### ISSUE TITLE
Auto update plugin files

### ISSUE THREAD

**Issue by Fyphen1223** [lavalink-devs/Lavalink#1014]
### Change request

Lavalink should update its plugins if the user specified to do so.
Completely automatically updating them can be dangerous in some cases, so that should be in option.
(Or implementing auto update with plugin itself is the priority?)

### Relevance

This will be pretty beneficial for some cases.

### Could this be a plugin instead?

Half yes, half no, since not all of the plugins will provide automatic update.

### Checklist

- [X] I have checked for duplicate issues
- [X] I have checked for existing plugins

**Comment by topi314** [comment]
Lavalink already updates your plugins when you specify a new version in your `application.yml`

**Comment by Fyphen1223** [comment]
Oof, I mean, auto updating version in application.yml, not retrieving the specified version automatically.

**Comment by topi314** [comment]
I don't see how this would be a good idea
Updating software should be a manual process
What if a newer plugin version introduce breaking changes all of the sudden?

**Comment by Fyphen1223** [comment]
I was thinking of implementing rule system of updating plugins. Like not updating to a new version if the version name contains specific strings, or not updating plugins if the version name contains changes in MAJOR update indicator.

**Comment by freyacodes** [comment]
A technical problem with this is that we would need to somehow overwrite the configuration. Even if we assume that you configured Lavalink with a non-JSON YAML file, and we are somehow able to detect it, overwriting that file is still tricky.

**Comment by topi314** [comment]
Plugin devs are not required to follow semver spec nor should they be required to
This sounds overcomplicated for no actual benefit

If anything there could be a cli tool to update plugin versions to their latest releases via a manual command

All in all I don't think this is an issue at all
Plugins tend to not update that often

**Comment by topi314** [comment]
I think it would be beneficial to know which actual issue this feature request should solve

**Comment by Fyphen1223** [comment]
i use many plugins(not so many, about 5 or 6 I think) with my project, and I'm so tired of updating each plugins manually. I have to check the plugins webpage, and write it down if the update is available.
So I wanted to make Lavalink able to update its plugins automatically.

**Comment by topi314** [comment]
you can watch projects on github and get notified about new releases
![image](https://github.com/lavalink-devs/Lavalink/assets/15636011/8afaae49-2b93-4d8c-81ab-50c29880b570)
