### ISSUE TITLE
Unable to play music "Error in loading item ytsearch"

### ISSUE THREAD

**Issue by muralianand12345** [lavalink-devs/Lavalink#1021]
I'm encountering an error when attempting to play Spotify music using Lavalink version 4.0.3 with LavalinkSrc version 4.0.1. The issue arises when I try to play a song, and the error message is as follows:

`connection successfully established from Magmastream 2024-03-09T21:55:02.092+05:30  INFO 13 --- [  XNIO-1 task-2] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://open.spotify.com/track/6E90gq0KO6FYZVOXx8kCcC?si=2451168c8452401b" 2024-03-09T21:55:03.288+05:30  INFO 13 --- [  XNIO-1 task-2] lavalink.server.player.AudioLoader       : Loaded track Astronaut In The Ocean 2024-03-09T21:55:04.011+05:30  INFO 13 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=https%3A%2F%2Fopen.spotify.com%2Ftrack%2F6E90gq0KO6FYZVOXx8kCcC%3Fsi%3D2451168c8452401b, client=172.16.4.1 2024-03-09T21:55:04.601+05:30  INFO 13 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/20nxtgs8x9sdy2jo/players/1011894951635853342?noReplace=false, client=172.16.4.1, payload={"encodedTrack":"QAACFAMAFkFzdHJvbmF1dCBJbiBUaGUgT2NlYW4AC01hc2tlZCBXb2xmAAAAAAACBqwAFjZFOTBncTBLTzZGWVpWT1h4OGtDY0MAAQA1aHR0cHM6Ly9vcGVuLnNwb3RpZnkuY29tL3RyYWNrLzZFOTBncTBLTzZGWVpWT1h4OGtDY0MBAEBodHRwczovL2kuc2Nkbi5jby9pbWFnZS9hYjY3NjE2ZDAwMDBiMjczNTgwYTA3ZjEzZWNlMWJkMzBkMzdiZDgwAQAMVVNBVDIyMTAwMDE3AAdzcG90aWZ5AQAMQXN0cm9ub21pY2FsAQA1aHR0cHM6Ly9vcGVuLnNwb3RpZnkuY29tL2FsYnVtLzZxTk1Zc3g1T1VGRFhXQW9jdDlQZ2UBADZodHRwczovL29wZW4uc3BvdGlmeS5jb20vYXJ0aXN0LzF1VTdnM0ROU2JzdTBRalNFcVp0RWQBAEBodHRwczovL2kuc2Nkbi5jby9pbWFnZS9hYjY3NjE2MTAwMDBlNWViNzA0ZTMxNGU1YmZiOGRlODA0Y2U2ZjFjAQBraHR0cHM6Ly9wLnNjZG4uY28vbXAzLXByZXZpZXcvZTg5ZTQ3N2MyNDY3YzQ3NzAzMTU2MWZmODAxYzA1NWM1Nzc3ZGU0Zj9jaWQ9OThiMGNhMzczYjliNGI5YTkyYmQ0MmIyMjgzYjE4YzYAAAAAAAAAAAA="} 2024-03-09T21:55:04.938+05:30 ERROR 13 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item ytsearch:"USAT22100017" com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:205) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:164) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:175) ~[lavaplayer-2.1.0.jar!/:na] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na] at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na] Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for search response: 400 at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:59) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:71) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:284) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:250) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:412) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:394) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:156) ~[lavaplayer-2.1.0.jar!/:na] ... 5 common frames omitted Caused by: java.io.IOException: Invalid status code for search response: 400 at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:63) ~[lavaplayer-2.1.0.jar!/:na] ... 13 common frames omitted 2024-03-09T21:55:04.991+05:30 ERROR 13 --- [back-1-thread-1] t.l.m.DefaultMirroringAudioTrackResolver : Failed to load track from provider "ytsearch:"USAT22100017""! java.util.concurrent.CompletionException: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[na:na] at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[na:na] at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.loadItem(MirroringAudioTrack.java:94) ~[lavasrc-plugin-4.0.1.jar!/:na] at com.github.topi314.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:50) ~[lavasrc-plugin-4.0.1.jar!/:na] at com.github.topi314.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:10) ~[lavasrc-plugin-4.0.1.jar!/:na] at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:43) ~[lavasrc-plugin-4.0.1.jar!/:na] at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.1.0.jar!/:na] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na] at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na] Caused by: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:205) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:164) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:175) ~[lavaplayer-2.1.0.jar!/:na] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na] ... 3 common frames omitted Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for search response: 400 at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:59) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:71) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:284) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:250) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:412) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:394) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:156) ~[lavaplayer-2.1.0.jar!/:na] ... 5 common frames omitted Caused by: java.io.IOException: Invalid status code for search response: 400 at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:63) ~[lavaplayer-2.1.0.jar!/:na] ... 13 common frames omitted 2024-03-09T21:55:05.223+05:30 ERROR 13 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item ytsearch:Astronaut In The Ocean Masked Wolf com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:205) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:164) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:175) ~[lavaplayer-2.1.0.jar!/:na] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na] at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na] Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for search response: 400 at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:59) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:71) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:284) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:250) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:412) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:394) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:156) ~[lavaplayer-2.1.0.jar!/:na] ... 5 common frames omitted Caused by: java.io.IOException: Invalid status code for search response: 400 at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:63) ~[lavaplayer-2.1.0.jar!/:na] ... 13 common frames omitted 2024-03-09T21:55:05.226+05:30 ERROR 13 --- [back-1-thread-1] t.l.m.DefaultMirroringAudioTrackResolver : Failed to load track from provider "ytsearch:Astronaut In The Ocean Masked Wolf"! java.util.concurrent.CompletionException: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413) ~[na:na] at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2118) ~[na:na] at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.loadItem(MirroringAudioTrack.java:94) ~[lavasrc-plugin-4.0.1.jar!/:na] at com.github.topi314.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:50) ~[lavasrc-plugin-4.0.1.jar!/:na] at com.github.topi314.lavasrc.mirror.DefaultMirroringAudioTrackResolver.apply(DefaultMirroringAudioTrackResolver.java:10) ~[lavasrc-plugin-4.0.1.jar!/:na] at com.github.topi314.lavasrc.mirror.MirroringAudioTrack.process(MirroringAudioTrack.java:43) ~[lavasrc-plugin-4.0.1.jar!/:na] at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[lavaplayer-2.1.0.jar!/:na] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na] at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na] Caused by: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:205) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:164) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$loadItem$0(DefaultAudioPlayerManager.java:175) ~[lavaplayer-2.1.0.jar!/:na] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na] ... 3 common frames omitted Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for search response: 400 at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:59) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:71) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:284) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:250) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:39) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:412) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:394) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.loadItemSync(DefaultAudioPlayerManager.java:156) ~[lavaplayer-2.1.0.jar!/:na] ... 5 common frames omitted Caused by: java.io.IOException: Invalid status code for search response: 400 at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-2.1.0.jar!/:na] at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:63) ~[lavaplayer-2.1.0.jar!/:na] ... 13 common frames omitted 2024-03-09T21:55:05.289+05:30  INFO 13 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/20nxtgs8x9sdy2jo/players/1011894951635853342?noReplace=false, client=172.16.4.1, payload={"encodedTrack":null} 2024-03-09T21:55:11.408+05:30  WARN 13 --- [ager-3-thread-1] c.s.d.l.tools.GarbageCollectionMonitor   : Suspicious GC results for the last 2 minutes: [Bucket 0 = 16] [Bucket 20 = 0] [Bucket 50 = 3] [Bucket 200 = 1] [Bucket 500 = 0] [Bucket 2000 = 0] `

I've contacted the LavalinkSrc dev and they responded this issue is related to lavalink

**Comment by topi314** [comment]
Tracked in https://github.com/lavalink-devs/lavaplayer/issues/69
