### ISSUE TITLE
Youtube search but doesnt play

### ISSUE THREAD

**Issue by SuupraaaMK4** [lavalink-devs/Lavalink#1055]
Im using Lavalink latest version with youtube-source 1.3.0 and poru 5.1.0. Yesterday works perfectly but now, it search the song but finish queue instantly. I test in another server (both mine, same config and verison) and works, so why this happen?

**Comment by devoxin** [comment]
Logs.

**Comment by Fizayy** [comment]
Same here, music start and stop instant even with spotify

**Comment by ErrorDoc404** [comment]
it fetch the song join the vs but didn't play and skip the song

**Comment by lunaseraphica** [comment]
maybe the songs are explicit, that might be why it skips them.

**Comment by ErrorDoc404** [comment]
well black pink album is not and it working fine in Lavalink v3 but its skipping in v4

**Comment by lunaseraphica** [comment]
> well black pink album is not and it working fine in Lavalink v3 but its skipping in v4

try using the new youtube source plugin, disable built-in one, else blackpink songs have nsfw words in the korean language and the lavalink is denying it

**Comment by devoxin** [comment]
Lavalink does not block any tracks even if they are explicit

**Comment by lunaseraphica** [comment]
> Lavalink does not block any tracks even if they are explicit

oh? weird, cause it happened to me after removing the account from yt config

**Comment by ErrorDoc404** [comment]
can i have the applicaition.yml file for plugins because when I am trying to configure its not working

I have tried shoukaku, erela, poru

**Comment by lunaseraphica** [comment]
> can i have the applicaition.yml file for plugins because when I am trying to configure its not working
> 
> I have tried shoukaku, erela, poru

sure, here is it: [lavalink-configuration.zip](https://github.com/user-attachments/files/15846701/lavalink-configuration.zip)

**Comment by devoxin** [comment]
> > Lavalink does not block any tracks even if they are explicit
> 
> oh? weird, cause it happened to me after removing the account from yt config

Do you have the TVHTML5EMBEDDED client enabled?

**Comment by Fizayy** [comment]
With Spotify, I'm like you, maybe it's not just Youtube...

**Comment by lunaseraphica** [comment]
> > > Lavalink does not block any tracks even if they are explicit
> > 
> > 
> > oh? weird, cause it happened to me after removing the account from yt config
> 
> Do you have the TVHTML5EMBEDDED client enabled?

Oh THAT'S WHAT IT WAS FOR? omggg i am such an idiot

**Comment by Fizayy** [comment]
Did music working for someone ?
In my case, it found the music, start and instant stop...

**Comment by ErrorDoc404** [comment]
> Did music working for someone ? In my case, it found the music, start and instant stop...

try my lavalink
host: node1.kartadharta.xyz
pass: kdlavalink

**Comment by lunaseraphica** [comment]
add more clients to lavalink application config. I did the same and worked afterwards

**Comment by ErrorDoc404** [comment]
> > can i have the applicaition.yml file for plugins because when I am trying to configure its not working
> > I have tried shoukaku, erela, poru
> 
> sure, here is it: [lavalink-configuration.zip](https://github.com/user-attachments/files/15846701/lavalink-configuration.zip)

mine works after this

**Comment by Gabry2790** [comment]
There is any temporary fix for this?

**Comment by devoxin** [comment]
As I mentioned earlier in the threads, provide logs.

**Comment by Gabry2790** [comment]
How can I activate logs?

**Comment by Fizayy** [comment]
There is no error crash or something, it's just starting and instant finishing

**Comment by devoxin** [comment]
Logs provide more details than just an error. Please provide logs otherwise I can't assist.

**Comment by Gabry2790** [comment]
I will send my logs in a couple of minutes

**Comment by Gabry2790** [comment]
> Logs provide more details than just an error. Please provide logs otherwise I can't assist.

Here is my logs:
[spring.log](https://github.com/user-attachments/files/15937232/spring.log)

**Comment by devoxin** [comment]
> > Logs provide more details than just an error. Please provide logs otherwise I can't assist.
> 
> Here is my logs: [spring.log](https://github.com/user-attachments/files/15937232/spring.log)

```
2024-06-22T15:18:04.108Z TRACE 28 --- [XNIO-1 I/O-2] lavalink.server.io.SocketContext         : Sent {"op":"event","type":"TrackExceptionEvent","guildId":"1094611468571377754","track":{"encoded":"QAAApQMADU1FVEFNT1JQSE9TSVMACklOVEVSV09STEQAAAAAAAIumAALbEp2Um9oWVNyWk0AAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1sSnZSb2hZU3JaTQEAMGh0dHBzOi8vaS55dGltZy5jb20vdmkvbEp2Um9oWVNyWk0vbXFkZWZhdWx0LmpwZwAAB3lvdXR1YmUAAAAAAAAAAA==","info":{"identifier":"lJvRohYSrZM","isSeekable":true,"author":"INTERWORLD","length":143000,"isStream":false,"position":0,"title":"METAMORPHOSIS","uri":"https://www.youtube.com/watch?v=lJvRohYSrZM","sourceName":"youtube","artworkUrl":"https://i.ytimg.com/vi/lJvRohYSrZM/mqdefault.jpg","isrc":null},"pluginInfo":{},"userData":{}},"exception":{"message":"This video is unavailable","severity":"common","cause":"com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable"}}
```

`clients=[MUSIC, ANDROID, WEB]`

Add more clients, as was already stated earlier in this thread.
Edit: And also disable `ANDROID`'s playback capabilities. It's broken with no known fix.

**Comment by Gabry2790** [comment]
What clients should I add? This problem happens also with Spotify. The bot enters the vocal, fetch the song and leaves.

**Comment by devoxin** [comment]
That's up to you based on your requirements. At the very least, I would add `ANDROID_TESTSUITE` but if you wanted to add any more that would be at your own discretion.

Also why would Spotify be any different? It mirrors to whatever providers you have set, which tend to include youtube.

**Comment by Gabry2790** [comment]
Ok, thanks

**Comment by Gabry2790** [comment]
> That's up to you based on your requirements. At the very least, I would add `ANDROID_TESTSUITE` but if you wanted to add any more that would be at your own discretion.
> 
> Also why would Spotify be any different? It mirrors to whatever providers you have set, which tend to include youtube.

Doesn't work,
these are the clients:
      - MUSIC
      - WEB
      - ANDROID_TESTSUITE
      - TVHTML5EMBEDDED
      - IOS
      - ANDROID_LITE

**Comment by Fizayy** [comment]
Here my logs when i try to find a music and play it
[music.log](https://github.com/user-attachments/files/15937905/music.log)

**Comment by devoxin** [comment]
> Here my logs when i try to find a music and play it [music.log](https://github.com/user-attachments/files/15937905/music.log)

These are not your complete logs, nor have you enabled debug.

**Comment by happyzxzxz** [comment]
I have same Issue, check the end of the log
[spring (1).log](https://github.com/user-attachments/files/16090383/spring.1.log)

**Comment by devoxin** [comment]
> I have same Issue, check the end of the log [spring (1).log](https://github.com/user-attachments/files/16090383/spring.1.log)

```
2024-07-03T22:05:33.572+02:00 DEBUG 17 --- [main] d.l.youtube.plugin.YoutubePluginLoader   : No ratelimit config found, skipping setup of route planner

...

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: This video is unavailable
	at dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:60) ~[youtube-plugin-1.3.0.jar!/:na]
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98) ~[youtube-plugin-1.3.0.jar!/:na]
	at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadVideo(NonMusicClient.java:315) ~[youtube-plugin-1.3.0.jar!/:na]
```

Use IPv6 rotation.

**Comment by Gabry2790** [comment]
Enabling HTTP/2 support resolved the issue for me

**Comment by devoxin** [comment]
HTTP2 does not affect YouTube playback as Lavaplayer/youtube-source uses its own HTTP client separate from Spring. That setting only affects your WS/HTTP connections to the Lavalink server.

Toggling that setting is merely a coincidence.

**Comment by devoxin** [comment]
HTTP2 does not affect YouTube playback as Lavaplayer/youtube-source uses its own HTTP client separate from Spring. That setting only affects your WS/HTTP connections to the Lavalink server.

Toggling that setting is merely a coincidence.

**Comment by Gabry2790** [comment]
> HTTP2 does not affect YouTube playback as Lavaplayer/youtube-source uses its own HTTP client separate from Spring. That setting only affects your WS/HTTP connections to the Lavalink server.
> 
> Toggling that setting is merely a coincidence.

So, how is my Lavalink now working again?

**Comment by devoxin** [comment]
The last line of my message. It literally has no bearing on the youtube source manager lol... It doesn't even use that setting.

**Comment by Gabry2790** [comment]
Ok

**Comment by Gabry2790** [comment]
Today doesn't work anymore
[Uploading spring.log…]()

**Comment by Gabry2790** [comment]
Today doesn't work anymore
[spring.log](https://github.com/user-attachments/files/16116396/spring.log)

**Comment by devoxin** [comment]
You are still not using IP rotation nor have you enabled more clients.
```
2024-07-06T14:06:56.513Z  INFO 28 --- [main] d.l.youtube.plugin.YoutubePluginLoader   : YouTube source initialised with clients: WEB_REMIX, WEB, ANDROID 
2024-07-06T14:06:56.513Z DEBUG 28 --- [main] d.l.youtube.plugin.YoutubePluginLoader   : No ratelimit config found, skipping setup of route planner
```

Enable more clients, and enable IP rotation.

For anyone else that stumbles upon this issue, you ought to be using [youtube-source](https://github.com/lavalink-devs/youtube-source) by now, as well as doing what is stated above in this comment.

Closing and locking as this no longer belongs in this repo. Further issues are to be made within the `youtube-source` repository (providing you are using `youtube-source`, if you aren't, then refer to the above comment).
