### ISSUE TITLE
Track Broken

### ISSUE THREAD

**Issue by ghost** [lavalink-devs/Lavalink#1086]
## Description
![image](https://github.com/user-attachments/assets/4bfe0ef5-929f-41e8-a7f2-5d63a8572004)

## Version info
**Client used:** niizuki 1.0.10

Output of `java -version`:
![image](https://github.com/user-attachments/assets/e96d321c-3a51-4c4e-9b4d-e89c152b172a)

Lavalink Logs:
![image](https://github.com/user-attachments/assets/fffca4df-0bf1-4cb7-adb2-7bca9149bb87)

**Comment by ghost** [comment]
That error for all tracks.

**Comment by devoxin** [comment]
This is an error for youtube-source not Lavalink.
Also update your `youtube-source`.

**Comment by ghost** [comment]
> This is an error for youtube-source not Lavalink. Also update your `youtube-source`.

its already up to date.

**Comment by ghost** [comment]
also I just resolved that.

**Comment by devoxin** [comment]
> > This is an error for youtube-source not Lavalink. Also update your `youtube-source`.
> 
> its already up to date.

No it's not.
<img width="1274" alt="image" src="https://github.com/user-attachments/assets/3d568088-0dd0-4b91-9295-4a41a5fd7d61">

**Comment by wioniqle-q** [comment]
so youre sayin for youtube-source for like plugin? or sometin

**Comment by ghost** [comment]
ah okey thanks
