### ISSUE TITLE
Songs restart randomly without a request being sent

### ISSUE THREAD

**Issue by BENx2115** [lavalink-devs/Lavalink#1092]
## Description
Since August 11th I have had the problem that songs are restarted without an error message or log in Lavalink, apparently only on YouTube.

## To Reproduce
Occurs randomly and is not reproducible

## Version info
**Client used:** lavalink-client (Node.js)

Output of `java -version`:
```
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

Lavalink Version:
```
4.0.7
```

YouTube Plugin:
```
1.5.2
```

**Comment by topi314** [comment]
you omitted significant info from the issue template, that being your logs
as you said this happens with youtube this is the wrong repo to raise such issues.
see https://github.com/lavalink-devs/Lavalink/issues/1091
