### ISSUE TITLE
Feature Request - LLM endpoint

### ISSUE THREAD

**Issue by Tomato6966** [lavalink-devs/Lavalink#1096]
Springboot 3.3 supports [Spring AI](https://spring.io/projects/spring-ai) and thus LLMs (Large Language Model)

therefore you could theoretically implement LLM endpoints to lavalink either through a plugin or nativly. e.g. voice-to-text or text-to-voice.

My config idea is, a prop for enabling + a prop for api key and maybe model/provider?

It's just an idea.

**Comment by topi314** [comment]
there is a Change Request issue template, follow it
