### ISSUE TITLE
Getting error while playing songs

### ISSUE THREAD

**Issue by anas-ike** [lavalink-devs/Lavalink#1099]
Player got exception 
This error in LavaLink console 
![IMG_20240821_030624](https://github.com/user-attachments/assets/45b245eb-b8aa-4831-a67d-8cefbe62c925)
This error in bot console 
![Screenshot_20240821_212806](https://github.com/user-attachments/assets/ed367fa3-0e04-4c47-9b63-ad02f3dc4aaf)

**Comment by devoxin** [comment]
Don't use the built-in YouTube source manager.
