### ISSUE TITLE
[Docs] Link to example bot in Readme leads to 404

### ISSUE THREAD

**Issue by Wayrion** [lavalink-devs/Lavalink#1122]
### Change request

Remove link / update the link to the code for the TestBot

### Relevance

Might be helpful for people getting started

### Could this be a plugin instead?

No

### Checklist

- [X] I have checked for duplicate issues
- [X] I have checked for existing plugins

**Comment by topi314** [comment]
resolved in https://github.com/lavalink-devs/Lavalink/commit/88cc85978198f75b662990b1ed0b0e9c77cd347b
