### ISSUE TITLE
[FR] Crossfade, EQ and filter support

### ISSUE THREAD

**Issue by Diniboy1123** [lavalink-devs/Lavalink#130]
It'd be incredibly amazing if our clients could change the EQ settings during the playback or if it'd support the lavaplayer filters.

**Comment by schnapster** [comment]
While not out of scope for this project, I don't think any of the current maintainers of this project (please correct me if I'm wrong) have an active interest in developing such a feature, so contributions on this issue would be very much welcome.

**Comment by freyacodes** [comment]
Crossfade is really tricky for three reasons:
* it requires two players active at the same time
* it requires mixing of the two players
* Lavalink doesn't know the next track in advance, and so the protocol would need to be changed to support this use-case

It's also relatively CPU intensive.

**Comment by Yucked** [comment]
Wouldn't it be possible to fire an event 10+- seconds before the track ends? Users can then handle the crossfade themselves.

**Comment by Shredder121** [comment]
No one can handle the crossfade themselves.
Lavalink does all the audio handling for you.

**Comment by Yucked** [comment]
Well, my point was Lavalink doesn't know what track is going to play next and there is no built in queue system iirc, most of the users handle their next tracks once a track has ended. But before the track ends Lavalink can fire an event in advance to let users know from there on user can use a timer or whatever to lower the volume as track ends and increase the volume as the next track starts playing.

**Comment by freyacodes** [comment]
@Yucked 
* That's not crossfading, that's just fading in and out. With crossfading you have two tracks simultaneously fading out and in respectively.
* You can already predict when a track is about to end.
* You'd have to send a lot of volume messages if you want the transition to sound smooth.

**Comment by Yucked** [comment]
Thanks for clearing that up. Just realized how heavy that'd be on the server.

**Comment by AndyTempel** [comment]
Referencing solution for __***EQ***__ to #154

**Comment by freyacodes** [comment]
@AndyTempel the PR only addresses equalization

**Comment by Diniboy1123** [comment]
I started working on this and you were right. It's too much work on the cost of a lot of CPU consumption.

**Comment by Shredder121** [comment]
Thanks for researching this btw. Let's hope others also read this and understand that it is impossibly hard to get working smoothly. (for some definition of smooth)
