### ISSUE TITLE
Twitch support broken

### ISSUE THREAD

**Issue by xXBuilderBXx** [lavalink-devs/Lavalink#136]
Hey looks like Twitch changed something and now support for it is broken in Lavalink anyone know why?
Version 2.1 and also tried 2.2 no luck

LavaLink https://i.imgur.com/IiGjEIa.png
Bot 1 https://i.imgur.com/4QhQA8w.png
Bot 2 https://i.imgur.com/QZwZX9k.png

**Comment by devoxin** [comment]
Lavaplayer issue https://its-called-hentai-and-its.art/fcb09a53a3.png

**Comment by schnapster** [comment]
Related: https://github.com/sedmelluq/lavaplayer/pull/126

**Comment by Zenrac** [comment]
https://github.com/sedmelluq/lavaplayer/pull/132 should fix it but it's not getting merged

**Comment by GigaFyde** [comment]
132 indeed fixes the twitch support

**Comment by davipatury** [comment]
sedmelluq/lavaplayer#132 has been merged.

**Comment by freyacodes** [comment]
@davipatury I'm waiting for a new release

**Comment by freyacodes** [comment]
v3.1.0.1 was released, adressing this issue.
