### ISSUE TITLE
[LavalinkClient] Not keeping track of channel moves

### ISSUE THREAD

**Issue by schnapster** [lavalink-devs/Lavalink#14]
When the bot is moved in the discord client from one channel to another, the LavalinkClient does not recognize that.

Probably needs a class similar to the `VoiceServerUpdateInterceptor.java` hooked in to 
`VOICE_STATE_UPDATE` similar to this line:
https://github.com/Frederikam/Lavalink/blob/51ec2c63983f965743bf1cc26f19d7fb1b6d4f3d/LavalinkClient/src/main/java/lavalink/client/io/Lavalink.java#L179

**Comment by freyacodes** [comment]
Might not be necessary to intercept the message. Maybe we can just rely on JDA's event system like we do with voice leave

**Comment by schnapster** [comment]
Can also think about removing the tracking of the current voice channel. It seems to work fine without exactly knowing where it is.

**Comment by freyacodes** [comment]
Not really, the `Link` class would try to connect to the wrong channel when changing node
