### ISSUE TITLE
REST API: Extremely slow response time on Youtube MIX playlists.

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [lavalink-devs/Lavalink#141]
Youtube can make temporary playlists called mixes for the user. The difference between these and normal playlists is that the video's aren't numbered and once all 50 are watched another 50 get added (plus they exist temporary). For the Youtube API these should behave just like a normal playlist. But for some reason I had Lavalinks REST API take 20 seconds to perform a request to a Youtube mix.

These are response times I collected with Postman:
https://sharex.reinfernhout.xyz/i/20ufF.png

When testing with the Youtube API I found no longer response times for Youtube mixes myself.

**Comment by schnapster** [comment]
_Could_ be an issue that's happening in lavaplayer, we've noticed very long loading times for mixes/playlists in the past.
Do the long loading times happen consistently? Or just "under load", like when several users are requesting mixes?

**Comment by freyacodes** [comment]
This is a lavaplayer issue. Please submit upstream https://github.com/sedmelluq/lavaplayer
