### ISSUE TITLE
Send the Lavalink-Major-Version header in REST responses

### ISSUE THREAD

**Issue by Emzi0767** [lavalink-devs/Lavalink#142]
As per docs: 

- Lavalink v3.0 now reports its version as a handshake response header. Lavalink-Major-Version has a value of 3 for v3.0 only. It's missing for any older version.

This would be a very useful feature, if not for the fact that most WS libraries do not expose the handshake, and thus provide no ability to recover that header. While at present it's possible to distinguish Lavalink 3.x and 2.x by checking REST response type (array vs object), this is a fragile approach that might not work in the future.

**Comment by freyacodes** [comment]
As per https://github.com/Frederikam/Lavalink/pull/137, the "api" version is what's relevant.

**Comment by luaugg** [comment]
building on top of what fred said, we could add another header with api version for v3/v4, or exclude the major header and just go by api.

most libraries didn't recognize the version header atm btw. ones that do, like my own, will treat nodes as if they're running v2 if the header isn't sent or if its value doesn't equal "3". it would thus be better to update ws headers and add rest headers in v4 if the old one is removed, or add them to v3 if the old one isn't removed.
