### ISSUE TITLE
Handshake SSL

### ISSUE THREAD

**Issue by jakhub69** [lavalink-devs/Lavalink#145]
Can't play music from youtube.
https://pastebin.com/raw/ZE4BXW36

**Comment by Abi45x** [comment]
What java distribution and version are you on?
(I.e OpenJDK 10 or Oracle JDK 10)

**Comment by Abi45x** [comment]
Also this issue tracker is not for general support questions. Please seek help at https://discord.gg/cgPFW4q

**Comment by kvbz** [comment]
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)

**Comment by jakhub69** [comment]
openjdk version "10.0.2" 2018-07-17

**Comment by Abi45x** [comment]
Resolved by moving from OpenJDK 10 to OracleJDK 10

This can be closed

**Comment by freyacodes** [comment]
> Also this issue tracker is not for general support questions. Please seek help at https://discord.gg/cgPFW4q

@Raven-Rose Not a "general support question", please don't refer to FredBoat support. This is a lavaplayer issue if anything, and has nothing to do with FredBoat.

**Comment by Abi45x** [comment]
My bad sorry, noted for next time
