### ISSUE TITLE
[BUG] NPE crash

### ISSUE THREAD

**Issue by Ahriana** [lavalink-devs/Lavalink#148]
during development of our new lib / bot we have been having issues with lava player NPE causing a stack and for LavaLink to exit which causes all connections to the player to close etc

the issue seams to be when a shard restarts and reconnects to discord (and to lava) which will eventually timeout lavalink's connection to discord due to no resume support which is fine.

the expected behaviour would be on a socket close to have the error be handled so other connections dont also get destroyed (i dont think a lavalink instance per shard is desired), im most likely hitting this issue more than anyone else due to the rate we are restarting shards and bots.

NPE below: 
```
java.lang.NullPointerException: null
    at lavalink.server.io.SocketServer.close(SocketServer.java:130)
    at lavalink.server.io.SocketServer.onClose(SocketServer.java:122)
    at org.java_websocket.server.WebSocketServer.onWebsocketClose(WebSocketServer.java:595)
    at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:504)
    at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:515)
    at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:563)
    at org.java_websocket.SocketChannelIOHelper.read(SocketChannelIOHelper.java:42)
    at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:406)
    at java.lang.Thread.run(Thread.java:834)
```

if there is anything else i can provide please let me know

**Comment by freyacodes** [comment]
Just to clarify, how many Lavalink connections do you have?

**Comment by Ahriana** [comment]
this issue can be done with just 1

**Comment by freyacodes** [comment]
This is the line in question: https://github.com/Frederikam/Lavalink/blob/master/LavalinkServer/src/main/java/lavalink/server/io/SocketServer.java#L130

Assuming you are on the same version, it seems that `getRemoteSocketAddress()` returns null, which is odd. You could try using https://github.com/Frederikam/Lavalink/pull/147 which replaces the old WS server.

https://ci.fredboat.com/repository/download/Lavalink_Build/5192:id/Lavalink.jar?guest=1

Also be sure to migrate your config https://github.com/Frederikam/Lavalink/commit/68be2ecbe23a29991b7fc321aed185b4bafc193b

**Comment by Ahriana** [comment]
i will try it and get back to you

**Comment by Ahriana** [comment]
~~is it possible to contact you on discord? having some unrelated issues with this build 
`Rose (RC) Jackson#0207`~~

was an issue my end, testing the version you linked now

**Comment by Ahriana** [comment]
👌 seams to have resolved the crash, throws `java.io.IOException: UT002002: Channel is closed` instaid but its not critical.

thank you for this!

**Comment by freyacodes** [comment]
Glad I could help
