### ISSUE TITLE
/natives/linux-arm/libconnector.so was not found

### ISSUE THREAD

**Issue by AlekEagle** [lavalink-devs/Lavalink#152]
When I go to play a track I get this error, I was able to find the missing library, but I need to figure out where to put it, since I'm using eris-lavalink as my client.

**Comment by calebj** [comment]
Related to #52. Lavalink doesn't run very well on embedded architectures like ARM, but it's possible.

You'll need to add `libconnector.so` to the `lavaplayer-natives` jar, then repack it into the Lavalink jar like so:
```sh
mkdir -p Lavalink-tmp/tmp/lavaplayer-natives ; pushd Lavalink-tmp
unzip ../Lavalink.jar
pushd tmp/lavaplayer-natives
unzip ../../BOOT-INF/lib/lavaplayer-natives-1.2.55.jar
mkdir -p natives/linux-arm/
cp ../../../libconnector.so natives/linux-arm/
jar -cvfm ../../BOOT-INF/lib/lavaplayer-natives-1.2.55.jar META-INF/MANIFEST.MF .
popd
rm -rf tmp/
jar -cvf0m ../Lavalink-repack.jar META-INF/MANIFEST.MF .
popd
rm -rf Lavalink-tmp
```
This assumes you have `libconnector.so` and `Lavalink.jar` in the cwd. You might also need `libudpqueue.so`.

I also have a PR (sedmelluq/lavaplayer#137) that would remove the need to repack jars to run Lavalink on platforms that don't have bundled libraries.

**Comment by AlekEagle** [comment]
I did all of that and sure enough I do need libudpqueue.so

**Comment by AlekEagle** [comment]
Has anyone made an ARM-bit libudpqueue.so yet? The docker you left in the PR isn't working on my computer

**Comment by calebj** [comment]
It's Docker, and should work on any x86 machine. But I won't support it here. Here are the libraries I built for all ARM variants:
[out-linux-arm.tar.gz](https://github.com/Frederikam/Lavalink/files/2499535/out-linux-arm.tar.gz). Repacking the udp-queue jar works the exact same way as the lavaplayer one.

**Comment by AlekEagle** [comment]
Thanks! I'll have them repacked in a few, thanks for all the help you have provided
