### ISSUE TITLE
Does anyone have the 3089 build for lavalink?

### ISSUE THREAD

**Issue by Myqzz** [lavalink-devs/Lavalink#161]
If so can I please have a link to download it, thanks.

**Comment by freyacodes** [comment]
It's not clear what version of Lavalink you are looking for

**Comment by shikhir-arora** [comment]
That's a really old build (from February 28) -- and looks like the (public) history only goes back to 3281, but that's [**really** old as well](https://ci.fredboat.com/viewLog.html?tab=artifacts&buildId=3281&guest=1). 

You sure you want that? 🤔 

https://ci.fredboat.com/repository/download/Lavalink_Build/3281:id/Lavalink.jar?guest=1


![screenshot 2018-12-08 13 12 24](https://user-images.githubusercontent.com/8797918/49689136-ec62f680-faea-11e8-9bf5-0f4e8e186cf5.png)
