### ISSUE TITLE
How do I get the 'event' specified in IMPLEMENTATION.md?

### ISSUE THREAD

**Issue by shreyaslad** [lavalink-devs/Lavalink#166]
So do I have to POST this 'event' to where Lavalink is or do I receive it from Discord?

```bash
{
    "op": "voiceUpdate",
    "guildId": "...",
    "sessionId": "...",
    "event": "..."
}
```

If I have to post it, where do I get `event` from?

**Comment by freyacodes** [comment]
It is the payload of a voice server update, formatted as a string https://discordapp.com/developers/docs/topics/voice-connections#retrieving-voice-server-information-example-voice-server-update-payload

It has to be forwarded to Lavalink from Discord, to authenticate yourself with the voice server.

**Comment by shreyaslad** [comment]
so I have to dump all that json to where Lavalink is setup with a post request?

**Comment by freyacodes** [comment]
Lavalink is primarily managed by websocket. See https://github.com/Frederikam/Lavalink/blob/master/IMPLEMENTATION.md#opening-a-connection

For further support, please use our discord channel.
