### ISSUE TITLE
Dispatch events/updates in response to successful requests

### ISSUE THREAD

**Issue by luaugg** [lavalink-devs/Lavalink#169]
this is the biggest thing lavalink misses imo so far, and has already inspired the creation of 2 different audio node servers that do notify clients of successful updates.

what i mean by this is, let's say you set the volume to 200. how do you know it worked? what if you got an error? you can't (easily) and there's no (good) workaround to knowing something succeeded or errorred. i hope lavalink will get this functionality one day as it's pretty annoying having to just rely and hope that everything went right. what if i want to know that i updated the volume? what if i want to know what bands changed and to what values? what if i want to see if lavalink errored? all of this information can be pretty helpful to bot developers and i think it's worth adding.

so far, there's no way to be certain of volume updates, pausing/resuming or tracks starting, and while the reason given for that is that they're all client side, the point i'm trying to make is that the clients depend on the server for all their functionality and can't be sure of the vast majority of that, and in the rare-ish chance that an error does happen, clients don't know of that.

**Comment by freyacodes** [comment]
On a side note, I'm not sure if the volume operation can fail, aside from syntax errors.

**Comment by luaugg** [comment]
i guess so, but it's always helpful to have extra information. if the server does error, the client(s) get notified. if they play tracks, they can rely on the server to actually confirm that before updating their state, similarly with pausing/resuming or equalizer updates or volume updates.

**Comment by topi314** [comment]
to provide an update here. 
The current rest-api proposal in https://github.com/freyacodes/Lavalink/pull/750 would cover this

**Comment by topi314** [comment]
implemented in https://github.com/freyacodes/Lavalink/releases/tag/3.7.0
