### ISSUE TITLE
Weird application.yaml causes stupid problems

### ISSUE THREAD

**Issue by melmsie** [lavalink-devs/Lavalink#171]
While I admit I'm an idiot for not realizing the issue sooner, I spent the better part of 12 hours figuring out why lavalink would silently exit with NO logs at all.

Turns out my application.yaml was causing the problem. After deleting it, lavalink worked fine. Would be super nice for future people if some error was thrown for them to see.

Current functionality: https://i.imgur.com/mbtPrYT.png

**Comment by melmsie** [comment]
Here's what my application.yaml looks like, I'm actually not seeing what's wrong with it?

```server: # REST and WS server
  port: 2333
  address: 0.0.0.0
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: "password"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 10
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: "url"
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB\

  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
```

**Comment by freyacodes** [comment]
The first line was missing, making this YAML invalid. The logging is handled by Spring Boot, but Spring Boot can't start if the configuration is malformed, thus no logging directory was set. 

~~The error should have been apparent if you had read the output of stdin.~~

Edit: Did not see the screenshot. Did not know Spring Boot was capable of doing that.

**Comment by melmsie** [comment]
Alright, thanks.
