### ISSUE TITLE
Debug endpoint disable feature

### ISSUE THREAD

**Issue by Diniboy1123** [lavalink-devs/Lavalink#173]
I personally find the debug endpoint really useful, so I would happily use it for some stuff that the stats endpoint won't send to me (like the lavalink server version), however it's not really a wise idea to have this endpoint open for "public" lavalink instances, where not just one, but many owners share the same server. I don't want them to break any internal or execute remote code on the server. So a config boolean definition would be awesome to have.

PS: are there any plans on multiple passwords?

https://github.com/Frederikam/Lavalink/blob/a6f5631b0ddd4b25a7e6720ae3f08c3a0a9729b5/LavalinkServer/src/main/java/lavalink/server/util/DebugRestHandler.java#L58-L83

**Comment by schnapster** [comment]
The debug endpoint has its own password. Also setting no debug password (less than 8 characters) essentially disables it.

**Comment by schnapster** [comment]
> PS: are there any plans on multiple passwords?

I'm positive that quality contributions of that feature would be welcome.

**Comment by Diniboy1123** [comment]
Oh that's more than awesome! Thank you
