### ISSUE TITLE
Audio Normalization

### ISSUE THREAD

**Issue by mroodadabooga666666666** [lavalink-devs/Lavalink#178]
Please implement some form of audio normalization so different tracks aren't at vastly different volumes.

https://wiki.hydrogenaud.io/index.php?title=ReplayGain

**Comment by freyacodes** [comment]
Transferred to Lavalink, as this would have to be implemented in Lavalink first, at least in order to get the relative audio level.

**Comment by topi314** [comment]
With the release of lavalink v3.5 you can add your own audio filters via plugins. 
This should probably be doable to implement using this new API.
As a result I'm gonna close this as it can be implemented outside of lavalink.
