### ISSUE TITLE
Required library at /natives/darwin/libudpqueue.dylib was not found

### ISSUE THREAD

**Issue by chaNcharge** [lavalink-devs/Lavalink#180]
Happens on a fresh installation of Lavalink (build 759) and macOS 10.13.6 running Java 11 (AdoptOpenJDK with openj9)

Error in console when attempting to play music:
https://hastebin.com/tacofexace

**Comment by LoryCS** [comment]
You have to manually insert in the .jar file the directory `natives/darwin` which must contain [this file](https://github.com/sedmelluq/jda-nas/tree/master/udp-queue-natives/dist/darwin). Or at least that's how I solved it.

**Comment by chaNcharge** [comment]
Hm, I'll try that, but I remember it used to work fine on a mac, and now it suddenly isn't included anymore?

**Comment by shikhir-arora** [comment]
> Hm, I'll try that, but I remember it used to work fine on a mac, and now it suddenly isn't included anymore?

@chaNcharge Here's a repacked JAR that should work on macOS, from Lavalink build 759. 

https://www.dropbox.com/s/gkcrahoik8if3tx/Lavalink759-macOS.jar?dl=1

**Comment by chaNcharge** [comment]
This is useful, thanks! Any chance it will get re-added into the main builds on the CI server?

**Comment by aikaterna** [comment]
If you encounter 403 errors while trying to play tracks, a newer Mac jar is available at https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.2.0.3_796 that includes Lavaplayer 1.3.17. The 759 build linked here uses 1.3.10 and 403's can be a common issue with that version now.

**Comment by topi314** [comment]
with [`v3.5.0`](https://github.com/freyacodes/Lavalink/releases/tag/3.5) lavalink added support for darwin including intel & arm.
