### ISSUE TITLE
Add volume value to playerUpdate

### ISSUE THREAD

**Issue by MrJacz** [lavalink-devs/Lavalink#182]
It would be nice to have some way to access volume without storing it in the lib each time its set.
I think playerUpdate would be the correct incoming message.

**Comment by freyacodes** [comment]
Sorry for the super late response, didn't see this before now.

I believe that would be bad API design. Why should the server remind the client every few seconds when the client can just remember the value?

**Comment by schnapster** [comment]
I think it's a reasonable proposal. Since the server is the single point of truth for the volume, there should probably be a way to grab it. A REST that provides this information on demand could be a better choice tho.

**Comment by MrJacz** [comment]
I would just include it in playerUpdate. its not like it would effect anything as its only adding the property to it. I feel it makes more sense for the server to send the volume, it is the part that controls the volume after all.

**Comment by freyacodes** [comment]
The volume is only changed when the client asks it to.

Besides, the new filters system is going to treat volume as a filter, deprecating the old way of setting the volume or equalizer.

Edit: I am open to the idea of a general REST API, although I do not have the motivation to develop it personally. The WS protocol works just fine for my client.

**Comment by topi314** [comment]
to provide an update here. 
The current rest-api proposal in https://github.com/freyacodes/Lavalink/pull/750 would cover this

**Comment by topi314** [comment]
implemented in https://github.com/freyacodes/Lavalink/releases/tag/3.7.0
