### ISSUE TITLE
Throwing both exception and receing track end event

### ISSUE THREAD

**Issue by aschenkuttel** [lavalink-devs/Lavalink#189]
After confirming that it has nothing to do with the library I'm using (wavelink.py) I wanted to ask if it's intended to raise First a TrackException and then a TrackEnd Event if the song is age restricted (doesn't work). Should it not be just an Exception or End?

**Comment by freyacodes** [comment]
If you start playing a track, you should be guaranteed that it is only ended if you receive a track end event (or you disconnect).

What is the problem with also throwing an exception?

**Comment by aschenkuttel** [comment]
Thats an issue with age restricted videos only, track is found, Lavalink "plays" it, instantly throws an Exception and a TrackEnd Event after a second or so. Lavaplayer didn't support age-restricted stuff till today: https://github.com/sedmelluq/lavaplayer/commit/e9a23f7df9b405bfff7bb6e90cf1a55e95a7aa53

**Comment by freyacodes** [comment]
I'm confused now.

Is this an issue about our error handling or the lavaplayer issue? 

Please pick one.

**Comment by aschenkuttel** [comment]
I'm sorry ^^ 
Not my native language so hard to explain.
Lavaplayer didn't support age-restricted videos which led to my problem if you tried to play them via lavalink. Which resulted in the Exception and the TrackEnd afterwards.
But since they "patched" it works now.

**Comment by freyacodes** [comment]
Then this issue was fixed by https://github.com/Frederikam/Lavalink/commit/0ac18d970be085a6c0bf3554b127284c99bb177a
