### ISSUE TITLE
Audio not working from non-local instance of lavalink

### ISSUE THREAD

**Issue by lukastrkan** [lavalink-devs/Lavalink#195]
Hello, 
I am making discord bot and I have problem playing audio when Lavalink server is on different machine or in different docker container. 
It can connect to voice room, but there´s no playback. 
It works without any problem on same machine. 
Any ideas how to fix it?

**Comment by freyacodes** [comment]
We do not give general FredBoat support via Gitub issues (especially not from this repo). Please seek selfhosting support in our #selfhosting channel https://discord.gg/cgPFW4q
