### ISSUE TITLE
Feature request: Pitch & Playback speed control

### ISSUE THREAD

**Issue by LBlend** [lavalink-devs/Lavalink#196]
I have no idea whether it's easy to implement this but a way to change to the Pitch or Playback speed would be nice

**Comment by freyacodes** [comment]
Lavalink wraps around lavaplayer, which is the engine that provides all audio. Lavalink is there to provide remote control and an output to Discord.

This means that it would have to be implemented in Lavaplayer first. Even then, this would be horribly inefficient compared to just extracting and uploading the unchanged audio.

**Comment by LBlend** [comment]
Ok I see. Thanks for the response!

**Comment by schnapster** [comment]
LL could wrap https://github.com/natanbc/lavadsp or offer a way for end users to add their own filters, possibly by a plugin system (see https://github.com/Frederikam/Lavalink/pull/119 for a first iteration).

**Comment by MinnDevelopment** [comment]
This shouldn't be much more demanding than changing the volume I would assume.
