### ISSUE TITLE
JSONObject["volume"] is not an int.

### ISSUE THREAD

**Issue by duncte123** [lavalink-devs/Lavalink#197]
Sometimes when sending a volume opcode this exception gets internally thrown 
https://sentry.io/share/issue/a8e1284d7e314fd09ac0eabc6cb53120/
https://sentry.io/share/issue/c9f238c5786448b894aad74e7a4ae868/
The json payload is 
```json
{"volume":100,"op":"volume","guildId":"451579004370026511"}
```

I haven't been able to reliably reproduce this myself but I'll update this issue when I find a way to reproduce it

**Comment by freyacodes** [comment]
Are you certain that this is the exact payload you are sending? These are clearly JSON type errors.

**Comment by duncte123** [comment]
I'm not quite sure as there are no stacktraces in the console to check and the sentry traces trace back to the volume handler, I feel like this could be an issue with the wrapper I'm using (<https://github.com/FredBoat/Lavalink-Client/>)

**Comment by freyacodes** [comment]
You should be able to see the received message in the logs (but not in sentry)

**Comment by duncte123** [comment]
I've gone through several logs without any odd-looking results

[spring.log.2019-06-02.0.log](https://github.com/Frederikam/Lavalink/files/3252044/spring.log.2019-06-02.0.log)

[spring.log.2019-06-03.0.log](https://github.com/Frederikam/Lavalink/files/3252032/spring.log.2019-06-03.0.log)

**Comment by freyacodes** [comment]
Neither of those have the "is not an int" exceptions

**Comment by duncte123** [comment]
That's the annoying part, the exception happened somewhere within those logs but it's undetectable

**Comment by freyacodes** [comment]
Have you tried grep?
`grep -B 2 "is not an int" spring*`

**Comment by duncte123** [comment]
Actually, it seems that I have configured one of my lavalink nodes to use the wrong dsn.
This is what someone is sending and I know who to yell at, sorry for wasting your time
```json
{"volume":{"mutes":[],"cases":4,"prefix":"a!","modrole":"0","muterole":"0","adminrole":"0","defvolume":50,"logchannel":"583093638
```
