### ISSUE TITLE
Return FriendlyException from onTrackException

### ISSUE THREAD

**Issue by duncte123** [lavalink-devs/Lavalink#198]
I want to propose to return the FriendlyException that is passed to [onTrackException][trackex] so that the java client can make use of this and have the correct severity instead of it always being [SUSPICIOUS][currentsend].
This currently already is a feature for the `/loadtracks` endpoint but not for the WebSocket connection.

I would like to make a pull request to implement this, but before I do I want to know what people think about this (possibly breaking) change.

[trackex]: https://github.com/Frederikam/Lavalink/blob/dev/LavalinkServer/src/main/java/lavalink/server/player/EventEmitter.java#L69
[currentsend]: https://github.com/FredBoat/Lavalink-Client/blob/master/src/main/java/lavalink/client/player/event/AudioEventAdapterWrapped.java#L57

**Comment by devoxin** [comment]
[This is already implemented](https://github.com/Frederikam/Lavalink/blob/master/LavalinkServer/src/main/java/lavalink/server/player/EventEmitter.java#L80), unless you're specifically referring to severity and not the exception itself, in which case a new field (`severity`) could be added which shouldn't be breaking at all -- I'm all for this if so 👍

**Comment by duncte123** [comment]
@Devoxin What is implemented is only the message, I'm talking about adding 
```json
{
    "exception": {
        "message": "......",
        "severity": "....."
    }
}
``` 

and possibly removing the `error` field

**Comment by devoxin** [comment]
Perhaps have both, keep `error` but introduce the new exception object. That way, it remains backwards compatible and `error` can be dropped on the next major version change

**Comment by duncte123** [comment]
That's an excellent idea
