### ISSUE TITLE
[DOCKER] Error When Playing Certain Songs From YouTube

### ISSUE THREAD

**Issue by ZandercraftGames** [lavalink-devs/Lavalink#200]
Heya. Getting constant errors when trying to play certain songs like Closer from YouTube. Hopefully you can help me with this.

Here is the pastebin of the error: https://pastebin.com/kKcfinM9

**Comment by MrCakeSlayer** [comment]
I had a similar issue a few days ago, updating to the latest version of LavaLink solved it for me.

**Comment by ZandercraftGames** [comment]
@MrCakeSlayer Are you using the Fredboat Docker build?

**Comment by ZandercraftGames** [comment]
Because I just pulled from it again, using the latest version and it didn't work.

**Comment by ZandercraftGames** [comment]
Heres a pastbin of my docker-compose.yml file: https://pastebin.com/s2F9vSgf

**Comment by ghost** [comment]
I'm getting a very similar if not the same error when playing songs from certain channels on YouTube but on Lavalink 3.2 on my own bot. I'm not sure why specifics channels are giving problems yet. But I am getting this error. I think I'm having a similar problem like you since you said it's only certain songs from YouTube

Edit: updating to Lavalink 3.2.1 fixed the problem

**Comment by ZandercraftGames** [comment]
@itsfoxbit When was 3.2.1 released and how do I update to it? Because I have already pulled v3 latest from docker, so it should have updated. 
This is what it says its running though:
```Version:        ab81dcd46adf3e8a961dd57eacd2a1bde1233e6c-SNAPSHOT
Build:          590
Build time:     24.07.2018 17:30:47 CEST
Branch          v3
Commit:         ab81dcd
Commit time:    24.07.2018 17:29:40 CEST
JVM:            10.0.1
Lavaplayer      1.3.7
2019-06-15T12:54:46.179294503Z 
    :: Lavalink    ::       
    :: Spring Boot ::        (v2.0.2.RELEASE)```

**Comment by freyacodes** [comment]
I somehow missed this issue completely.

You can recreate the docker-compose container after pulling with `docker-compose up -d lavalink`.

**Comment by ZandercraftGames** [comment]
@Frederikam I already deleted the cached image and redownloaded it yesterday. Have you fixed it since then?

**Comment by freyacodes** [comment]
What is the version info? Are you sure you aren't still using a lavalink that is nearly a year old?

**Comment by ZandercraftGames** [comment]
@Frederikam  Are you sure the Docker image has been updated? My version info was pasted above your 1st post in this issue.

**Comment by freyacodes** [comment]
It was updated a week ago https://cloud.docker.com/u/fredboat/repository/docker/fredboat/lavalink

**Comment by ZandercraftGames** [comment]
Here are the steps I have taken:
• Stop and delete container in Kitematic
• Run docker rmi 4545d9ebe7f6
• Run docker-compose up --no-start
(It visibly downloads and extracts lavalink)
• Start the container
NOTE: you can see my docker-compose.yml in the pastebin linked earlier in this issue.

**Comment by ZandercraftGames** [comment]
Then it says:
```
Pulling lavalink (fredboat/lavalink:v3)...
V3:Pulling from fredboat/lavalink
c2ad77de49ce: Pull complete
9ada33455794: Pull complete
5d334d334f71: Pull complete
00ca44442357: Pull complete
e120f532e154: Pull complete
263c123fbeea: Pull complete
a42029de12df: Pull complete
Digest: (too long)
Status: Downloaded newer image for fredboat/lavalink:v3

**Comment by ZandercraftGames** [comment]
Also, the page you linked gives me a 404 error.

**Comment by freyacodes** [comment]
We don't push to the v3 branch anymore. It is not a version, it is a git branch. Instead you can pull from the master build of v3: `master-v3`

See https://hub.docker.com/r/fredboat/lavalink

**Comment by ZandercraftGames** [comment]
So I should just pull from plain old fredboat/lavalink or from master-v3?

**Comment by ZandercraftGames** [comment]
@Frederikam My bot is now returning a connection refused error:
```
INFO: Beginning startup sequence...
INFO: Scaling known. Total: 1, mine: 0
WARN: Git commit checking failed, falling back to version checking
INFO: Fully ready, serving 1159 guild(s).
ERROR: Error: connect ECONNREFUSED 172.18.0.3:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
ERROR: Error: connect ECONNREFUSED 172.18.0.3:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
WARN: LavaLink node ws://lavalink:80 disconnected!
```

**Comment by ZandercraftGames** [comment]
Worked before reinstall.

**Comment by freyacodes** [comment]
1. What do you think connection refused means?
2. Post logs

**Comment by ZandercraftGames** [comment]
![image](https://user-images.githubusercontent.com/28664144/59554717-4dc1c180-8f75-11e9-8c93-fdeab51f2c70.png)
![image](https://user-images.githubusercontent.com/28664144/59554720-5c0fdd80-8f75-11e9-8dc5-7f9f873cce16.png)
Network configuration Is the same in kitematic… Also to answer your question, connection refused could mean 1 of 2 things. One would be that the service exists and is refusing a connection, and the other would be that it is connecting to a service that doesn't exist or the wrong service.

**Comment by ZandercraftGames** [comment]
```
019-06-15 17:51:34.543  INFO 1 --- [           main] o.s.b.w.e.u.UndertowServletWebServer     : Undertow started on port(s) 2333 (http) with context path ''
2019-06-15 17:51:34.555  INFO 1 --- [           main] lavalink.server.Launcher                 : Started Launcher in 8.121 seconds (JVM running for 9.424)
```
Considering the fact that it doesn't seem to be receiving any connections at all...

**Comment by freyacodes** [comment]
Lavalink doesn't refuse connections itself.

it seems like you are trying to bind to port 80, by LL is running on 2333.

**Comment by ZandercraftGames** [comment]
![image](https://user-images.githubusercontent.com/28664144/59554771-77c7b380-8f76-11e9-9141-6aced6142d77.png)

**Comment by ZandercraftGames** [comment]
@Frederikam Running the websocket on port 80.

**Comment by freyacodes** [comment]
LAVALINK_SERVER_WS_PORT is no longer used, and was removed several months ago after a major update

https://github.com/Frederikam/Lavalink/blob/master/CHANGELOG.md#v31

**Comment by ZandercraftGames** [comment]
Why so?

**Comment by ZandercraftGames** [comment]
Just running them both on the same port now?

**Comment by ZandercraftGames** [comment]
```
ERROR: Error: getaddrinfo ENOTFOUND lavalink lavalink:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
ERROR: Error: getaddrinfo ENOTFOUND lavalink lavalink:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
WARN: LavaLink node ws://lavalink:80 disconnected!
```
Set it to 80 and this now happens.

**Comment by freyacodes** [comment]
That's a problem with your docker configuration. It can't look up the hostname "lavalink" anymore

**Comment by ZandercraftGames** [comment]
It reads my arangodb as being "arango"

**Comment by ZandercraftGames** [comment]
Because this is how I connect to it: `[{"host":"lavalink","port":80,"restPort":2333,"region":"us","password":"password"}]`

**Comment by ZandercraftGames** [comment]
It uses both the websocket port and the server port

**Comment by freyacodes** [comment]
Maybe try recreating your setup?

`docker-compose down` and `docker-compose up -d`

**Comment by ZandercraftGames** [comment]
```
INFO: Fully ready, serving 1160 guild(s).
ERROR: Error: connect ECONNREFUSED 172.18.0.3:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
ERROR: Error: connect ECONNREFUSED 172.18.0.3:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
WARN: LavaLink node ws://lavalink:80 disconnected!
ERROR: ArangoError: database not found
    at new ArangoError (/opt/wildbeast/node_modules/arangojs/lib/async/error.js:71:21)
    at Object.resolve (/opt/wildbeast/node_modules/arangojs/lib/async/connection.js:254:32)
    at _hosts.(anonymous function) (/opt/wildbeast/node_modules/arangojs/lib/async/connection.js:130:26)
    at IncomingMessage.res.on (/opt/wildbeast/node_modules/arangojs/lib/async/util/request.node.js:78:21)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR: Error: connect ECONNREFUSED 172.18.0.3:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
ERROR: Error: connect ECONNREFUSED 172.18.0.3:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
```

**Comment by ZandercraftGames** [comment]
Now its not detecting arango or lavalink.

**Comment by ZandercraftGames** [comment]
Okay... rebuilt databases. Now just not detecting lavalink.

**Comment by ZandercraftGames** [comment]
Its back to this instead of not found.
```
ERROR: Error: connect ECONNREFUSED 172.18.0.3:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
ERROR: Error: connect ECONNREFUSED 172.18.0.3:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
WARN: LavaLink node ws://lavalink:80 disconnected!
```

**Comment by ZandercraftGames** [comment]
Okay... changed it to port 80 and now it can connect... Just not sure if it can control it since it uses both 80 and 2333.

**Comment by ZandercraftGames** [comment]
Yup...
```
INFO: Fully ready, serving 1160 guild(s).
INFO: LavaLink node ws://lavalink:80 ready.
CMD: settings by ZandercraftGamesYT in Zandercraft Hosting
CMD: join-voice by ZandercraftGamesYT in Zandercraft Hosting
CMD: request by ZandercraftGamesYT in Zandercraft Hosting
ERROR: Error: Error: connect ECONNREFUSED 172.18.0.3:2333
    at resolveTracks (/opt/wildbeast/src/encoders/lavalink.js:58:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ZandercraftGames** [comment]
Yep... Changed both to port 80. Now it works. Thanks! 😄

**Comment by MrJacz** [comment]
My emails o my god do not ever send that many comments it isnt discord

**Comment by OtterBoops** [comment]
> or mute the thread

**Comment by ZandercraftGames** [comment]
Sorry @MrJacz xD
