### ISSUE TITLE
events and playerUpdate payloads are not sent after a while

### ISSUE THREAD

**Issue by Earu** [lavalink-devs/Lavalink#203]
Everything is in the title, the discord WS continues to work correctly, voice is transmitted to the connected voice channel but no playerUpdate / event payloads are sent from Lavalink to its clients. Note that payloads sent by clients continue to work.
I've tried reproducing the issue without success, although it seems to happen after a shard disconnects. 

I have seen [this issue](https://github.com/Frederikam/Lavalink/issues/177), regarding your advice on following the shard life cycle, I assume you meant that I should ignore shard disconnected events, which I tried to do, but the issue persisted.

**Comment by freyacodes** [comment]
Please post lavalink logs

**Comment by freyacodes** [comment]
Also define "after a while". Does this affect individual nodes or voice connections?

**Comment by Earu** [comment]
Well it is not a fixed amount of time, sometimes it happens right away, sometimes after a few hours. This affects individual nodes. I attached the logs I have for the past two days.
[logs.zip](https://github.com/Frederikam/Lavalink/files/3306180/logs.zip)

**Comment by freyacodes** [comment]
What happens if you take a player that has stopped emitting events and play a new track for it?

**Comment by Earu** [comment]
It will play the track but will not receive any information related to playerUpdate e.g track position etc.

**Comment by freyacodes** [comment]
I frankly have no idea what could be causing this. I do not recall anyone else having this problem.

Please confirm that:
1. Lavalink is up to date (copy and paste the info that gets shown on Lavalink's startup)
2. The events are not being sent by Lavaalink over the connection. For that you could use wireshark, a modified client, or a debugger. If you need help with this, speak with the maintainer of your client.

**Comment by Earu** [comment]
![putty_2019-06-19_19-25-12](https://user-images.githubusercontent.com/20880060/59786681-154d1b00-92c8-11e9-9c24-5e35c9144bf5.png)

I already tested the client I am using, and I am really not receiving any playerUpdate payload, in fact its the first thing I checked. I hooked to this [event](https://github.com/Yucked/Victoria/blob/v4/LavaBaseClient.cs#L210) and made sure that the `LogSeverity` was set to Debug. No playerUpdate gets logged (after a while), I do log some other things though like operations and stats.

It is also worth mentioning that this happened with the previous versions of Lavalink I used.

**Comment by freyacodes** [comment]
That event appears to be a part of Victoria. It does not tell me if it is Lavalink or Victoria that is misbehaving or even the WS client Victoria is using.

If you are using an unencrypted connection, have you considered using Wireshark to check if anything is coming over the WS/TCP connection?

**Comment by Yucked** [comment]
Hey, it's definitely not Victoria. I've re-read the code several times and though I've never had this problem some users are reporting that those events are never being sent from Lavalink. The SocketHelper class is using ClientWebSocket that are part of .NET FX, none of the information is getting left out and every data received from Lavalink is logged before it's processed. Stats are logged just fine on debug mode but neither TrackUpdate nor rest of the tracks events are received from lavalink after some while like Earu reported.

**Comment by freyacodes** [comment]
I think I have an idea of how I can debug this, without reproducing it myself.

Does the problem persist even if you reconnect Victoria to Lavalink?

**Comment by Earu** [comment]
From my experience, whenever I restart the process, it starts behaving normally again.

**Comment by freyacodes** [comment]
I don't mean restarting the server, I mean reconnecting to it.

**Comment by Earu** [comment]
The problem does not persist when a new WS connection is created. 

> 
> 
> From my experience, whenever I restart the process, it starts behaving normally again.

I meant restarting the process using the Victoria library, which basically re-connects to Lavalink server.

**Comment by freyacodes** [comment]
That makes it more difficult to debug.

What JVM version do you use?

**Comment by Earu** [comment]
```java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
OpenJDK Server VM (build 25.212-b03, mixed mode)
```

**Comment by freyacodes** [comment]
If you want I can try to remotely debug the issue as it is happening to one of your nodes. You can set up a debugging agent that I would be able to connect to. Add this to your JVM args (before or after `-jar`):

`-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005`

**Comment by Earu** [comment]
Sure, although its not happening right now, how can I contact you when that happens?

**Comment by freyacodes** [comment]
You can reach me on the Discord server. See the readme.

`Fre_d#0310`

**Comment by schnapster** [comment]
A small update: This appears to still be an issue. Some people were discussing this on one of the Discord servers today, though unfortunately none of them willing to set up debugging for it as described above. Unless someone experiencing this issue helps debugging it, it is unlikely that this can be resolved.

**Comment by Daniele122898** [comment]
Im running the latest version of lavalink with java 13 and for some reason im not getting any Stat updates. don't rly know why. There's nothing in the console or anything. First thought its an issue with victoria but it seems to be a LL issue?

**Comment by freyacodes** [comment]
@Daniele122898 that doesn't seem related to this issue. Please open a new issue while following the issue template.

**Comment by topi314** [comment]
There hasn't been any activity in a long time and more info is needed so I'm gonna close this.
If the issue persists feel free to reopen the issues
