### ISSUE TITLE
Soundcloud: Error in playback 189559327

### ISSUE THREAD

**Issue by ghost** [lavalink-devs/Lavalink#204]
Im trying to play music thru soundcloud. This particular search does not work tho.

Lavalink version used: 3.2.1
Client used: Eris-Lavalink

Server side Logs: https://pastebin.com/Q2DpHnyx

Client side error logs: ERROR {"op":"event","type":"TrackExceptionEvent","track":"QAAAiAIAF1NoaWdhdHN1IHdhIEtpbWkgbm8gVXNvAAlmYW56ZW4xOTAAAAAAAAGbXQAJMTg5NTU5MzI3AAEAOGh0dHBzOi8vc291bmRjbG91ZC5jb20vZmFuemVuMTkwL3NoaWdhdHN1LXdhLWtpbWktbm8tdXNvAApzb3VuZGNsb3VkAAAAAAAAAAA=","error":"Something broke when playing the track.","guildId":"446603458389475329"}

Song trying to play : shigatsu wa kimi no uso

**Comment by schnapster** [comment]
In the stacktrace you can see that you are receiving an HTTP 401 code from sound cloud. The track you are trying to play is probably private or has some other kind of access control.

**Comment by ghost** [comment]
Maybe limit the search on public songs? Just an idea.

Edit: Its a public track tho
![802AFF2B-A780-4FFE-9485-D35B5C321ED3](https://user-images.githubusercontent.com/34076729/60026696-9fcdba00-96ce-11e9-8985-3614401e0ae2.jpeg)

**Comment by ghost** [comment]
Heya. What’s the status of the fix?

**Comment by schnapster** [comment]
The status of the fix is that it is waiting on someone to use some of their free time and contribute it. Maybe you, since this looks important to you? Also this looks like more of a lavaplayer issue than a lavalink issue, so you should probably open an issue there.

**Comment by ghost** [comment]
Will do. Thanks!
