### ISSUE TITLE
Required library was not found

### ISSUE THREAD

**Issue by MrDandycorn** [lavalink-devs/Lavalink#205]
I get this error when trying to play local files or changing volume on lavalink 3.2.1. I also tried 3.2.0.3 and it works normally but fails to play some youtube videos which work in 3.2.1. Client used is lavalink.py and here are the server logs: https://pastebin.com/W0nHz0V8
Also, I am on Windows 10 Pro 1903 x32 and I tried lavalink on different pc with Windows 10 Pro 1903 x64 and it worked perfectly.

**Comment by freyacodes** [comment]
Lavaplayer (the library that plays music) does not support any 32 bit operating systems.

**Comment by aikaterna** [comment]
You can find a relatively recent Lavalink.jar (build 796) with 32 bit natives on https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.2.0.3_796. I maintain those builds so if you decide to use them please come to me with any errors instead of opening issues on the main repo here.

**Comment by MrDandycorn** [comment]
> Lavaplayer (the library that plays music) does not support any 32 bit operating systems.

Thanks for the response

> You can find a relatively recent Lavalink.jar (build 796) with 32 bit natives on https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.2.0.3_796. I maintain those builds so if you decide to use them please come to me with any errors instead of opening issues on the main repo here.

Thanks a bunch
