### ISSUE TITLE
java.lang.AbstractMethodError on latest dev

### ISSUE THREAD

**Issue by duncte123** [lavalink-devs/Lavalink#215]
## Description
When running the disconnect command on the current development version the following happens https://pastebin.com/fc85vb4x

## Version info
**Client used:** [FredBoat's client with a minor modification to allow regions to be set](https://github.com/DuncteBot/Lavalink-Client/tree/dunctebot-changes)

Output of `java -jar Lavalink.jar --version`:
```
duncte123@duncte123:~/Downloads/lavalink$ java -jar Lavalink.jar --version

Version:        523fca18bbc4d4a7aaeafba06515237fcb8dfb99-SNAPSHOT
Build:          830
Build time:     31.07.2019 11:25:13 UTC
Branch          dev
Commit:         523fca1
Commit time:    31.07.2019 11:22:32 UTC
JVM:            11.0.3
Lavaplayer      1.3.19

duncte123@duncte123:~/Downloads/lavalink$ 

```

Log files:
[error.log](https://github.com/Frederikam/Lavalink/files/3485383/error.log)
[spring.log](https://github.com/Frederikam/Lavalink/files/3485384/spring.log)

**Comment by duncte123** [comment]
This mainly seems to happen if you call stop when there is no track playing

**Comment by schnapster** [comment]
Probably spring versions need to be aligned between LL and Magma.

**Comment by DevYukine** [comment]
Lavalink uses Spring boot version `2.0.4` which uses spring `5.0.8` while Magma uses latest spring `5.1.9`, so Lavalink needs to update to a later (better to the latest) version of spring boot which uses a newer version of spring

**Comment by schnapster** [comment]
Fixed by https://github.com/Frederikam/Lavalink/commit/aa16e6b34d9de05aa303a6cdbea18a7fccacb09f
