### ISSUE TITLE
UDP port for the firewall

### ISSUE THREAD

**Issue by rodseb** [lavalink-devs/Lavalink#218]
## Description
Hello
I have a problem.
I can not find the UDP port for the firewall?

## Version info
**Client used:**

```
        Version:        3.2.1.1
        Build:          828
        Build time:     31.07.2019 11:02:24 CEST
        Branch          master
        Commit:         d9c9aa0
        Commit time:    31.07.2019 10:59:59 CEST
        JVM:            1.8.0_222
        Lavaplayer      1.3.19
```

ERROR 8770 --- [elastic-2] s.n.magma.connections.AudioConnection    : Failed to discover external udp address

**Comment by freyacodes** [comment]
I don't think this has anything to do with your firewall. If you insist, you could try disabling it temporarily to check.

That said, I am not entirely sure how the voice protocol deals with UDP sockets.

**Comment by rodseb** [comment]
Hello
without the firewall it works well

**Comment by freyacodes** [comment]
From what I could gather from Magma's source code, the port is determined by Discord.

Also see https://discordapp.com/developers/docs/topics/voice-connections#establishing-a-voice-udp-connection

**Comment by rodseb** [comment]
Thank you for your reply
I found these ports 50.000 - 65.535

[https://twitter.com/discordapp/status/793626299617120256](https://twitter.com/discordapp/status/793626299617120256)

it's professional precision
