### ISSUE TITLE
 libconnector.so: Operation not permitted in /tmp

### ISSUE THREAD

**Issue by Sasiko** [lavalink-devs/Lavalink#222]
java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /tmp/lava-jni-natives/1568318308672/libconnector.so: /tmp/lava-jni-natives/1568318308672/libconnector.so: failed to map segment from shared object: Operation not permitted

centos 7 on /tmp/
its mounted with tmpfs /tmp tmpfs rw,noexec,nosuid 0 0

and thats to prevent malicious peopl from executing scripts.

Is there anyway to avoid storing files from /tmp folder and let us choose a storage path?

**Comment by MinnDevelopment** [comment]
You can use `-Djava.io.tmpdir=/path/to/dir` I believe

**Comment by schnapster** [comment]
@MinnDevelopment you are correct: https://github.com/sedmelluq/lavaplayer/blob/master/common/src/main/java/com/sedmelluq/lava/common/natives/NativeLibraryLoader.java#L172

This looks solved.
