### ISSUE TITLE
Lavalink doesn't send sound on java 8

### ISSUE THREAD

**Issue by NIXC** [lavalink-devs/Lavalink#231]
## Description
It appears as though the latest Lavalink off master does not work with java 8. I've tried both a self compiled version and the latest off the CI (all logs below are from the CI version). I've personally ran it on a windows 10 64 bit machine and a raspberry pi (with appropriately compiled natives) and experienced no sound with java 8. I've ran the same file on a Debian server with java 11 and it works fine.

I've had a friend test on Windows 7 with java 8 and had it fail, and and another person running Ubuntu 18.04 on the discord said they fixed it by installing java 11.

Sample log me attempting to play music from the windows 10 machine: https://hastebin.com/ekudidowes.coffeescript
Note that I've updated java since then, but it hasn't changed the output. Log hangs like that forever (well past the end of the song). Stats reports the song is at 0 seconds.

I've traced it back through git, it appears as though the first commit that fails is this one: https://github.com/Frederikam/Lavalink/commit/a6f836afe9d946cd6d71d265fe281ef9749c173b
It's highly possible that its something to do with the updated Magma or Jda-nas libraries. 
The commit before that one does not exhibit this issue. I haven't been able to pin it down further than that.

## Version info

Output of `java -jar Lavalink.jar --version`:
```
PS C:\Users\NIN3\Documents\Git\Spyder\cogs\Audio> java -jar .\Lavalink.jar --version

Version:        c314f4db6018a2984c94091aaaf6b72d6652d9e3-SNAPSHOT
Build:          900
Build time:     19.10.2019 20:50:43 UTC
Branch          master
Commit:         c314f4d
Commit time:    19.10.2019 20:47:04 UTC
JVM:            1.8.0_231
Lavaplayer      1.3.22
```

Output of `java -version`:
```
PS C:\Users\NIN3\Documents\Git\Spyder\cogs\Audio> java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

**Comment by iamrunyard** [comment]
Indeed the latest version of Lavalink does not work with Java 8!

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)

**Comment by schnapster** [comment]
One thing I noticed is that magma is being built with Java 11. That's not necessary an issue as the targetted Java version is 8, but there were some trouble with the produced bytecode between 8/11 when it comes to ByteBuffers, which are being used here. While the report does not mention any related exceptions, trying this out might still be worth a shot: https://github.com/napstr/Magma/pull/27

**Comment by NIXC** [comment]
Sorry for the slow response on this: I've tried using both jitpack and manually replacing magma with a version compiled on my java8 machine from that branch. I don't see any change nor improvement sadly.

**Comment by schnapster** [comment]
Thanks for trying this out, @NIXC. I don't have any other ideas or suggestions for this issue at this moment.

**Comment by freyacodes** [comment]
Closing as Java 8 is no longer supported.
