### ISSUE TITLE
Where are Github Dev Releases at?

### ISSUE THREAD

**Issue by kashalls** [lavalink-devs/Lavalink#232]
I noticed on the CI Server that dev releases were being uploaded to github somewhere. Where could I find these?

https://ci.fredboat.com/viewLog.html?buildId=7350&buildTypeId=Lavalink_GithubRelease&tab=buildResultsDiv

**Comment by ghost** [comment]
https://github.com/Frederikam/Lavalink/commits/dev

**Comment by freyacodes** [comment]
That build config affects manually drafted releases on GitHub. It only exists to automate the distribution of the binaries.

There are no prereleases.
