### ISSUE TITLE
Initialization Error in UdpQueueManager on FreeBSD

### ISSUE THREAD

**Issue by panickeraj** [lavalink-devs/Lavalink#233]
## Description
When I try to use Lavalink on my FreeBSD jail it crashes with an exception whenever I try to play music.

Heres the log file from the run.
[spring.log](https://github.com/Frederikam/Lavalink/files/3817833/spring.log)

## Version info
```
Version:        c314f4db6018a2984c94091aaaf6b72d6652d9e3-SNAPSHOT
Build:          Unofficial
Build time:     07.11.2019 04:05:13 UTC
Branch          master
Commit:         c314f4d
Commit time:    19.10.2019 20:47:04 UTC
JVM:            1.8.0_222
Lavaplayer      1.3.22

```

**Comment by freyacodes** [comment]
Unfortunately, we don't support FreeBSD. We rely on 3 upstream libraries that heavily rely on natives.
