### ISSUE TITLE
How this connect to discord without bot access token?

### ISSUE THREAD

**Issue by ItsNerd** [lavalink-devs/Lavalink#246]
Maybe this is a dumb question, but
I looked at the implementations, and did not find the access token passing in the node. How then playback starts if we only have bot id?

**Comment by freyacodes** [comment]
You're not connecting to the usual WS or REST gateway. When your bot wants to "join" a voice channel, Discord sends you some temporary login details (session ID and token) to one of the voice servers in what's called a “voice server update”. Your client must provide these via the `voiceUpdate` op.
