### ISSUE TITLE
 Soundcloud source doesn't work.

### ISSUE THREAD

**Issue by ramazan-bodur** [lavalink-devs/Lavalink#250]
Twitch, YouTube, Vimeo vs. sources work, but Soundcloud doesn't work and gives this error.
```javascript
{ playlistInfo: {},
  exception: {
    severity: 'FAULT',
    message: 'Something went wrong when looking up the track' },
  loadType: 'LOAD_FAILED',
  tracks: [] }
```
How can i solve this?

**Comment by freyacodes** [comment]
Not a Lavalink issue.

Please check your logs and see https://github.com/sedmelluq/lavaplayer
