### ISSUE TITLE
Lavalink frequently fails to connect to discord's voice servers

### ISSUE THREAD

**Issue by Awarets** [lavalink-devs/Lavalink#258]
## Description
Whenever my client joins a discord voice channel, there's a very high chance that lavalink fails to connect to discord's voice servers. The log containing the relevant error message is attached below. I've tested this in every discord server region and the same problem occurs in each one. Only about 1 in every 5 attempts to connect actually succeeds.

## Version info
**Client used:**

Output of `java -jar Lavalink.jar --version`:
```
Version:        4f53d09491ba5254eb5c55c234a63b208388d3ef-SNAPSHOT
Build:          982
Build time:     18.02.2020 01:14:32 UTC
Branch          master
Commit:         4f53d09
Commit time:    28.12.2019 17:00:51 UTC
JVM:            14
Lavaplayer      1.3.32
```

[connectionerror.log](https://github.com/Frederikam/Lavalink/files/4377083/connectionerror.log)

**Comment by freyacodes** [comment]
I believe this might be a TLS issue in Java 14. Try downgrading.

**Comment by Awarets** [comment]
Downgrading to Java 13 seems to have resolved the issue, thanks.
