### ISSUE TITLE
Poor audio quality

### ISSUE THREAD

**Issue by calico-crusade** [lavalink-devs/Lavalink#262]
## Description

Very poor audio quality. Audio is very choppy and horrible sounding bass for everyone on the call.

I'm 99% sure it isn't related to internet connection or computer's power, I've tried the following setups;
* Windows 10, i7-7820X, 32GB Ram - 500mbps down, 40mpbs up. 
* Ubuntu 16.04, i7-8700K, 32GB Ram - 500mbps down, 40 mpbs up.
* Ubuntu 18.04, AWS EC2 T2.medium (4GB Ram, 2CPUs) with T2/T3 scaling enabled 

I get the same poor performance on all of those platforms. Every now and then the audio quality will get better for a short period of time, but then will tank again after a few seconds with no added processes or services. 

What can I do to mitigate this? 

## Version info
Clients used: 
Sharplink v1.0.0-beta-0005 (latest)
Lavalink.py 2.1.10

Output of `java -jar Lavalink.jar --version`:
```
Version:        3.3.1
Build:          997
Build time:     25.03.2020 12:30:43 UTC
Branch          master
Commit:         29f68ba
Commit time:    25.03.2020 12:28:48 UTC
JVM:            13.0.2
Lavaplayer      1.3.38
```

Are the lavalink logs stored someone specific or do you need an extract from journalctl? 

Edit: I have not changed any of the default settings within Lavalink or SharpLink/Lavalink.py as the documentation is sparse or none-existent.

**Comment by freyacodes** [comment]
The setup you have described should have worked fine.

> Very poor audio quality. Audio is very choppy and horrible sounding bass for everyone on the call.

What is your volume set at? A volume over 100% could come off as choppy and destorted. This is revealed in your logs.

> Are the lavalink logs stored someone specific or do you need an extract from journalctl?

Lavalink is not distributed as a Systemd service. Logs are written to `./logs/`. But journalctl works too.

**Comment by Repulser** [comment]
Discord was / is having some issues with voice due to high load, Yesterday all the music bots were lagging so this could be related.

**Comment by calico-crusade** [comment]
Volume is 100% or lower. I have a hard coded restriction on this. I've tried lessening it and increasing it. Audio quality was still a problem. There isn't a logs directory, afaik. This would appear in the working directory/ the same directory as the lavalink.jar, correct? 

I'm running lavalink as a systemd service, working directory is set to the same directory as the lavalink.jar.

If it is as @Repulser says, then there really isn't much to do about it now. I'll see if I can find the log files in the mean time.

**Comment by topi314** [comment]
This issue hasn't been updated in a long time so I'm gonna close it.
If this issue persists feel free to reopen the issue
