### ISSUE TITLE
ERROR 5116 --- [     parallel-3] reactor.core.scheduler.Schedulers        : Scheduler worker in group main failed with an uncaught exception

### ISSUE THREAD

**Issue by ImBoing** [lavalink-devs/Lavalink#278]
When ever I try to play music on my discord bot this happens https://hastebin.com/gedegohafi.cs I am using lavalink version 3.3.1 and java jdk 11. I am on a mac

**Comment by topi314** [comment]
It has been a long time since this issue has been opened.
If this issue persists feel free to reopen the issue
