### ISSUE TITLE
Building from Source?

### ISSUE THREAD

**Issue by stuyy** [lavalink-devs/Lavalink#282]
Trying to see if I can build the Lavalink project from source. Seems like the Launcher.kt is the main file that runs everything? But in IntelliJ it won't allow me to select that as the Main class even though I have Kotlin selected as a template. I have my project set up as a Gradle project.

**Comment by freyacodes** [comment]
Sorry for the late reply.

We use gradle. Run `./gradlew build` (*NIX) or `gradlew.bat build` (Windows) to build. Resulting jar is placed in the new `build` directory.
