### ISSUE TITLE
Some videos not working

### ISSUE THREAD

**Issue by zvshka** [lavalink-devs/Lavalink#283]
## Description
Some urls cant load. If searching by name - 404 else if searching by url - no format

## Version info
**Client used:**

Output of `java -jar Lavalink.jar --version`:
```
Version:        4f53d09491ba5254eb5c55c234a63b208388d3ef-SNAPSHOT
Build:          982
Build time:     18.02.2020 01:14:32 UTC
Branch          master
Commit:         4f53d09
Commit time:    28.12.2019 17:00:51 UTC
JVM:            11.0.7
Lavaplayer      1.3.32
```
Right now i cant extract logs from Docker

**Comment by zvshka** [comment]
https://hasteb.in/mimepixi.log - logs

**Comment by freyacodes** [comment]
Try the dev branch. Need to merge that soon.

**Comment by zvshka** [comment]
Thx its worked!
