### ISSUE TITLE
No track from some URLs

### ISSUE THREAD

**Issue by TacticalTechJay** [lavalink-devs/Lavalink#285]
## Description

Whenever loading tracks with URL sometimes it would not work out and give no results.
The URL I tried is this: https://www.youtube.com/watch?v=-n6O5YH_gXE 
which gave no results. 

## Version info
**Client used:**

Output of `java -jar Lavalink.jar --version`:
```
Version:        3.3.1
Build:          997
Build time:     25.03.2020 12:30:43 UTC
Branch          master
Commit:         29f68ba
Commit time:    25.03.2020 12:28:48 UTC
JVM:            11.0.7
Lavaplayer      1.3.38
```

Logs:
2020-05-04 22:20:06.884  INFO 1 --- [ XNIO-1 task-29] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
2020-05-04 22:20:06.896  INFO 1 --- [der-2-thread-21] lavalink.server.player.AudioLoader       : No matches found

**Comment by freyacodes** [comment]
Try the dev branch. It has a newer Lavaplayer version.
