### ISSUE TITLE
Error occured while starting to play song

### ISSUE THREAD

**Issue by Bennienator** [lavalink-devs/Lavalink#286]
Hey guys,
i'm trying to setup lavalink on my raspberry pi 3, but i cant get it to work.
On my windows PC it's no problem.

[errRaspi.log](https://github.com/Frederikam/Lavalink/files/4592744/errRaspi.log)

**Comment by freyacodes** [comment]
Raspberry pi (or ARM systems in general) is not officially supported. We rely on dependencies that do not support ARM.

See #279

**Comment by Bennienator** [comment]
Thanks for the fast reply,
sorry that was my fault. Didn't searched issues correctly.

Best regards
