### ISSUE TITLE
Question regarding the docker image

### ISSUE THREAD

**Issue by EvilSakray** [lavalink-devs/Lavalink#288]
## Description
Hello,

First thanks for you work :)
I'm having an issue with the docker image, while it installs and run just fine I can't seem to connect to the server (see logs below)
This happens when the application.yml file isn't present (and it isn't by default) 

I'm just unsure about if it's an intended behaviour (having to build your own docker image from yours including the file or adding it using a volume) =>  Issue #74 seem to tend in that direction but being kinda old I wanted to reconfirm. 

Or is there any other way to specify the settings that missed?
I'm pretty new to containers so just trying to ask the right questions.

## Version info
Latest (:master)

Output of `java -version`:
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment Zulu13.29+9-CA (build 13.0.2+6-MTS)
OpenJDK 64-Bit Server VM Zulu13.29+9-CA (build 13.0.2+6-MTS, mixed mode, sharing)

    2020-05-09 12:51:44.303 INFO 1 --- [ XNIO-1 task-3] l.server.io.HandshakeInterceptorImpl : Incoming connection from /xx.xx.xx.xx:65274
    2020-05-09 12:51:44.304 ERROR 1 --- [ XNIO-1 task-3] o.s.w.s.s.s.DefaultHandshakeHandler : Handshake failed due to invalid Upgrade header: null

Thanks for your reply.

**Comment by freyacodes** [comment]
I don't know what would cause that error

You could try providing your full logs and the server's response

**Comment by EvilSakray** [comment]
Hello,

Sorry for wasting your time I actually managed to missread the logs all day long yesterday... 
The error above was due to when I would browse the url directly to ensure the url itself was opened properly.

I was just getting a regular Authentication failed otherwise, and this is because the lib I'm using didn't handle the case password was null properly. (It would always add the Authorization header and therefore passing an empty string value instead)

**EDIT:** Okay while what I said above is true to establish the initial connection I still end up being stuck once I try sending request to the REST endpoint:

The RequestAuthorizationFilter on Lavalink's end, enforces the presence of an Authorization header so what I mentionned above doesn't work anymore (i.e. sending a null password value by ommiting the Authorization header)
I get 401 if I don't send a header, 403 otherwise since I can't find a way to send "null" through the header. (I don't think you can?)

---

Regarding the other point in my first post what would you suggest to add a configuration file? Build a docker image or add it through volume?

Thanks.

**Comment by freyacodes** [comment]
What I usually do is just have a config file as a volume. Although you could just use environment variables.

To override `lavalink.server.password` I set `LAVALINK_SERVER_PASSWORD`

Any particular reason you are building your own image?

**Comment by EvilSakray** [comment]
I'm not building my own docker image atm, just trying to figure out the best way to add a config file since I can't get the raw docker image to work on its own. (null password issue)

If I were to do, it'd be for that sole purpose but I'll look into mounting the application.yml file first.
