### ISSUE TITLE
Dont get any Stat events

### ISSUE THREAD

**Issue by Daniele122898** [lavalink-devs/Lavalink#289]
## Description
Im running version 3.3.1 of lavalink with java 13 and for some reason im not getting any Stat updates. don't rly know why. There's nothing in the console or anything. First thought its an issue with victoria but it seems to be a LL issue? 

## Version info
**Client used:**
https://github.com/Yucked/Victoria But i saw the creator comment on a similar issue that he has tripple checked the implementation and its apparently not a lib issue since all other events are fine

v3.3.1 of Lavalink
Output of `java -version`:
```
openjdk version "13.0.3" 2020-04-14
OpenJDK Runtime Environment Zulu13.31+11-CA (build 13.0.3+3-MTS)
OpenJDK 64-Bit Server VM Zulu13.31+11-CA (build 13.0.3+3-MTS, mixed mode, sharing)
```
Here are the logs. There's nothing in it that would seem that smth is failing.
http://cdn.argonaut.pw/file/e613800a-ab4e-4854-9ed4-92b3faca459f.log

**Comment by freyacodes** [comment]
The stats task shouldn't be able to silently fail. The thread doesn't have a name, so it is difficult to check if it exists.

Can you log everything that the client receives? I want to be certain that this is not a client issue.

**Comment by Daniele122898** [comment]
Just did some more digging into victoria bcs i grew more suspicious of the lib. 

Turns out it swallows the events and doesnt fire properly. sorry to have wasted your time. ill report it to the lib developer

**Comment by freyacodes** [comment]
:ok_hand:
