### ISSUE TITLE
Can't start Lavalink because of UnsupportedClassVersion Error

### ISSUE THREAD

**Issue by Qzername** [lavalink-devs/Lavalink#291]
## Description

So I tried to start lavalink but I have this error:

Caused by: java.lang.UnsupportedClassVersionError: lavalink/server/info/AppInfo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I installed the newest version of java but It still isn't working. I reinstalled Java but still nothing.

## Version info
**Client used:**

Output of `java -version`:
```
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) Client VM (build 25.251-b08, mixed mode)
```

I can't provide log and version because of error.

**Comment by freyacodes** [comment]
Java 8 is not supported. Update to Java 13.

Duplicate of #249 and #266 

Edit: To clarify, you are not running Lavalink with the correct Java version, as shown by `java -version`. You may have other versions of Java installed though.

**Comment by Qzername** [comment]
I know that, but where is Java 13 JRE? I can't find it.

**Comment by freyacodes** [comment]
That depends on your system. This issue tracker is not the place to seek general help with Java. Try asking in our Discord channel.

https://discord.gg/jtAWrzU
