### ISSUE TITLE
Why you are getting “An illegal reflective access operation has occurred.”

### ISSUE THREAD

**Issue by freyacodes** [lavalink-devs/Lavalink#295]
You may have seen this scary red warning (or something similar) when starting Lavalink:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (file:/home/frey/.gradle/caches/modules-2/files-2.1/org.jboss.xnio/xnio-nio/3.3.8.Final/8dafaf230666e526c53e544ab6a9d6ecfcbab4ee/xnio-nio-3.3.8.Final.jar) to constructor sun.nio.ch.EPollSelectorProvider()
WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This message has been appearing since Java 9. This is due to the new module system in Java 9 which puts currently-unenforced restrictions on reflection. This is a problem with our dependencies that will be resolved at a later time.

This “future release” is not out yet, and this warning is otherwise harmless.

See also: https://www.oracle.com/corporate/features/understanding-java-9-modules.html

**Comment by Elite230** [comment]
Anyway How do i fix this? my bot is not connecting

**Comment by THUNDER1090** [comment]
cant connect

**Comment by THUNDER1090** [comment]
reply when









...

**Comment by THUNDER1090** [comment]
guys is your lavalink working?? if no react with  thumbsdown

**Comment by THUNDER1090** [comment]
bruh help me

**Comment by THUNDER1090** [comment]
bruh

**Comment by THUNDER1090** [comment]
![image](https://user-images.githubusercontent.com/88153370/143478598-a4901ca0-395b-4ace-a01a-ca5b5e97c8f3.png)
 this is error and idk passwords "" IS GETTING REMOVED

**Comment by THUNDER1090** [comment]
WHO IS THIS MAD GUY

**Comment by THUNDER1090** [comment]
BRO BAD SUPPORT 
PEEPS JSUT REACT
