### ISSUE TITLE
OnTrackFinished Event does not seem to work!

### ISSUE THREAD

**Issue by t4zzlerdeveloper** [lavalink-devs/Lavalink#296]
## Description
OnTrackFinished Event does not seem to work! If I change back to 3.3 Lavalink Version it seems to work but I have other problem: "Something broke when playing the track", so I do not know what I can do to fix this?! Is it the Victoria Library that needs to be updated?(If I update victoria some features stop working...)

## Version info
**Client used:** Victoria 1.0.2, Lavalink 3.3.1

**Comment by freyacodes** [comment]
It's called `TrackEndEvent`.

Please confirm with the client devs if this is a Lavalink problem or not. If so, post your logs.

**Comment by t4zzlerdeveloper** [comment]
Ok, I forgot to mention that Lavalink doesnt output any error!!! I think it is a Victoria Library issue...

**Comment by t4zzlerdeveloper** [comment]
**Victoria Library version is actually on 4.0.17 and Discord.net is on 2.1.1, Im going to try to mess arround with versions and try to get this fixed!

**Comment by freyacodes** [comment]
Are you sure it is not this issue?

https://github.com/Yucked/Victoria/issues/67

Edit: You're on `4.0.17`. This is fixed in Victoria `4.0.18`. Closing.

**Comment by t4zzlerdeveloper** [comment]
Thank you so much and sorry for wasting your time unnecessarily!
