### ISSUE TITLE
Decoding multiple tracks

### ISSUE THREAD

**Issue by ducc** [lavalink-devs/Lavalink#3]
Using the `/loadtracks` endpoint returns lavaplayer encoded tracks that are almost always decoded immedietly after using the `/decodetrack` endpoint to get track info. When used with a playlist of hundreds of songs or a search result this can lead to hundreds of calls to the decode endpoint.

#### Solution 1: Providing track info with each track in the `/loadtracks` endpoint.
```
GET /loadtracks?identifier=dQw4w9WgXcQ&info=true
{
  "tracks": [
    {
      "track": "AAAA==",
      "info": {
        "title": "48 hours of screaming",
        ...
      }
    }
  ]
}
```
Advantage: No additional requests have to be made to load tracks and view track info.

Disadvantage: Modifies the existing response format which could make existing clients incompatible with the endpoint.

#### Solution 2: Decoding multiple tracks in the `/decodetrack` endpoint.
```
GET /decodetrack?tracks=AAAA==,BBBB==,CCCC==,...
[
  {
    "track": "AAAA==",
    "info": {
      "title": "48 hours of screaming",
      ...
    }
  },
  ...
]
```
Advantage: The endpoint was added yesterday so it is unlikely that changing the response format would lead to incompatible clients.

Disadvantages:
- One additional request has to be made to decode tracks whereas with solution 1 it is not required.
- URLs have a length limit (iirc) so decoding hundreds of tracks will not be possible.

**Comment by freyacodes** [comment]
I suggest you should be using POST requests to decode tracks in bulk
