### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by KagChi** [lavalink-devs/Lavalink#300]
## Version info
**Client used:**  3.3.1

Output of `logs`:
```
c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of SX_ViT4Ra7k
2020-05-29T01:10:23.262616+00:00 app[web.1]: 
2020-05-29T01:10:23.262617+00:00 app[web.1]: com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
```

How do i download the dev version?

**Comment by OtterBoops** [comment]
According to the Readme, they should be available in the CI.

https://ci.fredboat.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Lavalink_Build&tab=artifacts&guest=1

**Comment by KagChi** [comment]
> According to the Readme, they should be available in the CI.
> 
> https://ci.fredboat.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Lavalink_Build&tab=artifacts&guest=1

I need dev build from github so i can host via heroku
