### ISSUE TITLE
Something Broke when playing the track

### ISSUE THREAD

**Issue by raghavken** [lavalink-devs/Lavalink#303]
## Description

Many songs dont play and return this error

## Version info
**Client used:** 
Erela Client
Output of `java -version`:
```
openjdk 13.0.3 2020-04-14
OpenJDK Runtime Environment (build 13.0.3+3-Ubuntu-1ubuntu2)
OpenJDK 64-Bit Server VM (build 13.0.3+3-Ubuntu-1ubuntu2, mixed mode, sharing)
```

0|npm  | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
0|npm  | 	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.47.jar!/:na]
0|npm  | 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.47.jar!/:na]
0|npm  | 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.47.jar!/:na]
0|npm  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
0|npm  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
0|npm  | 	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
0|npm  | Caused by: java.lang.NullPointerException: null
0|npm  | 	at java.base/java.net.URI$Parser.parse(URI.java:3127) ~[na:na]
0|npm  | 	at java.base/java.net.URI.<init>(URI.java:623) ~[na:na]
0|npm  | 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeTrackFormat.getUrl(YoutubeTrackFormat.java:66) ~[lavaplayer-1.3.47.jar!/:na]
0|npm  | 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:97) ~[lavaplayer-1.3.47.jar!/:na]
0|npm  | 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.47.jar!/:na]
0|npm  | 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.47.jar!/:na]
0|npm  | 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.47.jar!/:na]
0|npm  | 	... 4 common frames omitted
0|npm  | 2020-05-29 14:18:57.162  INFO 143781 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"713429951046483999"}

**Comment by Fabricio20** [comment]
This issue has been fixed on the latest `master` branch (released today) and has been fixed for a while already on the `dev` branch. Please update your LavaLink server.

**Comment by ta1H3n** [comment]
Is it possible to get a new release build? I currently don't have the means of building the project myself

**Comment by freyacodes** [comment]
It's automated

https://ci.fredboat.com/repository/download/Lavalink_Build/8110:id/Lavalink.jar?guest=1

**Comment by raghavken** [comment]
ah ok

**Comment by hansputera** [comment]
> It's automated
> 
> https://ci.fredboat.com/repository/download/Lavalink_Build/8110:id/Lavalink.jar?guest=1

how to download this file?
