### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: No available websocket connection for selected node.

### ISSUE THREAD

**Issue by KagChi** [lavalink-devs/Lavalink#305]
## Version info
**Client used:** 

Output of `java -version`:
```
13
```

If i left bot for 30 mins then i wanna play the music my log show this
UnhandledPromiseRejectionWarning: Error: No available websocket connection for selected node.

**Comment by freyacodes** [comment]
This looks like a client issue. Please speak to the developers of your client.
