### ISSUE TITLE
Audio Quality has deteriorated drastically!

### ISSUE THREAD

**Issue by Mr-TylerMorgan** [lavalink-devs/Lavalink#308]
_Hello @Frederikam !
I have invited a discord bot in a discord server... I regularly use that bot for listening to music...but, today the audio was quite off... I have checked with bot's creator and he  told that its the issue on Lavalink's front... Hope you to fix it ASAP!

Thanking You!
Tyler! :)_

**Comment by OtterBoops** [comment]
The information you provided does not explain anything. Check the the issue template and add more information.

**Comment by freyacodes** [comment]
I have not received bug reports about bad audio quality.

If the bot developer has a problem, he can report it himself. I can't help you with someone else's problem, nor do I hold the responsibility.
