### ISSUE TITLE
Base64 encoding is unreliable

### ISSUE THREAD

**Issue by realmayus** [lavalink-devs/Lavalink#309]
## Description

I tried to encode this song to a base64 string using Wavelink (was told to report it here):
https://www.youtube.com/watch?v=_2zwBWLkZHM

After encoding that, I am writing the base64 string to a database. When the user requests the song from the database, the base64 string can't get decoded. 

The base64 string that wavelink/lavalink gives me is this:
```
QAAAhwIAIUNoaWxsIGJ5IEpvYWtpbSBLYXJ1ZCBbWm9uZWQgT3V0XQAMSm9ha2ltIEthcnVkAAAAAAAC+bgAC18yendCV0xrWkhNAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9XzJ6d0JXTGtaSE0AB3lvdXR1YmUAAAAAAAAAAA==
```
## Version info
**Client used:** 
Wavelink

Lavalink:
        Version:        b16ba2f169212982a2124423a9f2cb236b22f624-SNAPSHOT
        Build:          1050

Output of `java -version`:
```
java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

The log just shows this:
```
[ XNIO-1 task-14] l.server.player.AudioLoaderRestHandler   : GET /decodetrack
```

**Comment by realmayus** [comment]
Other users are reporting issues when encoding a video with strange characters in the title, for example this video: https://www.youtube.com/watch?v=2yWWFLI5kFU

but my video doesn't even include any strange characters.

**Comment by freyacodes** [comment]
What do you mean by encoding something with Wavelink?

The data is not meant to be read or written by the client.

**Comment by realmayus** [comment]
Wavelink's `Track` object has a property called `.id`([docs](https://wavelink.readthedocs.io/en/latest/wavelink.html#wavelink.player.Track.id)) which gives me the track data. 
To decode it, I use wavelink's `wavelink.build_track` ([docs](https://wavelink.readthedocs.io/en/latest/wavelink.html#wavelink.client.Client.build_track))

**Comment by realmayus** [comment]
What's strange is that it works for most videos but some fail.

**Comment by freyacodes** [comment]
> the base64 string can't get decoded.

I am not sure what you are trying to accomplish. Please elaborate on what you are expecting, and what is actually happening.

Edit: And please upload your log file

**Comment by Drapersniper** [comment]
Are you by any chance just running the url though a base64 encoder? if thats the case that will not work.

~~Wavelink and lavalink.py both dont have endpoints to encode. (neither does the lavalink jar)~~ Should have been more explicity here as I meant it doesn't simply just encode, and return just the encoded string from the input URL, without any extra work.
i.e serving as just a simple base64 of the url.

**Comment by freyacodes** [comment]
> (neither does the lavalink jar)

It does though. That's the `/loadtracks` endpoint

**Comment by ghost** [comment]
He is probably talking about the `/decodetrack` endpoint. Some B64 (returned by lavaplayer & lavalink from `/loadtracks`) returns an Internal Server Error.

Here's an example
B64: `QAAAmwIAOOGam+GaiOGakeGai+GagOGahOGaieGakeGaiOGaiOGanCBhbmQg4Zqb4ZqR4ZqM4ZqQ4ZqL4ZqcAAlUb20gU2NvdHQAAAAAAAOKQAALMnlXV0ZMSTVrRlUAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj0yeVdXRkxJNWtGVQAHeW91dHViZQAAAAAAAAAA`
Video URL: `https://www.youtube.com/watch?v=2yWWFLI5kFU`

**Comment by realmayus** [comment]
> I am not sure what you are trying to accomplish. Please elaborate on what you are expecting, and what is actually happening.

I have a feature in my bot that allows the user to create personal playlists which are stored in my Database.
When the user adds a song to their personal playlist, my bot adds the base64 string to the database. When the user loads their personal playlist, my bot pulls all the playlist data from my database (which then is just an array of base64 data) and puts it in the queue and plays it.
I am expecting that every base64 string gets decoded properly and doesn't raise an exception.
What happens is that I wavelink raises `BuildTrackError`s.

> Are you by any chance just running the url though a base64 encoder? if thats the case that will not work.

nope, as I said, I use wavelink's .id property to get the data.

Log: https://hastebin.com/zuzifehide.rb

**Comment by freyacodes** [comment]
It works on my machine:tm:
```bash
curl --request GET \
  --url 'http://localhost:2333/decodetrack?track=QAAAhwIAIUNoaWxsIGJ5IEpvYWtpbSBLYXJ1ZCBbWm9uZWQgT3V0XQAMSm9ha2ltIEthcnVkAAAAAAAC%2BbgAC18yendCV0xrWkhNAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9XzJ6d0JXTGtaSE0AB3lvdXR1YmUAAAAAAAAAAA%3D%3D' \
  --header 'authorization: youshallnotpass'
```
```json
{
  "identifier": "_2zwBWLkZHM",
  "isSeekable": true,
  "author": "Joakim Karud",
  "length": 195000,
  "isStream": false,
  "position": 0,
  "title": "Chill by Joakim Karud [Zoned Out]",
  "uri": "https://www.youtube.com/watch?v=_2zwBWLkZHM"
}
```

Also Naegin's B64:
```json
{
  "identifier": "2yWWFLI5kFU",
  "isSeekable": true,
  "author": "Tom Scott",
  "length": 232000,
  "isStream": false,
  "position": 0,
  "title": "᚛ᚈᚑᚋ ᚄᚉᚑᚈᚈ᚜ and ᚛ᚑᚌᚐᚋ᚜",
  "uri": "https://www.youtube.com/watch?v=2yWWFLI5kFU"
}
```

I'm disappointed that you didn't use Tom Scott's video about YouTube and base64
https://www.youtube.com/watch?v=gocwRvLhDf8

**Comment by realmayus** [comment]
Okay, it turns out that it was a bug in Wavelink, not in Lavalink.
Thanks a bunch for helping debugging the issue!
https://github.com/PythonistaGuild/Wavelink/pull/57 fixed the issue.
