### ISSUE TITLE
No match for GET  /loadtracks

### ISSUE THREAD

**Issue by ThatAnonyG** [lavalink-devs/Lavalink#313]
## Description
Very often track search fails to find a match for the given input. I have to try like 5 times to get a match. Exception is when I provide an ID or link but otherwise it is very common and annoying.

## Version info
**Client used:** LavaJS - Latest (My own library)
**LavaLink:** a47a7a46c291390d82bb405abc8c2035de4f28e4-SNAPSHOT (Build: 1064)
**Lava Player:** 1.3.49
 
Output of `java -version`:
```
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
```

**Comment by duncte123** [comment]
Track search is being fixed https://github.com/sedmelluq/lavaplayer/pull/492

**Comment by ThatAnonyG** [comment]
Ohh! Ok thanks for the quick reply. I shall wait for them to fix it then.

> I don't know how but I read it "has been fixed". xD

**Comment by freyacodes** [comment]
The fix is already included in the latest dev build of Lavalink

**Comment by ThatAnonyG** [comment]
@Frederikam Can you possibly provide the link to that? (Only if it's available publicly) Thanks in advance.

**Comment by freyacodes** [comment]
It's on the CI. Here's the direct link for this particular build
https://ci.fredboat.com/repository/download/Lavalink_Build/8162:id/Lavalink.jar?guest=1

**Comment by ThatAnonyG** [comment]
Oh thanks! The issue was quite annoying. 😂
