### ISSUE TITLE
Invalid satus status code for video page response: 429

### ISSUE THREAD

**Issue by pablo1v** [lavalink-devs/Lavalink#317]
## Description

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.

Screenshot: https://i.imgur.com/ABxZep0.png

## Version info
**Client used:** 

Output of `java -version`:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
```

**Comment by duncte123** [comment]
You got banned from YouTube for making too many requests. If you stop sending requests from that ip-adress you will be unbanned

**Comment by Voxay** [comment]
Why be banned?. The first time I used the lavaliere, I got the same error.

**Comment by OtterBoops** [comment]
https://stackoverflow.com/questions/40756171/youtube-reports-api-httperror-429-freequotagroupclient-project-100

It's not an issue on LavaLink's side. It just returns the response it gets. Revise your code.

**Comment by pablo1v** [comment]
Could you have a better solution for now....
Or does lavalink itself support a youtube key setting?

**Comment by alhassanv** [comment]
Same issue here.

**Comment by pablo1v** [comment]
We need to discuss this.

**Comment by txj-xyz** [comment]
I'm now getting the same thing, issue is resolvable by getting a new IP address or waiting 5 days for the IP to be unbanned

**Comment by freyacodes** [comment]
Working around this issue is complicated and relies heavily on network configuration. Lavalink isn't broken, but it offers solutions.

Here are some pointers:
https://github.com/Frederikam/Lavalink/blob/master/ROUTEPLANNERS.md
https://ramblings.fred.moe/2020/3/tunnelbroker-with-lavalink

Please use Discord for discussion.
