### ISSUE TITLE
loadtracks doesn't find any matches when searching for tracks

### ISSUE THREAD

**Issue by tomrsae** [lavalink-devs/Lavalink#320]
## Description
I'm making a Discord bot with the latest version of the Victoria library, which interfaces Lavalink in C#.
I've contacted the author of Victoria, and we concluded that this is an issue with Lavalink, not the library or my program.
Their words were: "Victoria can't fill your result array if Lavalink doesn't return any matches" (My logs confirms that Lavalink doesn't find any matches).

My program attempts to call `Victoria::LavaNode::SearchAsync(string)`, which "performs a search on all enabled sources in configuration [application.yml]".
I have straight copy/pasted the application.yml file from this repository, so I can't see how there would be a problem there.

I am also using simple queries such as "test", "random", "video", "song", etc. This doesn't return anything. Copy/pasting a video title and searching with that doesn't return anything, either.
_However_, it does work when I provide a direct link (e.g. https://www.youtube.com/watch?v=wuYMQJmacGQ).

I thought maybe it could be a Java bug on my system or something of the sort, so I uploaded my bot and Lavalink to the production server, but the error is reproduced.

I have attached my latest log file, where you can see the regular query first (which returns no matches found).
In the second part of the log, you can see the specific link query.

## Version info
**Client used:** Victoria v5.1.6 by Yucked

Output of `java -version`:
I have multiple Java versions installed on my system, but I launch Lavalink as:
`"C:\Program Files\Java\jdk-13.0.2\bin\java.exe" -jar "C:\Lavalink\Lavalink.jar"`
Therefore I'm 100% sure I'm using the following Java executable:
```
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

Output of: `"C:\Program Files\Java\jdk-13.0.2\bin\java.exe" -jar "C:\Lavalink\Lavalink.jar" --version`
I downloaded and tested with the most recent Lavalink version from CI about 30 minutes ago as of writing this. Error still occurs.
```
Version:        e0f335000df475c342ffcad118e62c37d36ad78a-SNAPSHOT
Build:          1069
Build time:     17.06.2020 19:43:02 UTC
Branch          master
Commit:         e0f3350
Commit time:    17.06.2020 19:35:15 UTC
JVM:            13.0.2
Lavaplayer      1.3.50
```

[spring.log](https://github.com/Frederikam/Lavalink/files/4843618/spring.log)

**Comment by nikammerlaan** [comment]
Victoria's naming throws stuff off a little, unfortunately. You have to explicitly mark your input as a search query for Lavalink to treat it as such. This comes in the form of a prefix like `ytsearch:` and `scsearch:`. From what I can see, Victoria provides helper methods for these cases with the `SearchYouTubeAsync` and `SearchSoundCloudAsync` methods.

**Comment by tomrsae** [comment]
@nikammerlaan This worked, I can't believe I didn't at least try them myself.. Thank you very much for pointing this out!
