### ISSUE TITLE
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.

### ISSUE THREAD

**Issue by theADAMJR** [lavalink-devs/Lavalink#321]
## Description
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
No tracks can be found on YouTube.

Breaks with same Lavalink version, on different IPs and operating systems.

## Version
`java --version`

(Ubuntu)
![java-v](https://user-images.githubusercontent.com/28284250/86344478-3d4cb980-bc52-11ea-95d0-2b242e61d566.png)

(Windows)
```
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.2+8, mixed mode, sharing)
```

## Log
(Ubuntu) https://hastebin.com/siruvejuqo.bash
(Windows) https://hastebin.com/soguhisoyo.bash

**Comment by devoxin** [comment]
Update with a build from the CI server. You can find a link in the README.
