### ISSUE TITLE
Using GitHub Releases over CI Server

### ISSUE THREAD

**Issue by ThatAnonyG** [lavalink-devs/Lavalink#330]
## Description
Hey, this is more of a request. Can you guys keep the GitHub releases up-to-date? GitHub releases are lot easier to navigate than the CI Server. It would be amazing if this is possible. Thanks!

**Comment by freyacodes** [comment]
The problem is that drafting releases is ... effort. And I've been a bit stressed as of late.

v3.3.1.1 released.
