### ISSUE TITLE
loadtracks for yt

### ISSUE THREAD

**Issue by hansputera** [lavalink-devs/Lavalink#331]
loadtracks for yt is do not work for me, the result is Not matches found.

anyone?

**Comment by nikammerlaan** [comment]
What input are you giving the endpoint? What version are you running?

**Comment by freyacodes** [comment]
@hansputera please open a new issue with this issue template
https://github.com/Frederikam/Lavalink/issues/new?assignees=&labels=&template=bug_report.md

Also check that you are on the latest version. If you're not, please update.
