### ISSUE TITLE
Feature Request: Audio Filters like FFmpeg Audio Filters.

### ISSUE THREAD

**Issue by ghost** [lavalink-devs/Lavalink#340]
Audio filters like FFmpeg audio filters. Like bass, reverse, vibrato...

**Comment by freyacodes** [comment]
See #264

**Comment by thrace19** [comment]
So it means I can use filters in v3.3.1.1?

**Comment by timoaardappel** [comment]
Will #264 ever be merged though, it's been a couple of months since that commit.

**Comment by freyacodes** [comment]
@inhydrox no

@timozaaijer I'm very busy. Someone else is very welcome to take a look at the filters branch for me.

**Comment by timoaardappel** [comment]
@Frederikam who's authorised to do that then? I'm sure not everyone can do it

**Comment by freyacodes** [comment]
I'm not going to ”authorize” anyone. If someone can prove that the PR works and that it is compliant with the spec, then I can more easily merge.

**Comment by freyacodes** [comment]
Closing as this is now available on the dev branch
