### ISSUE TITLE
Lavalink not closing connections when using LoadBalance with ipv6

### ISSUE THREAD

**Issue by clement-ldr** [lavalink-devs/Lavalink#342]
## Description

It seems that lavalink keeps connections/sockets opened between web requests, this is not really a problem when using ratelimit strategies such as "RotateOnBan" however, when using "LoadBalance" lavalink never close them resulting in thousands of opened sockets stuck in close wait state, using memory.

## Version info
Client used: Wavelink

Output of `java -version`:
```
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
```
(partial) Output of  `lsof +c 0 -Tqs | grep CLOSE_WAIT`
[lsof.txt](https://github.com/Frederikam/Lavalink/files/5081367/lsof.txt)

**Comment by freyacodes** [comment]
This looks like a Lavaplayer problem. Consider opening an issue there
https://github.com/sedmelluq/lavaplayer
