### ISSUE TITLE
Failed to discover external udp address

### ISSUE THREAD

**Issue by raghavken** [lavalink-devs/Lavalink#343]
## Description

My bot randomly stopped playing music, i checked the pm2 logs and found this 0|npm      | 2020-08-17 14:08:33.186 ERROR 18959 --- [      elastic-2] s.n.m.impl.connections.AudioConnection   : Failed to discover external udp address

## Version info
**erela.js** 

Output of `java -version`:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```

0|npm      | ly established from /127.0.0.1:39124
0|npm      | 2020-08-17 14:06:00.101  INFO 18959 --- [  XNIO-1 task-2] lavalink.server.io.SocketServer          : Connection successfully established from /127.0.0.1:39126
0|npm      | 2020-08-17 14:06:24.674  INFO 18959 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"sessionId":"55d8758ea7597fce181fdd92503a351a","op":"voiceUpdate","guildId":"708754192293953579","event":{"token":"ff4f0055795defbe","guild_id":"708754192293953579","endpoint":"us-south7907.discord.media:80"}}
0|npm      | 2020-08-17 14:06:24.876  INFO 18959 --- [  XNIO-1 task-3] l.server.player.AudioLoaderRestHandler   : GET /loadtracks
0|npm      | 2020-08-17 14:06:25.458  INFO 18959 --- [     parallel-1] com.jcabi.manifests.Manifests            : 73 attributes loaded from 84 stream(s) in 524ms, 73 saved, 1240 ignored: ["Ant-Version", "Archiver-Version", "Automatic-Module-Name", "Bnd-LastModified", "Build-Jdk", "Build-Jdk-Spec", "Build-Time", "Built-By", "Bundle-ActivationPolicy", "Bundle-Activator", "Bundle-Category", "Bundle-Description", "Bundle-DocURL", "Bundle-License", "Bundle-ManifestVersion", "Bundle-Name", "Bundle-NativeCode", "Bundle-RequiredExecutionEnvironment", "Bundle-SymbolicName", "Bundle-Vendor", "Bundle-Version", "Copyright", "Created-By", "Export-Package", "Extension-Name", "Git-Revision", "Implementation-Build", "Implementation-Build-Date", "Implementation-Title", "Implementation-URL", "Implementation-Vendor", "Implementation-Vendor-Id", "Implementation-Version", "Import-Package", "Include-Resource", "JCabi-Build", "JCabi-Date", "JCabi-Version", "Jar-Name", "Jar-Version", "Java-Vendor", "Java-Version", "Kotlin-Runtime-Component", "Kotlin-Version", "Log4jReleaseKey", "Log4jReleaseManager", "Log4jReleaseVersion", "Magma-Version", "Main-Class", "Manifest-Version", "Multi-Release", "Originally-Created-By", "Os-Arch", "Os-Name", "Os-Version", "Private-Package", "Provide-Capability", "Require-Bundle", "Require-Capability", "Scm-Connection", "Scm-Revision", "Scm-Url", "Specification-Title", "Specification-Vendor", "Specification-Version", "Spring-Boot-Classes", "Spring-Boot-Lib", "Spring-Boot-Version", "Start-Class", "Tool", "X-Compile-Source-JDK", "X-Compile-Target-JDK", "url"]
0|npm      | 2020-08-17 14:06:28.045  INFO 18959 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded playlist Search results for: gravity falls theme
0|npm      | 2020-08-17 14:06:29.773  INFO 18959 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"play","guildId":"708754192293953579","track":"QAAAhQIAHVtIRF0gR3Jhdml0eSBGYWxscyBUaGVtZSBTb25nAA5HcmF2aXR5RmFsbHNHRgAAAAAAAJxAAAtaNnVzS2h6TDh1SQABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PVo2dXNLaHpMOHVJAAd5b3V0dWJlAAAAAAAAAAA=","volume":100}
0|npm      | 2020-08-17 14:06:54.418  INFO 18959 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"708754192293953579"}
0|npm      | 2020-08-17 14:08:33.186 ERROR 18959 --- [      elastic-2] s.n.m.impl.connections.AudioConnection   : Failed to discover external udp address

Version:        e0f335000df475c342ffcad118e62c37d36ad78a-SNAPSHOT
Build:          1069
Build time:     17.06.2020 19:43:02 UTC
Branch          master
Commit:         e0f3350
Commit time:    17.06.2020 19:35:15 UTC
JVM:            11.0.7
Lavaplayer      1.3.50

**Comment by freyacodes** [comment]
Not a bug, this is a firewall issue. See #218 for hints.

**Comment by raghavken** [comment]
but i never had a firewall in the past it just randomly stopped working
