### ISSUE TITLE
Closed with code 4014 and reason Disconnected

### ISSUE THREAD

**Issue by dakata1337** [lavalink-devs/Lavalink#344]
I am using Java JDK 11.0.6 
`
Java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode)
`

Info about the LavaLink build:
`
 Version:        3.3.1.1
        Build:          1075
        Build time:     13.07.2020 09:09:23 UTC
        Branch          master
        Commit:         f6a1a2a
        Commit time:    13.07.2020 09:04:37 UTC
        JVM:            13.0.2
        Lavaplayer      1.3.50
`

This is the error i am getting in the console
`
2020-08-30 22:46:42.995  INFO 27704 --- [     parallel-4] s.n.m.impl.connections.AudioWebSocket    : Websocket to wss://russia3149.discord.media/?v=4 closed with code 4014 and reason Disconnected.
`
`
2020-08-30 22:46:42.997  INFO 27704 --- [     parallel-4] s.n.m.impl.connections.AudioWebSocket    : Closing
`

What could cause the problem?

**Comment by freyacodes** [comment]
From the Discord documentation:

> 4014: Either the channel was deleted or you were kicked. Should not reconnect.

https://discord.com/developers/docs/topics/opcodes-and-status-codes#voice-voice-close-event-codes

**Comment by dakata1337** [comment]
> From the Discord documentation:
> 
> > 4014: Either the channel was deleted or you were kicked. Should not reconnect.
> 
> https://discord.com/developers/docs/topics/opcodes-and-status-codes#voice-voice-close-event-codes

And how am i supposed to fix it?

**Comment by freyacodes** [comment]
What are you trying to solve? Your bot was forcefully removed from a channel due to some admin action. Lavalink is working as intended.

**Comment by dakata1337** [comment]
When i get this error my bot leaves the VC and i dont want it to..

**Comment by freyacodes** [comment]
Is this something that is happening on your own server, without anyone messing with the channels or permissions?

**Comment by dakata1337** [comment]
I am alone with the bot.

**Comment by freyacodes** [comment]
That might be an indication that Discord is doing something wrong. I don't know why it would trigger a code 4014, but Discord is essentially telling us to not reconnect. So we don't.

You can work around this by attempting to reconnect when Lavalink tells your bot that it has received a code 4014. Seek help from whoever is the maintainer of the client lib you're using. Or ask for help in the Discord channel.

**Comment by TheOriginalDaka** [comment]
I found a fix! The problem isn't from LavaLink.
If you're using Discord.Net 2.2.0 update to the latest pre-release (tested with 2.3.0-dev-20200904.2). Here is a tutorial how https://docs.stillu.cc/guides/getting_started/nightlies.html?tabs=vs.

**Comment by dakata1337** [comment]
I found a fix! The problem isn't from LavaLink.
If you're using Discord.Net 2.2.0 update to the latest pre-release (tested with 2.3.0-dev-20200904.2). Here is a tutorial how https://docs.stillu.cc/guides/getting_started/nightlies.html?tabs=vs.
