### ISSUE TITLE
ERROR 1323 when attempting to use Lavalink

### ISSUE THREAD

**Issue by BladesStaff** [lavalink-devs/Lavalink#345]
## Description
e describ
When using lavalink for a discord music bot, everything worked besides the Lavalink server. It connected perfectly fine but then didn't play anything and gave the error displayed below.

## Version info
**Client used:** 
Lavalink v 3.3.1.1
Output of `java -version`:
```
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
```

Log: https://hasteb.in/qeyejofo.yaml

**Comment by freyacodes** [comment]
Duplicate of #180 

From the readme:

> Support for Darwin (Mac), Windows AMD64, and Linux ARM (Raspberry Pi) is provided on a best-effort basis. This is dependent on Lavaplayer's native libraries.

My advice would be to run Lavalink on a Linux server.
