### ISSUE TITLE
Lavalink always throws an error when loading Youtube tracks

### ISSUE THREAD

**Issue by RRainmaker** [lavalink-devs/Lavalink#350]
Whenever i try to load a youtube track with ytsearch:query, it raises the 'x common frames omitted' error. Loading directly from a url leads to no tracks found. However, using soundcloud search and other urls work perfectly fine.

My current Lavalink library is the Github release, though using the CI server release also causes the error

Java version: 11.0.8

Lavalink version info:
    Version:        3.3.1.1
    Build:          1075
    Build time:     13.07.2020 09:09:23 UTC
    Branch          master
    Commit:         f6a1a2a
    Commit time:    13.07.2020 09:04:37 UTC
    JVM:            11.0.8
    Lavaplayer      1.3.50

**Comment by freyacodes** [comment]
I believe version 3.3.1.2 fixes this.

If not, please reopen this issue and upload your logs. 

> it raises the 'x common frames omitted' error

That's not an error, that's just a way to make stack traces more readable
