### ISSUE TITLE
[Request for new feature] Mixcloud support

### ISSUE THREAD

**Issue by Finoway** [lavalink-devs/Lavalink#352]
Hello, it would be possible to add support for mixcloud please ? 
https://www.mixcloud.com/

**Comment by freyacodes** [comment]
Lavaplayer needs to have it supported https://github.com/sedmelluq/lavaplayer

**Comment by Finoway** [comment]
you are a bot to answer so quickly? x)

**Comment by Finoway** [comment]
Thank you for your answer, have a nice day
