### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by Sekai966** [lavalink-devs/Lavalink#353]
## Description

I feel there is no bass and the overall quality is not that good

is there any thing that i cloud do

## Version info
lastest

**Comment by freyacodes** [comment]
If you listen to YouTube and you have not changed the volume, the vast majority of the video audio tracks are passed through unaltered to Discord.

Other tracks are resampled to opus, but this should only have a minimal effect on quality.

It's always possible that something may have gone wrong. Ultimately I don't know how to help you.

**Comment by topi314** [comment]
with [`v3.5.0`](https://github.com/freyacodes/Lavalink/releases/tag/3.5) lavalink allows setting the `opusEncodingQuality` & `resamplingQuality` which can help with audio quality

If this issue persists feel free to reopen it
