### ISSUE TITLE
youtube playlist issue

### ISSUE THREAD

**Issue by paring-chan** [lavalink-devs/Lavalink#355]
## Description
Track load error on load youtube playlist

## Version info
**Client used:** erela.js

Output of `java -version`:
```
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```

```
Version:        3.3.1.1
Build:          1075
Build time:     13.07.2020 09:09:23 UTC
Branch          master
Commit:         f6a1a2a
Commit time:    13.07.2020 09:04:37 UTC
JVM:            11.0.8
Lavaplayer      1.3.50
```

**Comment by topi314** [comment]
Try updating to the latest commit 
You're like 2 months behind and there was a lavaplayer update 5 days ago

**Comment by thomasgranbohm** [comment]
I also have this problem.
Outputs "Error loading in track:" followed by the requested playlist URL but lowercased, which doesn't link to the playlist.

**Comment by Horstexplorer** [comment]
> I also have this problem, but on the newest release.
> Outputs "Error loading in track:" followed by the requested playlist URL but lowercased, which doesn't link to the playlist.

Quoting the LP FAQ at https://github.com/sedmelluq/lavaplayer/blob/master/FAQ.md#sources-are-registered-but-all-youtube-tracks-trigger-nomatches
Make sure to not convert the string to lowercase as those urls are case sensitive. This issue occurs when u convert the message to lowercase for handling ur commands and then just taking the url out of it.

**Comment by devoxin** [comment]
Closing due to no response. Assuming resolved, if this is not the case then do follow up.
