### ISSUE TITLE
YouTube has stopped working

### ISSUE THREAD

**Issue by ThatOneCalculator** [lavalink-devs/Lavalink#360]
## Description

YouTube has stopped working with Lavalink. My bot just joins and leaves. This only started occuring today after 2 months of Lavalink usage.

## Version info
**Client used:** 
lavalink.py

Output of `java -version`:
```
openjdk version "11.0.8" 2020-07-14 OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04) OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

```
Version: 3.3.1.4
Build: 1109
Build time: 04.10.2020 15:26:50 UTC
Branch Commit: master
Commit: 19972c2
Commit time: 04.10.2020 15:12:22 UTC
JVM: 11.0.8
Lavaplayer 1.3.54.3
```

**Comment by ThatOneCalculator** [comment]
Also, all other audio sources (soundcloud, bandcamp, etc) work perfectly fine. It's ***just*** YouTube.

**Comment by freyacodes** [comment]
Upload your logs please

> Tested on 3.3.1.3 and 3.3.1.4

This is the server version. When we talk about the client, we talk about the library you use to connect to Lavalink.

(gotta run, brb)

**Comment by ThatOneCalculator** [comment]
> Upload your logs please
> 
> > Tested on 3.3.1.3 and 3.3.1.4
> 
> This is the server version. When we talk about the client, we talk about the library you use to connect to Lavalink.
> 
> (gotta run, brb)

Sorry 'bout that! Better?

**Comment by freyacodes** [comment]
Still can't help you without logs

**Comment by ThatOneCalculator** [comment]
> Still can't help you without logs

Does lavalink save logs somewhere?

**Comment by freyacodes** [comment]
Near the working directory

**Comment by ThatOneCalculator** [comment]
Is it `/logs/spring.log`?

**Comment by freyacodes** [comment]
Yes

**Comment by ThatOneCalculator** [comment]
The file is too big for GitHub's comment upload system (81 MB). How would you like me to send it?

**Comment by freyacodes** [comment]
Try only including the lines relevant to your issue

**Comment by ThatOneCalculator** [comment]
Actually, I uploaded it to 0x0.st. Here you go! https://0x0.st/i0Il.log

**Comment by ThatOneCalculator** [comment]
Oh we commented at the same time. I'll redo it!

**Comment by ThatOneCalculator** [comment]
[spring_small.log](https://github.com/Frederikam/Lavalink/files/5343230/spring_small.log)
Here's the small version

**Comment by freyacodes** [comment]
You're very obviously getting ratelimited by YouTube (status 429). Your bot leaving might be something your client is doing.

This is a common but difficult problem. You may ask for help in our Discord channel.

**Comment by ThatOneCalculator** [comment]
Can you send the link to the Discord?

**Comment by freyacodes** [comment]
Check the readme
