### ISSUE TITLE
No voice output after longer periods of inactivity

### ISSUE THREAD

**Issue by jyliuu** [lavalink-devs/Lavalink#364]
## Description
If the bot is left in the VC for a longer period of time, Lavalink will not transmit any audio upon request. 
I'm not sure if this is more of a Discord problem or Lavalink?

Using LL
	Version:        3.3.1.4
	Build:          1111

**Comment by aikaterna** [comment]
Have you checked to see if the Lavalink library you're using supports resuming?

**Comment by topi314** [comment]
this seems to be related to https://github.com/freyacodes/Lavalink/issues/459 and has been fixed in https://github.com/freyacodes/Lavalink/pull/648 and 3.5rc1
