### ISSUE TITLE
(General) Is Lavalink safe from DMCA?

### ISSUE THREAD

**Issue by aroxu** [lavalink-devs/Lavalink#375]
Recently, RIAA Sent DMCA Report, and youtube-dl was took down. And all forked repos deleted together.
So I am wondering that is Lavalink doesn't affected with such as youtube-dl?

**Comment by freyacodes** [comment]
Lavalink (or more precisely lavaplayer) have nothing to do with youtube-dl and our circumstances are very different.

**Comment by aroxu** [comment]
> Lavalink (or more precisely lavaplayer) have nothing to do with youtube-dl and our circumstances are very different.

Oh. Then I think Lavalink is safe to use. Thank you.
+ I'll close this issue after 3 days.

**Comment by brianle1301** [comment]
@Frederikam Can you please explain how it works overall and why it is safe to use lavalink? Thanks

**Comment by HeyBanditoz** [comment]
Is walking down the street safe?
