### ISSUE TITLE
lavalink error using discord.py and java 11

### ISSUE THREAD

**Issue by Nadav2005** [lavalink-devs/Lavalink#377]
## Description

[NODE-na-localhost:7000] Invalid response received; this may indicate that Lavalink is not running, or is running on a port different to the one you passed to `add_node`. error when i run the program

## Version info
**Client used:** 

Output of `java -version`:
```
java version "11.0.9" 2020-10-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)

```

Error: Unable to access jarfile Lavalink.jar

**Comment by devoxin** [comment]
This doesn't appear to be a Lavalink problem. It's pretty self explanatory; you're trying to start Lavalink from a directory it's not situated in.
Edit: Or you haven't downloaded the jar, in which case you'll need to do that.

**Comment by Nadav2005** [comment]
i can fix it?

**Comment by Nadav2005** [comment]
![image](https://user-images.githubusercontent.com/73541263/97316806-d2fbfc80-1872-11eb-8324-de2f11dab8da.png)
this is my folder

**Comment by silverfox0000** [comment]
you used command `cd` to your project? for start the Lavalink

P.S Your lavalink in the DiscordBot-VA not src

**Comment by UnspankableGoose** [comment]
You are mistaken, Lavalink.jar and application.yml are both clearly in the src folder.

**Comment by DMNight6** [comment]
java -jar ./Lavalink.jar
What perimeter did you use to run the lavalink?

**Comment by freyacodes** [comment]
This issue tracker is not for general troubleshooting
