### ISSUE TITLE
Something broke when playing the track

### ISSUE THREAD

**Issue by SoHectic** [lavalink-devs/Lavalink#380]
## Description

When using lavalink.py for my discord bot if I search for a song or use a link, sometimes it will work perfectly and other times it will join the channel then leave right away giving me the error Something broke when playing the track. If using a playlist link it will join and sometimes it will join then leave right away, and other times it will skip a couple of songs that have the error and move onto other songs in the playlist or it will play the songs like normal.

## Version info
**Client used: lavalink.py** 

Output of `java -version`:
```
java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
```
Lavalink Logs - https://pastebin.com/gisXf7Cd

**Comment by L4kyn** [comment]
Same here.

`java -version`:
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
Lavalink log: https://pastebin.com/gBRz1pib

**Comment by freyacodes** [comment]
You both have outdated versions

**Comment by karelkryda** [comment]
I had the same problem, but today I updated Lavalink version to 3.3.2.1...I'll test it...

Btw my Lavaplayer version is 1.3.53. Is it ok?

**Comment by SoHectic** [comment]
Updating has fixed this as far as i can tell
