### ISSUE TITLE
queueEnd event not called if using .stop()

### ISSUE THREAD

**Issue by karelkryda** [lavalink-devs/Lavalink#383]
Hi,
I'm using Lavalink with Node.js. In Node.js I'm using `Erela.js` package.
As stop (clear) command I'm using `player.queue.clear()` and `player.stop()`, but `.on("queueEnd")` event is never called.
Thank you

**Comment by freyacodes** [comment]
Then speak to the Erela.js devs. I can't help you.

**Comment by doente** [comment]
<player>.stop() works as a skip
if you use queue.clear() the music array will be erased and will continue to play.

To resolve this I added the song again (queue 0)
or just before clearing ignoring the array 0

**Comment by karelkryda** [comment]
> .stop() works as a skip
> if you use queue.clear() the music array will be erased and will continue to play.
> 
> To resolve this I added the song again (queue 0)
> or just before clearing ignoring the array 0

Unfortunately, it doesn't work even with the classic song skip `player.stop()`. If the last song in the queue is skipped, the event will not be called.

**Comment by karelkryda** [comment]
Latest test release of Erela.js repair this issiue
