### ISSUE TITLE
Issue with audio playback.

### ISSUE THREAD

**Issue by YVSemlani** [lavalink-devs/Lavalink#385]
## Description

I am running a Lavalink server off of a raspberry pi. The server works for some songs but for other songs it gives me an error. It also is prone to long pauses on any device I run it off of.

## Version info
**Client used:** 
Wavelink.py
Output of `java -version`:
![image](https://user-images.githubusercontent.com/38896123/97786147-a0eee100-1b77-11eb-9424-68f2b779fc7e.png)

**Error**
![image](https://user-images.githubusercontent.com/38896123/97786123-713fd900-1b77-11eb-8600-5359caa922c4.png)

![image](https://user-images.githubusercontent.com/38896123/97786120-5ff6cc80-1b77-11eb-9a51-7770e5cce1f4.png)

**Comment by freyacodes** [comment]
We do not support ARM CPUs. Duplicate of #279
