### ISSUE TITLE
Change port Lavalink runs from

### ISSUE THREAD

**Issue by hburn7** [lavalink-devs/Lavalink#387]
How can I configure Lavalink to run from a port other than 8080? I have a Jenkins pipeline that already uses port 8080. I know there is probably a simple solution but I haven't been able to find anything online to help.

Running from Ubuntu 20.04.1 LTS

Error message:
```
Web server failed to start. Port 8080 was already in use.
Action:
Identify and stop the process that's listening on port 8080 or configure this application to listen on another port.
```

My application.yml also has port 2333 as the configured port.

**Comment by freyacodes** [comment]
Sounds like your config file is not actually being picked up. Somewhat counter-intuitively the default is 8080. Make sure it is in the working directory.

You can also use the SERVER_PORT environment variable.

Closing this as I do not like help requests in the issue tracker.
