### ISSUE TITLE
[Bug] YouTube Mix playlists only return a single track

### ISSUE THREAD

**Issue by devoxin** [lavalink-devs/Lavalink#39]
Links to YouTube Mix playlists only appear to return the video linked to the `watch?v=` parameter rather than the videos from the `list` parameter

Example URL: `https://www.youtube.com/watch?v=v7Srbp8WPMY&list=RDv7Srbp8WPMY`

**Comment by shikhir-arora** [comment]
~~~As far as I'm aware, that is intended behavior. When you copy-paste a video from a playlist, you get a link like that, and most of the times the intended use is to play that single video alone.~~~

~~`https://www.youtube.com/watch?v=v7Srbp8WPMY&list=RDv7Srbp8WPMY`
 should normally parse to `https://www.youtube.com/watch?v=v7Srbp8WPMY`~~

**Comment by freyacodes** [comment]
>As far as I'm aware, that is intended behavior. When you copy-paste a video from a playlist, you get a link like that, and most of the times the intended use is to play that single video alone.

No, it's not intended

@Devoxin what version are you using?

**Comment by devoxin** [comment]
The dev build you linked me in the JDA server

(https://ci.fredboat.com/viewLog.html?buildId=2252&buildTypeId=Lavalink_Build&tab=artifacts)

**Comment by devoxin** [comment]
Update: I don't think this issue is limited to mix playlists. URLs such as `https://www.youtube.com/watch?v=VYz3VIQeET8&list=PL0syuOXMyw6ao11w7sAbQaLK_ARRn-jyS` only return one track, however if you change the URL to `https://www.youtube.com/playlist?list=PL0syuOXMyw6ao11w7sAbQaLK_ARRn-jyS` it returns all of the tracks. RegEx issue?

**Comment by shikhir-arora** [comment]
I assumed it was intended behavior because depending on how it's configured, it can go both ways. I self host FredBoat and dabBot and dabBot will just play the track, while FredBoat does load the playlist. It would be a regex thing up to the creator of the bot at the end of it.

**Comment by devoxin** [comment]
(Just to note this is also reproducible on Lavalink V3, Build 475 (02 Jun 18 12:34))

Lavaplayer itself (on a Java bot) loads all tracks from a mix list

**Comment by devoxin** [comment]
__Update__
There's a small work-around discovered by @Zenrac to load mixes as expected

`https://youtu.be/videoid?list=playlistid` will load all tracks from a mix list, whereas the standard URL (`https://youtube.com/watch?v=videoid&list=playlistid`) will only return a single track.

Tried and tested on Lavalink V3, build 562 - Lavaplayer 1.3.7

**Comment by schnapster** [comment]
Try properly URL encoding the identifier.

**Comment by schnapster** [comment]
Bad call:
```
curl -i -H "Authorization: youshallnotpass" "127.0.0.1:2333/loadtracks?identifier=https://www.youtube.com/watch?v=c5R3lNsNjLs&list=RDc5R3lNsNjLs"
```

Good call:
```
curl -i -H "Authorization: youshallnotpass" "127.0.0.1:2333/loadtracks?identifier=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dc5R3lNsNjLs%26list%3DRDc5R3lNsNjLs"
```

**Comment by devoxin** [comment]
URL encoding appears to have worked. Thanks ^^
