### ISSUE TITLE
lavalink won't send track start event

### ISSUE THREAD

**Issue by AlvaroMS25** [lavalink-devs/Lavalink#399]
## Description
Latest versions of lavalink from ci won't forward track start event through WS, using an "old" version with devoxin-lp (1.3.60) works fine, made the library log every WS payload received, but never received track start one.
 

## Version info
**Client used:** Custom fork of lavalink-rs (https://gitlab.com/nitsuga5124/lavalink-rs/)

Output of `java -version`:
```
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
```

There are no error logs from lavalink server, simply doesn't forward the event

Output of "java -jar Lavalink.jar --version":

←[32m       .  ←[31m _                  _ _       _    ←[32m__ _ _
←[32m      /\\ ←[31m| | __ ___   ____ _| (_)_ __ | | __←[32m\ \ \ \
←[32m     ( ( )←[31m| |/ _` \ \ / / _` | | | '_ \| |/ /←[32m \ \ \ \
←[32m      \\/ ←[31m| | (_| |\ V / (_| | | | | | |   < ←[32m  ) ) ) )
←[32m       '  ←[31m|_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\←[32m / / / /
←[0m    =========================================←[32m/_/_/_/←[0m

        Version:        b97bd00f09ebdea8b1266d1a5971c798677b9a6c-SNAPSHOT
        Build:          1149
        Build time:     19.11.2020 16:38:19 CET
        Branch          HEAD
        Commit:         b97bd00
        Commit time:    19.11.2020 16:34:43 CET
        JVM:            13
        Lavaplayer      1.3.60

**Comment by freyacodes** [comment]
The custom version you're using doesn't emit those events.

https://github.com/Frederikam/Lavalink/blob/b97bd00f09ebdea8b1266d1a5971c798677b9a6c/LavalinkServer/src/main/java/lavalink/server/player/EventEmitter.java

Closing as you're using an unsupported fork.

**Comment by freyacodes** [comment]
I should also add that the fork you're using hasn't seen any of my commits after August 2019, and only works because of a lavaplayer patch. I recommend against using such an old version.
