### ISSUE TITLE
Lavalink + Proxied Behind Cloudflare: Is it possible?

### ISSUE THREAD

**Issue by 2M4U** [lavalink-devs/Lavalink#409]
For people that wish to put their Lavalink behind a domain and still securely protect their server behind cloudflare, 
is it is possible?

As it's possible to pass a Lavalink through Nginx which is essentially the same thing except not changing the "IP" as such, it should still connect to the node.

**Comment by topi314** [comment]
yes it is
just keep in mind lavalink uses websockets too

**Comment by 2M4U** [comment]
> yes it is
> just keep in mind lavalink uses websockets too

Care to explain how to do it securely so I don't leak my servers backend?
Cause I would love to be able to do this :)

**Comment by topi314** [comment]
mind joining the discord for further discussing?(linked in readme)
