### ISSUE TITLE
[Suggestion] [REST] Way to change YouTube Playlist size limit

### ISSUE THREAD

**Issue by devoxin** [lavalink-devs/Lavalink#41]
So it would appear that the current limit is lavaplayer's default (600) tracks. From what I've seen, there's no property to change this.

Perhaps a property that can be changed in `application.yml` to set the maximum amount of tracks loaded from a playlist?

**Comment by freyacodes** [comment]
Wouldn't be difficult to accomplish with the config file. I believe this limit only applies to the youtube source provider
