### ISSUE TITLE
SocketTimoutException on slow (http) sources

### ISSUE THREAD

**Issue by Sekoree** [lavalink-devs/Lavalink#411]
## Description
SocketTimoutException on some specific slow (http) sources, since it takes about 3-5 seconds until that service is able to send data, Lavalink seems to give up on it after a second or so.
Is it possible to change that timeout to a higher number somehow? 
The URL used there works fine when I use FFMPEG (in combination with the regular voice client of the library I use) for example.

## Version info
**Client used:** DSharpPlus.Lavalink (nightly 760)

Output of `java -version`:
```
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
```
[spring.log](https://github.com/Frederikam/Lavalink/files/5648820/spring.log)

**Comment by freyacodes** [comment]
It could be possible with some modification to lavalink

Related: #276

**Comment by Sekoree** [comment]
Would be great to have it as a setting in the config file or just some cmd parameter.

**Comment by DELUUXE** [comment]
Is there any update on this?
Some internet radios take just a few seconds to long to respond and are in turn not playable.
#276 seems to be related (though mentions only YouTube?), but has not been merged?

**Comment by topi314** [comment]
I assume the track failed with a track stuck exception.
WIth [`v3.5.0`](https://github.com/freyacodes/Lavalink/releases/tag/3.5) lavalink allows setting a `trackStuckThresholdMs` which defaults to `10000ms` in the config. This can help with slow sources

If the issue persists feel free to reopen the issue
