### ISSUE TITLE
why no work men

### ISSUE THREAD

**Issue by metaldream64** [lavalink-devs/Lavalink#413]
## Version info
**Client used:** 

Output of `java -version`:
```
(paste here)
```

**Comment by Dramex** [comment]
![image](https://user-images.githubusercontent.com/14023814/102339846-d2e0c900-3fa6-11eb-878e-bb82ad95bb4e.png)

**Comment by topi314** [comment]
![grafik](https://user-images.githubusercontent.com/15636011/102340632-0f0c2d80-3f97-11eb-93a3-b099b278dafe.png)

**Comment by mTvare6** [comment]
![myfigure](https://user-images.githubusercontent.com/57838468/102341679-2f9bae00-3fbe-11eb-9897-d902d3f65b8d.png)

**Comment by kpopdev** [comment]
Trolls everywhere. 
for me everything working good xd
close this ticket please also join JDA discord server if u need help. https://discord.gg/ye5qH5QruV
