### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Required library was not found

### ISSUE THREAD

**Issue by TaromaruYuki** [lavalink-devs/Lavalink#414]
## Description
Changing the volume when song is playing results in:
java.lang.UnsatisfiedLinkError: Required library was not found
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
and the stopping of the music

## Version info
**Client used:**
Lavalink.py

Output of `java -version`:
```
openjdk version "13-BellSoft" 2019-09-17
OpenJDK Runtime Environment (build 13-BellSoft+33)
OpenJDK Server VM (build 13-BellSoft+33, mixed mode)
```

## Logs
https://gist.github.com/Taromaruu/7668d8f5e499dc559b5a00c60e03ba4f

**Comment by freyacodes** [comment]
ARM CPUs are not supported. Duplicate of #279
