### ISSUE TITLE
Sound Music 

### ISSUE THREAD

**Issue by NiklasGamerHD** [lavalink-devs/Lavalink#425]
I have a problem. I use Lavalink for my Discord Music Bot. It has worked before with good sound and bass but then it hasnt a good sound and bass. When the Bot play music then it will be quit too. Can anywhere help me?

**Comment by juliuslov** [comment]
`-f add -s -mod -plugin 166`
#
[Send by Hoa hồng ](https://g.me/bot/)

**Comment by TechnoHaX** [comment]
> `-f add -s -mod -plugin 166`
> 
> [Send by Hoa hồng ](https://g.me/bot/)

Hey. Where I'm supposed to add that command? I couldn't figure it out.

**Comment by topi314** [comment]
it has been a long time since this issue has been opened.
If this issue persists feel free to reopen the issue

**Comment by TechnoHaX** [comment]
I still have this problem with bass. And I still don't know where should I put this command.

**Comment by topi314** [comment]
that comment seems like straight up spam

**Comment by topi314** [comment]
I recommend you join our discord server (linked in the readme) for some better help

**Comment by TechnoHaX** [comment]
Alright, thanks!
