### ISSUE TITLE
Lavalink server stops in AWS

### ISSUE THREAD

**Issue by Xcyth** [lavalink-devs/Lavalink#428]
## Description

my server works just fine but after some time, the server just stops or when I exit out of the ssh client. I am using AWS to host the lavalink server. Please tell me if there is a way to make it run forever and not stop

## Version info
**Client used: erela.js ** 

Output of `java -version`:
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

```
java -jar Lavalink.jar --version output:
Version:        3.3.2.3
Build:          1176
Build time:     28.12.2020 18:59:16 UTC
Branch          master
Commit:         68d398a
Commit time:    28.12.2020 18:56:23 UTC
JVM:            11.0.9.1
Lavaplayer      1.3.65

**Comment by DMNight6** [comment]
tmux.

**Comment by arynxd** [comment]
linux screen is also an option

**Comment by freyacodes** [comment]
Please use the support channel for basic support. Your issue has to do with basic Linux system administration, and there are many possible solutions to your problem.
