### ISSUE TITLE
Authentication failed from { ... }

### ISSUE THREAD

**Issue by TheRedLord69** [lavalink-devs/Lavalink#429]
## Description
When I am trying to initialize the audio service using:
```
audioService = new LavalinkNode(new LavalinkNodeOptions
            {
                RestUri = "http://localhost:8080/",
                WebSocketUri = "ws://localhost:8080/",
                Password = "youshallnotpass"
            }, new DiscordClientWrapper(cicada_client));
await audioService.InitializeAsync();
```
it gives me an error in the discord bot console saying: ```The server returned status code '401' when status code '101' was expected.```
and the console of the server says: ```Authentication failed from /0:0:0:0:0:0:0:1:26325```

From what I know 401 means 'unauthorized' but I dont understand why does it say unauthorized when all the info I provided seems to be right.

## .yml file
server: # REST and WS server
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "youshallnotpass"

## Version info
**I used Lavalink4NET**

Output of `java -version`:
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

## Lavalink version
```5b35fba50da639a0825e5392656d1e6f5d0813f8-SNAPSHOT```

**Comment by freyacodes** [comment]
Your Lavalink is not picking up the config file or it would be running on port 2333

Please use the support channel for basic troubleshooting.

**Comment by TheRedLord69** [comment]
> Your Lavalink is not picking up the config file or it would be running on port 2333
> 
> Please use the support channel for basic troubleshooting.

Where can I find the support channel ?
