### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by aeiousy** [lavalink-devs/Lavalink#430]
Node main got an error: connect ECONNREFUSED 62.171.128.136:2333

i keep getting this error even when i make sure its connected

**Comment by kotx** [comment]
Make sure your firewall isn't blocking the connection. Can you connect to 62.171.128.136:2333 from your browser? You should get an HTTP 401.
Also, you've leaked the ip of your server.

**Comment by freyacodes** [comment]
Not a Lavalink server issue
