### ISSUE TITLE
Est-ce possible de faire jouer de la musique aléatoirement ?

### ISSUE THREAD

**Issue by Ben27YT** [lavalink-devs/Lavalink#440]
Bonjour,

Je souhaite savoir si cela serais possible de faire jouer de la musique aléatoirement ?

**Comment by topi314** [comment]
Yes it's possible
Keeping this english would be helpful

**Comment by Ben27YT** [comment]
Okay no problem for english.
It's possible your explain to me how to do it ?

**Comment by topi314** [comment]
would you mind joining the discord for this?

**Comment by Ben27YT** [comment]
no problem
