### ISSUE TITLE
IP blocked from Youtube?

### ISSUE THREAD

**Issue by cheetahbyte** [lavalink-devs/Lavalink#443]
We had the problem today that the bot did not play anything. We already had the assumption to be blocked by Youtube. When we then packed the Lavalink server on another server, it worked again. Is this normal? Do we have to do this regularly now?

**Comment by topi314** [comment]
https://github.com/Frederikam/Lavalink/issues/369

**Comment by SuupraaaMK4** [comment]
Same here @topi314
