### ISSUE TITLE
YouTube connection Timeout.

### ISSUE THREAD

**Issue by EvieePy** [lavalink-devs/Lavalink#449]
## Description
Connection Timeout when searching or trying to play a song via YouTube.

Ubuntu 20.04.1 LTS x86_64

Using /48 block via HE TunnelBroker.
Able to `ping -6` successfully with an IP in that block.

Everything was working fine for months, and one day it just started doing this. Updated Lavalink to the latest dev build on CI.
Removed and changed Tunnel on TunnelBroker with no success.

## Version info
**Wavelink 0.9.9**

Output of `java -version`:
```
openjdk 13.0.4 2020-07-14
OpenJDK Runtime Environment (build 13.0.4+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 13.0.4+8-Ubuntu-120.04, mixed mode, sharing)

```
**Logs:**
https://mystb.in/EstimationArabicWeight.yaml

**Edit:**
I understand this most likely a Lavaplayer issue but I thought I'd ask here first.

**Comment by freyacodes** [comment]
Are you saying this still doesn't work if you disable the IP balancing in the Lavalink config? The log you showed uses balanced IPs.

Have you tried running something like `curl https://www.youtube.com` ?`

**Comment by EvieePy** [comment]
curl works fine.

What are you suggesting I disable? Sorry.

**Comment by freyacodes** [comment]
> Removed and changed Tunnel on TunnelBroker with no success.

What did you mean by this?

**Comment by EvieePy** [comment]
Oh sorry for the confusion.

I created a new Tunnel on HE to test. The logs you see are using the new Tunnel with a new IP. I am yet to test this without. I can do that now.

**Comment by EvieePy** [comment]
Everything works fine on IPv4, without the Tunnel.

Which is weird because the Tunnel had been working fine for months without any changes.

**Comment by freyacodes** [comment]
Make sure you're running the `ip -6 route replace local YOUR_48_BLOCK dev lo` command. It needs to be run each time your network is reset.

If that doesn't solve your problem, see https://ramblings.fred.moe/2020/3/tunnelbroker-with-lavalink#help-ive-tried-everything

Closing as this issue tracker is not for general troubleshooting.

**Comment by MrBoombastic** [comment]
Came back to topic about year later. I struggled with timeouts, but that command above fixed that. Thanks!
