### ISSUE TITLE
Failing to connect to voice channels

### ISSUE THREAD

**Issue by Thewsomeguy** [lavalink-devs/Lavalink#45]
Sometimes lavalink will fail to connect to voice channels. Not sure if it's an issue with the lavalink server or with eris-lavalink. Sometimes it will also fail to disconnect from the voice channel, and it won't be able to connect again unless the connected client is restarted or the bot is "voice kicked" from the channel.

Link to related issue: https://github.com/briantanner/eris-lavalink/issues/4

**Comment by Repulser** [comment]
Does this just happen randomly? Or is there a specific scenario that causes this?

**Comment by MrJacz** [comment]
I'm pretty sure its eris-lavalink not handling session id's correctly

**Comment by MrJacz** [comment]
@Thewsomeguy Just a question, In the Lavalink console does it keep requesting guild, channel or permission check?

**Comment by DaWolf85** [comment]
This (or a similar) issue just occurred through FredBoat on a server I'm on as well, and FredBoat printed part of a stacktrace for our viewing pleasure:
`java.lang.NullPointerException
    lavalink.client.io.Link.connectNow(Link.java:158)
    lavalink.client.io.Link.connect(Link.java:114)
    fredboat.audio.player.LavalinkManager.openConnection(LavalinkManager.java:77)
    fredboat.audio.player.GuildPlayer.joinChannel(GuildPlayer.java:139)
    fredboat.audio.player.GuildPlayer.joinChannel(GuildPlayer.java:118)
    fredboat.audio.player.GuildPlayer.queue(GuildPlayer.java:170)
    fredboat.command.music.control.PlayCommand.onInvoke(PlayCommand.java:105)
    fredboat.commandmeta.CommandManager.prefixCalled(CommandManager.java:121)
    ...`

I don't have intimate knowledge of the library, but it seems based on my quick and dirty reading that, for this to happen, `currentNode` would have to be null even after the null check and assignment on lines 109/110 of [lavalink.client.io.Link](https://github.com/Frederikam/Lavalink/blob/master/LavalinkClient/src/main/java/lavalink/client/io/Link.java). And that does seem related to requesting guilds, specifically to requesting the ID.

**Comment by Repulser** [comment]
@DaWolf85 this has already been fixed in the development branch, that issue is unrelated.

**Comment by freyacodes** [comment]
@DaWolf85 that issue was fixed. It has nothing to do with this issue though

**Comment by Repulser** [comment]
I believe https://github.com/briantanner/eris-lavalink/pull/11 should fix this issue.

**Comment by MrJacz** [comment]
👍
