### ISSUE TITLE
Error when playing audio

### ISSUE THREAD

**Issue by DaliborTrampota** [lavalink-devs/Lavalink#450]
Hello,

this was emitted by error event on player
```js
{
  op: 'event',
  reason: 'Internal error',
  code: 4000,
  byRemote: false,
  type: 'WebSocketClosedEvent',
   guildId: '327829501532962828'
}
{
  op: 'event',
  reason: 'Abnormal closure',
  code: 1006,
  byRemote: false,
  type: 'WebSocketClosedEvent',
  guildId: '327829501532962828'
}
```

Yesterday it never happened. Today it happened twice already. In the past it happened occasionally but it starts to annoy me as I can't find any info about those two errors. I haven't moved the bot from one vc to another because I know there are issues with it as well. I just played music (radio) this morning and it crashed twice. Once with radio playing second time with classic youtube song (not radio). Any ideas on how to fix this? I do not use any ip rotations or that yet as only few users listen to my bot daily. So I'd rather find a fix for it sooner than later. 

My ram usage is fine as well if it's any related to that: https://cdn.discordapp.com/attachments/418817098278764544/819177388003819555/unknown.png

Any ideas are welcome :) Thank you.

**Comment by freyacodes** [comment]
~~Your websocket connections appear to be closed by whichever client library you're using (`byRemote: false`). You should probably speak with its developers instead.~~

~~If you still believe this is a lavalink problem, post logs.~~

Sorry, I misread. Please still post logs though.

**Comment by DaliborTrampota** [comment]
Oh sorry I forgot to mention. There are no logs whatsoever in lavalink console thats the problem. It just throws this error on the event but in console it just says this: 
```
{"op":"destroy","guildId":"327829501532962828"}
{"sessionId":"2a4b3f0410de50ef0015f9e3e19c274f","event":{"token":"6a1f54dcc023fb11","guild_id":"327829501532962828","endpoint":"eu-central1012.discord.media:443"},"op":"voiceUpdate","guildId":"327829501532962828"}
```

**Comment by DaliborTrampota** [comment]
is there a way to enable debug logs? maybe I don't have them on?

**Comment by freyacodes** [comment]
Run lavalink with `--debug` or add `debug: true` in the config.

**Comment by DaliborTrampota** [comment]
Ok I ran it with --debug as I don't know where exactly in the config file I should specify debug: true, but I'll keep it running and once it crashed I'll let you know. Thank you for the fast support!

**Comment by DaliborTrampota** [comment]
https://sourceb.in/liii78aXxq Here it is, it didn't happen lately that often but it still did.

**Comment by freyacodes** [comment]
That paste service fails to actually load the text.

**Comment by DaliborTrampota** [comment]
hmm weird I see it just fine but here is pastebin https://pastebin.com/R8nqQk9k

hastebin.com doesnt work for me. whenever I want to click save it does nothing the pastebin has narrow container so the text clips to another line and its not looking good and readability is poor so sorry for that

**Comment by freyacodes** [comment]
That's a pretty normal network error. Your client should try to reconnect.

**Comment by DaliborTrampota** [comment]
it probably reconnects but the song doesnt resume and to make it play again i need to stop the player and play another song or the same one

**Comment by freyacodes** [comment]
The track gets cleaned up if audio does not get sent for a while

**Comment by DaliborTrampota** [comment]
Well ill try handle it in my code then thanks :)
