### ISSUE TITLE
I know this Error is "fixxed" but still help appreciated!

### ISSUE THREAD

**Issue by Tomato6966** [lavalink-devs/Lavalink#452]
![image](https://user-images.githubusercontent.com/68145571/111354281-7022ca80-8686-11eb-9de4-965fa440c075.png)

Now the thing is, the exact same application.yml settings and LAVALINK version are working on a different Debian, i created a VM and there it works
I am using 2 IPV6 Blocks, and tried with java 11, 13 and 15 with both i get the same error

now i wanted to try your     `youtubeTimeout: -1`   fix, but i couldn'T find a Build for that could u please link me a build for it? THANKS

**Comment by Tomato6966** [comment]
Please, I just need a build from it...

**Comment by freyacodes** [comment]
This looks like a problem with your IPv6 setup, not youtube being slow

**Comment by Tomato6966** [comment]
No It's not 
![image](https://user-images.githubusercontent.com/68145571/111532352-d92d3f80-8765-11eb-8ff1-9342c4309e0c.png)

I can build a connection up to the Server

i also built your experiented/youtubeTimeout but that didnt help either

**Comment by Tomato6966** [comment]
I fixxed it!

The problem were due to many problems:

First for some reason i had next to debian ubunto installed, so i removed it from etc/

second i continued trying it with java 15, which didnt work so i removed the ip routing, then it worked
so then i tried with different ipv6 address, which then didnt work again

so i checked the routings, for some reason with removing the ubunto the routing resetted so i redid it

then the routing worked for one ipv6 address but not for both

then i swapped to java 11 and everything worked again


to put everything in a nutshell, ubuntu was the reason why i wasnt able to use it thanks!
