### ISSUE TITLE
Got an unexpected error.

### ISSUE THREAD

**Issue by clodlol** [lavalink-devs/Lavalink#458]
Error:-
```
[JDA MainWS-ReadThread] ERROR WebSocketClient - Got an unexpected error. Please redirect following message to the devs:
	VOICE_SERVER_UPDATE -> {"endpoint":"singapore5013.discord.media:443","guild_id":"780393488575234099","token":"c333c12cdd036222"}
```

The bot connects to the voice channel and throws this error. I have my lavalink server up and running and i have double checked the host, password and port.

**Client used:**[Lavalink-Client](https://github.com/Frederikam/Lavalink-Client)

Java version:-
```
java version "16" 2021-03-16
Java(TM) SE Runtime Environment (build 16+36-2231)
Java HotSpot(TM) 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)
```

Lavalink Logs:-
[spring1.log](https://github.com/Frederikam/Lavalink/files/6189135/spring1.log)

Lavalink Version: 3.3.2.3

**Comment by freyacodes** [comment]
You're not even connecting to Lavalink. Your client is misconfigured.

Not sure what the JDA error is about. Is there not a stack trace?

**Comment by clodlol** [comment]
>  Is there not a stack trace?

nope

**Comment by clodlol** [comment]
nevermind, figured it out myself.
