### ISSUE TITLE
Where can I download the dev version? 

### ISSUE THREAD

**Issue by KasaiKonoru** [lavalink-devs/Lavalink#463]
Where can I download the dev version?

**Comment by duncte123** [comment]
A link to the CI where you can download the dev version is over here https://github.com/Frederikam/Lavalink#server-configuration

**Comment by KasaiKonoru** [comment]
thx you, you mean this:
https://ci.fredboat.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Lavalink_Build&tab=artifacts&guest=1

**Comment by topi314** [comment]
as you can see if you click this is a direct link to latest master.

**Comment by KasaiKonoru** [comment]
> as you can see if you click this is a direct link to latest master.

But this is dev version? It looks like lastest official version

**Comment by topi314** [comment]
![grafik](https://user-images.githubusercontent.com/15636011/113263864-9bd2c100-92d2-11eb-870c-8adda79d7c6a.png)

**Comment by KasaiKonoru** [comment]
ok and where is the dev version?

**Comment by KasaiKonoru** [comment]
I have problems with lavalink. I play a track and lavalink skipped this instant.
![Screenshot_20210401_101943](https://user-images.githubusercontent.com/45830738/113265385-99b53600-92c3-11eb-97f1-a159a904d7b4.jpg)
![Screenshot_20210401_102215_mobileSSH feng gao](https://user-images.githubusercontent.com/45830738/113265391-9a4dcc80-92c3-11eb-929a-e0ce0a536c09.jpg)
![Screenshot_20210401_102211_mobileSSH feng gao](https://user-images.githubusercontent.com/45830738/113265395-9ae66300-92c3-11eb-839a-c98cf051ddeb.jpg)

![Screenshot_20210401_102217_mobileSSH feng gao](https://user-images.githubusercontent.com/45830738/113265549-ccf7c500-92c3-11eb-91bd-3f13bdb1e4a8.jpg)

**Comment by topi314** [comment]
stop spamming this issue latestcdev version does not have a fix for this yet
pr is made & we are waiting for fred to merge it

**Comment by KasaiKonoru** [comment]
No its not the dev version its the latest version

and I use Java 13

**Comment by topi314** [comment]
https://ci.fredboat.com/viewLog.html?buildId=8762&buildTypeId=Lavalink_Build&tab=artifacts&branch_Lavalink=refs%2Fheads%2Fdev?guest=1

**Comment by KasaiKonoru** [comment]
> https://ci.fredboat.com/viewLog.html?buildId=8762&buildTypeId=Lavalink_Build&tab=artifacts&branch_Lavalink=refs%2Fheads%2Fdev

**Comment by KasaiKonoru** [comment]
> > https://ci.fredboat.com/viewLog.html?buildId=8762&buildTypeId=Lavalink_Build&tab=artifacts&branch_Lavalink=refs%2Fheads%2Fdev

This is the latest?

**Comment by topi314** [comment]
yes its latest dev??

**Comment by KasaiKonoru** [comment]
Ok sry I clicked on close

**Comment by KasaiKonoru** [comment]
> 
> 
> 

![grafik](https://user-images.githubusercontent.com/45830738/113269969-4cdc5a00-92d9-11eb-8a9f-aac424e1babb.png)
Can you help me pls whats wrong?

**Comment by topi314** [comment]
https://github.com/Frederikam/Lavalink/issues/463#issuecomment-811741538
https://github.com/Frederikam/Lavalink/pull/464

**Comment by KasaiKonoru** [comment]
> 
> 
> [#463 (comment)](https://github.com/Frederikam/Lavalink/issues/463#issuecomment-811741538)
> #464

Ok thx but nothing worked as everything was described

**Comment by freyacodes** [comment]
You're getting that error on an old lavaplayer version.

Update to the latest lavalink (either master or dev)
