### ISSUE TITLE
Something broke when playing the track(Only YouTube)

### ISSUE THREAD

**Issue by chlibekp** [lavalink-devs/Lavalink#467]
## Description
When you want to play YouTube audio, lavalink throws an error, it finds the song on youtube, but when It wants to play it just throws an error and says, that queue is empty.

I tried other java and lavalink versions.

## Version info
**node used:** v14.0.0
**Client used:** erela.js@2.3.2(tried gorilink)

Output of `java -version`:
```
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)
I even tried java 11
```
https://pastebin.com/0LpV9FN8

**Comment by topi314** [comment]
update to latest ll release
should be fixed there

**Comment by emre1702** [comment]
I've tried the newest docker images from master and dev and still got this error.

![image](https://user-images.githubusercontent.com/15148761/113490189-e4ec6600-94c8-11eb-96af-58bb6d64ce2d.png)

**Comment by chlibekp** [comment]
Everything was working, but now its broken again for some reason

**Comment by topi314** [comment]
are you on latest again?

**Comment by chlibekp** [comment]
yes, still not working. Same output as before

**Comment by chlibekp** [comment]
okay, I have found out, that the issue is only on linux. and it's not problem with java I have tried java 11 and 14 on both.

**Comment by chlibekp** [comment]
https://pastebin.com/7SeK12jp I have tried running it in docker and I got this output.

**Comment by chlibekp** [comment]
It somehow started working. Idk how and why :D
