### ISSUE TITLE
Playback can be slow or fast in the beginning, does not play at the right tempo

### ISSUE THREAD

**Issue by aoztanir** [lavalink-devs/Lavalink#486]
## Description

When I play audio using lavalink/discord.py/wavelink the audio is very slow or fast in the beginning and then catches up later. I am running on a Raspberry Pi 3 with an Arm specific build of Lavalink. It is worth noting that I don't think the specific arm CPU or x86 soc is significant as I noticed these issues on an x86 processor too.

## Version info
**Client used:** 
Wavelink

Output of `java -version`:
![image](https://user-images.githubusercontent.com/53831852/118692723-33c33600-b7bf-11eb-8054-6e0aafaeb167.png)

**Comment by topi314** [comment]
Since opening this issue a lot of time has passed.
If this issue persists feel free to reopen this issue
