### ISSUE TITLE
Handle resumes and reconnects correctly

### ISSUE THREAD

**Issue by schnapster** [lavalink-devs/Lavalink#49]
Original issue: https://github.com/Frederikam/FredBoat/issues/403

> Tested this with latest LL and FB code, resumes are not handled optimally.
> The bot always leaves the voicechat, music is paused, unpaused on rejoin.
> Sometimes it does not rejoin, and therefore does not continue the playback.
> 
> Reconnects break it worse: Never rejoins the voicechat, but always keeps playing.

Instead, these events should be handled the same way they are handled when running without LL:
Resumes are, if at all, noticed by a short audio cut out.
On Reconnects the VoiceChannel is left, and upon restoration of the connection, rejoined and the playback continued.

**Comment by freyacodes** [comment]
It is odd that it isn't rejoining, as that as explicitly handled on resume and reconnect by the Lavalink class.

**Comment by Repulser** [comment]
Now that ive had a full resume i can provide more insight, since i have auto reconnect disabled i got the wanted behavior (Small voice cutout), it seems that there isnt a need to reconnect all voice channels on resume?

**Comment by freyacodes** [comment]
@Repulser that is probably because of the fact that JDAA implemented voice resume since. Good to know

**Comment by Repulser** [comment]
This should be fixed in V2
