### ISSUE TITLE
Lavaplayer doesn't play some songs at all

### ISSUE THREAD

**Issue by Sirius227** [lavalink-devs/Lavalink#496]
Lavaplayer does not play some songs at all. This issue occurs on vps server. There is no problem when I run it on my own computer. I am using Discord.NET v2.4.0 & Victoria

vps server system features; 
Intel xeon cpu x5670 @ 2.93GHz
4 GB ram

Lavalink version;

Version: 3.3.2.5
Build: 1222
Build time: 11.04.2021 08:07:27 UTC
branch master
Commit: 7b914f2
Commit time: 09.04.2021 17:14:27 UTC
JVM: 16.0.1
Lavaplayer 1.3.76

For example 
![test - Discord 16 06 2021 15_20_00](https://user-images.githubusercontent.com/76209670/122217912-883cfc80-ceb6-11eb-882c-332eb12f511c.png)

**Comment by topi314** [comment]
please provide the stacktrace from the console
those logs are useless and don#t give any info

**Comment by Sirius227** [comment]
[spring.log.txt](https://github.com/freyacodes/Lavalink/files/6663035/spring.log.txt)

**Comment by freyacodes** [comment]
Your problem is this

> Network is unreachable: no further information

So *something* is wrong with your network. I have never seen this exact message before.

**Comment by topi314** [comment]
are you using ipv6 rotation?

maybe you want to join the discord for further support on that

**Comment by freyacodes** [comment]
> are you using ipv6 rotation?

Logs indicate no

> localAddress: \<unspecified\>

**Comment by Sirius227** [comment]
I don't know much about this kind of problem. What solutions can I implement?
ipv6 address does not appear when i type ipconfig in command window

**Comment by V1rtuaI** [comment]
I have IP rotation and I still get this issue on a regular basis.

**Comment by Bedrock16** [comment]
It maybe be due to some song are ban at your ip
