### ISSUE TITLE
Yt api

### ISSUE THREAD

**Issue by kakarot-dev** [lavalink-devs/Lavalink#497]
I know this sounds unreasonable but is it possible to use a api key to make search requests from lavalink to youtube

**Comment by cloudwithax** [comment]
this sounds like you have an issue with ip banning and frequent 403s, please look into ipv6 routing, as it will prevent you from getting this issue less frequently https://blog.arbjerg.dev/2020/3/tunnelbroker-with-lavalink

**Comment by freyacodes** [comment]
Technically possible but you would be unable to stream audio. The quotas are also very low.

If this is something you want to pursue, I recommend you consume the API directly without Lavalink.

Even if you don't stream audio you could just use Lavalink's search, working around the ratelimits as described above.

**Comment by kakarot-dev** [comment]
yes Thank you so much!!
