### ISSUE TITLE
Tunnelbroker (Network) : Is unreachable

### ISSUE THREAD

**Issue by veerack** [lavalink-devs/Lavalink#498]
Trying to make ip-rotation due too many requests and constant ratelimits by youtube, following https://blog.arbjerg.dev/2020/3/tunnelbroker-with-lavalink, all good until i reach the `ping6 google.com` step, which return `Connection : network is unreachable`

Totally sure i've followed and done right each step before.

**Comment by jadoncodes** [comment]
if you see this I am in the discord as I own the vps this issue is on, so i'd go there if I were you
