### ISSUE TITLE
TeamCity - Never Logs In

### ISSUE THREAD

**Issue by majorcyto** [lavalink-devs/Lavalink#5]
Hi, tried it from two computers and two different networks but Team City never logs in. I was able to get into it fine last time I used it.

No error code, just spins on the login button for eternity.

**Comment by freyacodes** [comment]
Oh dear. Somehow the server got left hanging. It fails to restart. Looking into this now.

**Comment by majorcyto** [comment]
Works now \o/

**Comment by freyacodes** [comment]
The issue was that the DB had died due to TeamCity artifacts taking up too much disk space. For some reason, PRs are triggering hundreds of builds. Need to investigate why TeamCity is doing that

**Comment by Shredder121** [comment]
Maybe some rebases are triggering builds for *every* commit in between the source, and the target, regardless of changes or not?
(it's not reachable anymore, btw 😩)
