### ISSUE TITLE
soundcloud not working with lavaplayer < 1.3.77

### ISSUE THREAD

**Issue by AlexandreBazeaud** [lavalink-devs/Lavalink#501]
## Description

Soundcloud return a 401 error whenever i try to play one, problem is a known one and lavaplayer's developper already fixed it.
see [here](https://github.com/sedmelluq/lavaplayer/issues/636)

Would be cool to have the next lavalink version to use this. thanks in advance.

**Comment by topi314** [comment]
https://github.com/freyacodes/Lavalink/pull/499
