### ISSUE TITLE
How to host lavalink in for public 

### ISSUE THREAD

**Issue by appujet** [lavalink-devs/Lavalink#503]
I have hosting but my friend don't have hosting so I went to give lavalink and password How to do this?

**Comment by topi314** [comment]
https://github.com/freyacodes/Lavalink/blob/2ac6bf4e0dcab9ba7493b0494316b8bee698913d/LavalinkServer/application.yml.example#L6

address needs to be 0.0.0.0
And make sure your firewall is configured correctly to let port 2333 be open

**Comment by appujet** [comment]
But my friend is hosting in replit 
And my lavalink server in my pc

**Comment by growtoups** [comment]
u need to open one of your ports (from your router panel)

**Comment by appujet** [comment]
I am using AWS e2c than how to do
