### ISSUE TITLE
Filters isn't working

### ISSUE THREAD

**Issue by zRickz** [lavalink-devs/Lavalink#505]
I'm trying to speed the audio and it returns that the filter operation doesn't exist...

lavalink.py

```
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

```

2021-07-21 03:11:16.983  INFO 13364 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : {"op": "filters", "guildId": "805333944442028033"}
2021-07-21 03:11:16.984  WARN 13364 --- [   XNIO-1 I/O-1] lavalink.server.io.SocketServer          : Unexpected operation: filters

Lavalink Version:

Version:        2ac6bf4e0dcab9ba7493b0494316b8bee698913d-SNAPSHOT
Build:          1232
Build time:     20.04.2021 07:05:21 UTC
Branch          master
Commit:         2ac6bf4
Commit time:    20.04.2021 07:02:46 UTC
JVM:            16
Lavaplayer      1.3.76

**Comment by ColdtQ** [comment]
You have to use the latest development build from the CI server. Check it here - https://ci.fredboat.com/viewLog.html?buildId=8871&buildTypeId=Lavalink_Build&tab=artifacts

**Comment by ColdtQ** [comment]
Please close this ^

**Comment by zRickz** [comment]
Thanks!

**Comment by Franetse7** [comment]
ok thanks
