### ISSUE TITLE
Doesn't play any Tracks

### ISSUE THREAD

**Issue by TruSoggy** [lavalink-devs/Lavalink#506]
## Description
Doesn't play any Track

## Version info
**Client used:** DSharpPlus

Output of `java -version`:
```
java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)
```

[spring.log](https://github.com/freyacodes/Lavalink/files/6860581/spring.log)

**Comment by TruSoggy** [comment]
i still have the same issue...

**Comment by topi314** [comment]
if I'm not totally blind you never forward a voice server update event
<https://github.com/freyacodes/Lavalink/blob/master/IMPLEMENTATION.md#provide-a-voice-server-update>

reach out to your lavalink-client devs on how to archieve that

**Comment by freyacodes** [comment]
Yes you are blind

It's a lavaplayer issue and with the latest version

**Comment by TruSoggy** [comment]
is there an API limit? because it seems to work for half a day and then it just stops... Bot is in 200+ servers

**Comment by freyacodes** [comment]
Try running the latest version and open this again if the issue persists
