### ISSUE TITLE
Building the files into a jar file

### ISSUE THREAD

**Issue by Sattishh** [lavalink-devs/Lavalink#508]
Hey everyone, since SoundCloud isn't working for me from the master branch, I want to use the Lavalink.jar based on the dev branch. 

However, I'm not sure how to build it into a jar file since there are no releases for the dev branches.

Can someone help me with this? Thanks.

**Comment by duncte123** [comment]
Go to the CI server linked in the bottom of the readme, download from the dev branch there

**Comment by Sattishh** [comment]
Got it from there! Thanks!
