### ISSUE TITLE
Received session description before protocol selection error

### ISSUE THREAD

**Issue by Tejas12972** [lavalink-devs/Lavalink#512]
## Version info
erela.js 

Getting this in the logs
 WARN 27 --- [ntLoopGroup-2-2] m.k.k.gateway.VoiceGatewayV4Connection   : Received session description before protocol selection? (connection id = .....) 
 
 Audio plays for a few seconds then cuts out, still posting in the logs tho

**Comment by freyacodes** [comment]
This could possibly be a Koe bug https://github.com/KyokoBot/koe

**Comment by Tejas12972** [comment]
Ok, I'll ask on there GitHub page thanks
