### ISSUE TITLE
Dosen't rotate ip and dont response on ip ban.

### ISSUE THREAD

**Issue by nottmayank** [lavalink-devs/Lavalink#514]
When my ip get rate-limited it dosent rotate ip & dosen't respond whereas works after restarting.
is there any way to make it work without restarting.

## Version info
**Client used: 3.3.2.5** 
Output of `java -version`:
```
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment (build 14+36-1461)
OpenJDK 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

```

it dosent respond after ip ban, it just searches and then nothing happens. After restarting works fine.

**Comment by freyacodes** [comment]
Please post logs and your ratelimit config
