### ISSUE TITLE
Nodes websocket keep disconnecting

### ISSUE THREAD

**Issue by veerack** [lavalink-devs/Lavalink#517]
## Description

Music works perfectly, no errors in my bot console, i have also a command that provides me all my Nodes status (i have shard-based nodes), their latency and players on them (also provides me a checkmark if the node is available or not)
As i see, nodes keeps going down every 20/30 seconds (precisely the websocket) and i have to reconnect the websocket manually / have a task that runs infinite to ensure the websocket connected.. idk why is this happening.

## Version info
**Client used:** 

Wavelink 0.9.10

Output of `java -version`:
```
openjdk 13.0.7 2021-04-20
OpenJDK Runtime Environment (build 13.0.7+5-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 13.0.7+5-Ubuntu-0ubuntu120.04, mixed mode)
```

I can't include these since i'm using a lavalink hosted by others (https://support.something.host/en/article/lavalink-hosting-okm26z/), i tried asking em for help since 5 days but didn't got a reply yet.

**Comment by freyacodes** [comment]
Huh, I didn't realise such a service existed.

I can't provide support for a third-party service. 

It's possible it could be a client issue, in which case it's not relevant to this issue tracker.

At any rate I recommend looking at the close code and reason upon websocket closure, and to look into hosting your own Lavalink server.

**Comment by veerack** [comment]
> Huh, I didn't realise such a service existed.
> 
> I can't provide support for a third-party service.
> 
> It's possible it could be a client issue, in which case it's not relevant to this issue tracker.
> 
> At any rate I recommend looking at the close code and reason upon websocket closure, and to look into hosting your own Lavalink server.

i actually want to host my own lavalink service, but i have no idea how to avoid youtube ratelimits since i have 50 constant players running 24/7 across all my bot guilds, and ratelimits comes very frequently (tried also with tunnelbroker ipv6 but still getting ratelimited after 1/2 hours).. any possible idea to avoid ratelimits?

**Comment by Arisstath** [comment]
Hello does the issue with lava.link still persist? We updated the way we load balance the connections.

**Comment by veerack** [comment]
> Hello does the issue with lava.link still persist? We updated the way we load balance the connections.

i don't know if this matter, but after some code fix, and after destroyed the node and recreated it back, everything seems working.. i was not destroying the node where i was connected when reloading music, maybe websocket sessions were stacking onto each one and causing the disconnections (i don't know if this is related tbh), but yes, now everything seems working fine, no websocket disconnected since 3 days ago (when i remade the node)
