### ISSUE TITLE
Missing option to disable native audio

### ISSUE THREAD

**Issue by Fabricio20** [lavalink-devs/Lavalink#52]
When testing LavaLink on new systems it would be nice to have a config option to disable native audio sending, since the internal checks do not account for new kernels/systems.

LavaLink seems to default NAS to enabled, making it impossible to test the resources on (currently) unsupported systems like linux-aarch64.

**Comment by freyacodes** [comment]
Feel free to add a switch to turn it off

On a sidenote, Lavaplayer generally performs very poorly on ARM.

**Comment by devoxin** [comment]
This doesn't look to be very easy - looks like this would require a modification to JDAA unless it has its own internal null checks for the AudioSendFactory

**Comment by shikhir-arora** [comment]
Lavaplayer does, you can run it without JDA-NAS which is what he's talking about I'm pretty sure. It's not hard to recompile Lavalink without JDA-NAS, but as Fred said it's something I would definitely recommend.

**Comment by freyacodes** [comment]
Time so clear up some misconceptions:

1. JDA uses its own AudioSendFactory when one isn't explicitly set
2. We enabled NAS at runtime https://github.com/Frederikam/Lavalink/blob/master/LavalinkServer/src/main/java/lavalink/server/Launcher.java#L126
3. NAS doesn't really have much to do with lavaplayer

**Comment by topi314** [comment]
implemented in https://github.com/freyacodes/Lavalink/releases/tag/3.7.0
