### ISSUE TITLE
Threshold surpassed: 10000

### ISSUE THREAD

**Issue by chronz** [lavalink-devs/Lavalink#520]
Hi, I get this error when using it with a discord bot.
`2021-09-20 05:16:25.962  WARN 659 --- [ntLoopGroup-2-1] lavalink.server.player.EventEmitter      : [MV] Weeekly(위클리) _ After School got stuck! Threshold surpassed: 10000`
How do I fix the issue? Is there a value in the config files which i have to change?
Thanks in advance

**Comment by freyacodes** [comment]
You should probably only worry about this warning if it's something that happens frequently or constantly. Playback is a bit fragile

**Comment by chronz** [comment]
> You should probably only worry about this warning if it's something that happens frequently or constantly. Playback is a bit fragile

It does happen quite often. Most of the time when I first send a command to play a song with the bot, it would not play anything at all. Then when the same play command is issued again, it would work. This error would come up after the first play command is issued. Not sure whether it's a bot problem or a lavalink problem so I thought I would ask here.

**Comment by JellyBrick** [comment]
Check your network bandwidth.
If the bandwidth is not sufficient, a track can be stuck.

**Comment by chronz** [comment]
> Check your network bandwidth.
> 
> If the bandwidth is not sufficient, a track can be stuck.

I have a 25 megabit connection up and down, is that adequate? 

would the host also be a problem? I’m currently self-hosting it on a 2-core 2GB RAM system. are the specs too low?

**Comment by topi314** [comment]
If you run into this error a lot for whatever reason lavalink now supports setting a custom value for stack struck 

This can help with slow audio sources such as radios

See https://github.com/freyacodes/Lavalink/pull/676
