### ISSUE TITLE
How to update every 0.1 s / 100ms

### ISSUE THREAD

**Issue by FreshImmuc** [lavalink-devs/Lavalink#522]
Yeah so how can I update the server every 0.1s or 100ms?

**Comment by aikaterna** [comment]
https://github.com/freyacodes/Lavalink/blob/eee27d4170c92abaa502100dc2c7582b168ee082/LavalinkServer/application.yml.example#L17

**Comment by FreshImmuc** [comment]
isnt this every 5 seconds?

**Comment by FreshImmuc** [comment]
I tried it and it is every 5 seconds. I am trying to update the clients every 0.1 s

**Comment by Moquent** [comment]
Just try setting the interval to 1s?  (1 second is the lowest)

**Comment by FreshImmuc** [comment]
> Just try setting the interval to 1s? (1 second is the lowest)

No. didn't work I get an error when I put 0.1 or 0,1

**Comment by Moquent** [comment]
> > Just try setting the interval to 1s? (1 second is the lowest)
> 
> No. didn't work I get an error when I put 0.1 or 0,1

1 second?
```bash
playerUpdateInterval: 1 # How frequently to send player updates to clients, in seconds
```

**Comment by FreshImmuc** [comment]
1 second is too high I need 0.1 or 0.2s

Moquent ***@***.***> schrieb am Mi., 22. Sept. 2021, 04:51:

**Comment by alula** [comment]
I think you're making a poor design choice, instead of making lavalink spam you with updates you should track the player state locally (increment the player timer every n milliseconds and correct it with update events sent by lavalink)
