### ISSUE TITLE
Not an issue, more of a question {endpoints}

### ISSUE THREAD

**Issue by MarquesCoding** [lavalink-devs/Lavalink#533]
I'm trying to create a express app where it would communicate with Lavalink was wondering if there is a way of getting guild data such as the queue etc to display on the website? I have my discord bot connected to Lavalink and that returns data such as what's in the queue, how many players are connected to that 'node'. I've tried using the same technique connecting using my express app but it doesn't show the same data... Is this because the 'node' creates instances?

Thanks

**Comment by freyacodes** [comment]
Lavalink doesn't have the concept of a queue. 

Lavalink doesn't currently have an endpoint to check what track (if any) is playing for a guild. You could get that data from your client
