### ISSUE TITLE
Handshake failed due to invalid Upgrade header: null

### ISSUE THREAD

**Issue by YueMiyuki** [lavalink-devs/Lavalink#537]
## Description
This error pops out every time when I start lavalink

## Version info
**Client used:** NodeJS

Output of `java -version`:
```
 java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

Logs attached
[logs.txt](https://github.com/freyacodes/Lavalink/files/7308201/logs.txt)

**Comment by freyacodes** [comment]
It looks like your client is not trying to establish a websocket
