### ISSUE TITLE
Lavalink always return the same selectedTrack for a Playlist

### ISSUE THREAD

**Issue by mccoderpy** [lavalink-devs/Lavalink#538]
## Description
When I request a playlist with a certain currently selected track (the `index` param in the URL) the selected track `selectedTrack` is returned correctly. However, if I request this playlist again with a different or no track selected, it still returns the one it returned the first time.

## Version info
**Client used:** Wavelink

Output of `java -version`:
```
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)
```

There is nothing in the logs related to this except that it loads the result for the URL. 

`Version`:        8bcb043d2a9c6ac73ce7f0bbcd09ce955edc4193-SNAPSHOT
`Build`:          1247
`Build time`:     25.09.2021 15:22:32 UTC
`Branch`          dev
`Commit`:         8bcb043
`Commit time`:    25.09.2021 15:19:28 UTC
`JVM`:            13.0.2
`Lavaplayer`      1.3.94-original

**Comment by mccoderpy** [comment]
This also happens on the latest stable version.

**Comment by devoxin** [comment]
The library used internally for scraping doesn't depend upon the `index` parameter. It uses the `v=` parameter (video ID), assuming this is a YouTube playlist.
