### ISSUE TITLE
Sound cloud issue

### ISSUE THREAD

**Issue by Bedrock16** [lavalink-devs/Lavalink#549]
Hey so I want to play music from sound cloud [in a Discord bot] when I try it .... In console lavalink give error ```no SoundCloud id provided``` so my question is where to provide that .... I am a beginner so please if anyone can help
Thank you

**Comment by topi314** [comment]
sounds like https://github.com/freyacodes/Lavalink/issues/543

**Comment by Bedrock16** [comment]
@TopiSenpai oh yea it works thanks
