### ISSUE TITLE
After about 2-3 hours the bot leaves the VC.

### ISSUE THREAD

**Issue by itamar1238** [lavalink-devs/Lavalink#555]
Hey. After about 2-3 hours my bot will just randomly leave the vc but lavalink is still playing! I dont know what could cause this  but it does get quite annoying. Is this on my end or discords?

**Comment by freyacodes** [comment]
Sounds like your bot rather than Discord. Lavalink has zero control over voice channels.

**Comment by itamar1238** [comment]
> Sounds like your bot rather than Discord. Lavalink has zero control over voice channels.

I have no clue as to what could be causing this. It was working not too long ago and now it cant stay in a vc for more than like 2 hrs.

**Comment by freyacodes** [comment]
If you want help you should speak with the people who use or develop whichever Discord library you're using

**Comment by itamar1238** [comment]
Ok. Thanks for the help otherwise!
