### ISSUE TITLE
Lavalink gets song information but doesn't play?

### ISSUE THREAD

**Issue by ItsLeon15** [lavalink-devs/Lavalink#556]
### Lavalink Not Playing Music

I've got Lavalink to get the song information and to play the song but when it tries to play it fails with no errors. 

**Lavalink Log**
`https://pastebin.com/fF2ZvPvp`

**Music Bot Code**
```js
let firstarray = fetchList.playlistArray[0].title;
let Searched = await player.search(firstarray, message.author);

if (fetchList.playlistArray) {
    player.queue.add(Searched.tracks[0]);
    if (!player.playing && !player.paused && !player.queue.size)
        player.play();
}
```

`fetchList.playlistArray[0].title;` returns the title of the song so no issues there?

Any help would be great

**Comment by ItsLeon15** [comment]
### Update

Lavalink only plays the song requested using `firstarray`, after it brings in a new song. 

The issue now seems that it can't play the song at first?

**Comment by topi314** [comment]
This is not a problem with lavalink but with your lavalink client

Reach out to the creators of the client

**Comment by ItsLeon15** [comment]
I've sent them an email, but in the meantime do you know what could be wrong with it? 

They aren't quick to respond

**Comment by Walkyst** [comment]
Library not sending `voiceUpdate` op for connecting to discord voice channel

**Comment by ItsLeon15** [comment]
So when I play another song, it does a 'voiceUpdate' and plays the first song?

Seems like a weird way of doing it but I guess I can find a workaround for it

**Comment by Walkyst** [comment]
`voiceUpdate` needs send once on connecting to voice or move bot between it, how this handled in your library i dont know

**Comment by ItsLeon15** [comment]
### Update

So, this was a surprising fix which for some reason I never found. The libary doesn't add `voiceUpdate` automatically so I had to solve for that. 

After the music plays it connects to the voice channel and boom!

Can't believe I'm so dumb.

Thanks @Walkyst for spotting the issue and helping me resolve it
