### ISSUE TITLE
Auto play not working

### ISSUE THREAD

**Issue by ItsLeon15** [lavalink-devs/Lavalink#568]
Hi there,

When I do ``player.set(`autoplay`, !player.get(`autoplay`))``, it doesn't auto play music. It just ends the queue? 

Please fix this for me. Lavalink reports autoplay as `True` but it doesn't do anything

**Comment by topi314** [comment]
lavalink has no property called autoplay
see https://github.com/freyacodes/Lavalink/blob/master/IMPLEMENTATION.md

**Comment by freyacodes** [comment]
Seek help from people that actually know whichever client you're using.

> Please fix this for me

This is not how you ask for help
