### ISSUE TITLE
Tracks with a specified `endTime` don't go to the next in queue as expected

### ISSUE THREAD

**Issue by zedseven** [lavalink-devs/Lavalink#569]
## Description
When a track with a specified end time reaches the time specified, it is stopped rather than being properly finished. This means it has to be "skipped" upon finishing, which requires additional overhead and doesn't seem to make sense.

When I say "properly finished", I specifically mean that I expect the track to end and the next in queue to play exactly as if the track had played out completely. I feel this is the way most users would expect it to behave.

If I'm somehow mistaken or this behaviour is working as designed, I'd love to know why. Thank you for your work on this library and tool.

## Version info
**Client used:** [lavalink-rs (with the original issue I raised for this)](https://gitlab.com/vicky5124/lavalink-rs/-/issues/5)

Output of `java -version`:
```
openjdk version "16" 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)
```

My log:
[spring.log](https://github.com/freyacodes/Lavalink/files/7573782/spring.log)

**Comment by topi314** [comment]
this has been fixed in https://github.com/freyacodes/Lavalink/pull/609 and `3.5rc1`
