### ISSUE TITLE
Don't play when I change the Voice Chat region (specific problem)

### ISSUE THREAD

**Issue by brunoxing2004** [lavalink-devs/Lavalink#570]
## Description
So, I have lavalink for a discord bot, and so far, all good.
But, when we need to change the region of the voice chat server, sometimes work, sometimes not.
I have the lavalink hosted in Germany (at Contabo) and the bot in js on Spain (at FDCServers).
A note, this only happens when I can connect to the new server faster than the bot can. For example, I change the region to India, and if the bot connects first to the voice chat, and I connect in second, I can listen to the music, but if the reverse happens, I can't listen.
Maybe this video can show better the problem: https://youtu.be/dj5rtGuwcnU

## Version info
root@plesk2:/lavalink# java -jar -Xmx15G Lavalink.jar --version

Version:        3.4
Build:          1257
Build time:     26.10.2021 14:18:37 UTC
Branch          master
Commit:         a364833
Commit time:    26.10.2021 14:15:20 UTC
JVM:            11.0.12
Lavaplayer      1.3.96-original

Output of `java -version`:
root@plesk2:/lavalink# java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Debian-2deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.12+7-
post-Debian-2deb10u1, mixed mode, sharing)

Logs (I send the full folder):
[logs.tar.gz](https://github.com/freyacodes/Lavalink/files/7576327/logs.tar.gz)

**Comment by Bedrock16** [comment]
It looks like you have Java 11 which has problem with lavalink. Read this for more info 

```Java 11 appears to have some issues with Discord's TLS 1.3. Java 14 has other undiagnosed HTTPS problems. Use Java 13. Docker images have been updated.```

**Comment by brunoxing2004** [comment]
Gonna check that. Thank you soo much!
I will give feedback as soon as possible.

**Comment by brunoxing2004** [comment]
Hello @Atharv-Pathak-14 
Tried with Java 13, didn't solve the problem.
I can try with a Docker version, but I think it's gonna be the same result.

**Comment by topi314** [comment]
thats prob the same problem as when you move the bot user into a different voice channel
this bug is known 

the current workaround is to pause & resume again after like 0.5s

**Comment by brunoxing2004** [comment]
Hello community, I have an update on this situation
So, after changing the bufferDurationMs from 400 to 100 (application.yml), it seems that the problem "it's solved".
After changing a lot of times from Brazil/USA/Japan/Australia/other regions to Europe (now Rotterdam) and vice-versa, the bot reacts correctly and plays the music.
However, the same doesn't happen when you move the bot, but for my case (a server to my class) it's just fine.

Thank for all the help, and Stay Safe!
