### ISSUE TITLE
Blacklist IP address

### ISSUE THREAD

**Issue by ririko5834** [lavalink-devs/Lavalink#584]
Is it possible to blacklist specific IP addressed from accessing the lavalink server? There are some IPs that are abusing my hosted lavalink.

**Comment by freyacodes** [comment]
That's what firewalls are for

**Comment by itsmishra19** [comment]
> Is it possible to blacklist specific IP addressed from accessing the lavalink server? There are some IPs that are abusing my hosted lavalink.

I don't know you can use something like `ufw` maybe not sure but it will work

**Comment by ririko5834** [comment]
I would appreciate if you would add field blockedIp to config where you can set array of blacklisted IP addresses
