### ISSUE TITLE
Fast playback in stage channels

### ISSUE THREAD

**Issue by KasaiKonoru** [lavalink-devs/Lavalink#589]
## Description
If I let play my musicbot in a discord stage voice channel, the bot has hightspeed and thats not normal.

## Version info
**Client used:** Erela.js

Output of `java -version`:
```
nor error
```

**Comment by ghost** [comment]
You provided invalid Java version. Also, the problem may be with your internet.

**Comment by Ruzie** [comment]
> ## Description
> If I let play my musicbot in a discord stage voice channel, the bot has hightspeed and thats not normal.
> 
> ## Version info
> **Client used:** Erela.js
> 
> Output of `java -version`:
> 
> ```
> nor error
> ```

As issue name that shall be problem with erela.js library not lavalink, you shall ask to their official server (MenuDocs) instead here.

**Comment by KasaiKonoru** [comment]
Yes I have the same problem. If I use move the bot and move him again to me, then the bot has highspeed

**Comment by freyacodes** [comment]
This is definitely not an erela issue

**Comment by devoxin** [comment]
I'm unable to reproduce this issue using latest build. Can you test with [3.5-rc1](https://github.com/freyacodes/Lavalink/releases/tag/3.5-rc1) and let me know if this resolves your issue?

> If I use move the bot and move him again to me, then the bot has highspeed

There is/was a known issue where if you send multiple `voiceUpdate`s to Lavalink in a short time frame it would cause audio to speed up. Please check your logs and ensure this is not the case. If it is, I would strongly advise informing the maintainer of your client library so they can correct this.
