### ISSUE TITLE
Required library could not be found on x86_64 Linux system (dev branch)

### ISSUE THREAD

**Issue by aidan-walden** [lavalink-devs/Lavalink#596]
## Description

Trying to commit filters results in the following error:
`Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.UnsatisfiedLinkError: Required library was not found`

## Version info
**Client used:** Lavalink-Client

Output of `java -version`:
```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-Debian-1deb11u2)
OpenJDK 64-Bit Server VM (build 17.0.1+12-Debian-1deb11u2, mixed mode, sharing)
```

[spring.log](https://github.com/freyacodes/Lavalink/files/7820099/spring.log)

**Comment by aikaterna** [comment]
#600 should fix this for you since your log indicates you're using a timescale filter when this happened.
