### ISSUE TITLE
Required library was not found (dev branch/builds)

### ISSUE THREAD

**Issue by Muh9049** [lavalink-devs/Lavalink#599]
## Description
For some reason using the official dev builds to apply the timescale filters returns this error and completely breaks the track: <https://srcb.in/YHbQc8HPlS>

Upon further digging into this issue, it seems that using the official master builds does not cause the track to crash and give that error and instead applies the timescale filter like it should even though it’s using Walkyst’s fork just like dev branch. Does anyone know why this might be the case and a workaround/fix?

master builds: https://ci.fredboat.com/viewType.html?buildTypeId=Lavalink_Build&tab=buildTypeStatusDiv&guest=%21&branch_Lavalink=%3Cdefault%3E
dev builds: https://ci.fredboat.com/viewType.html?buildTypeId=Lavalink_Build&branch_Lavalink=refs%2Fheads%2Fdev&tab=buildTypeStatusDiv&guest=!

**Note**: This issue happens on both Windows and Linux.

## Version info
Output of `java -version` (windows):
```
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

Output of `java -version` (linux):
```
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)
```

**Comment by szymonwilczek** [comment]
Try using this version of Lavalink: https://github.com/Cog-Creators/Lavalink-Jars/releases, and let me know

**Comment by Muh9049** [comment]
> Try using this version of Lavalink: https://github.com/Cog-Creators/Lavalink-Jars/releases, and let me know

At least from what I've heard, I'm sure it would but that doesn't solve the initial issue in the actual repo though. I'd rather use the official builds or build my own jars but I can't use it fully if I get the library not found error when applying timescale filters.

The problem is that the error is only occuring with the dev builds and not the master builds even though it uses the same LP fork, ladaDsp version, etc. Since that's the case, I assume something must've gotten messed up in a recent dev branch commit.
Keep in mind the dev builds never gave me this sort of issue until recently.

**Comment by Muh9049** [comment]
**Update**: Upon further digging again, I just found that ever since #1320, those have been the builds that error with the timescale filters now on. So basically any build from before #1320 worked fine with timescale. 🤔 

![image](https://user-images.githubusercontent.com/52611945/148411125-9258cdeb-4be3-4d56-bc2c-6c707ff03f20.png)

**Comment by freyacodes** [comment]
1320 is for a merge. If you want to dig deeper you can look at the `feature/plugins` branch

**Comment by viztea** [comment]
![image](https://user-images.githubusercontent.com/44017640/148454979-3245dd03-fba8-4a6f-b43e-734c1101ee87.png)

maybe this is the issue for the missing timescale natives?

**Comment by freyacodes** [comment]
Is that library provided with any other repositories? If so we could simply move JitPack to the bottom of the list

**Comment by viztea** [comment]
The build with natives should be on jcenter

**Comment by viztea** [comment]
If it's not on jcenter I have a build on my jfrog thing that should work fine 👍🏼

**Comment by Muh9049** [comment]
Moving jitpack below `jcenter()` fixes it :thumbsup:
