### ISSUE TITLE
Authentication failed from { ... } 

### ISSUE THREAD

**Issue by gamer50082** [lavalink-devs/Lavalink#611]
Authentication failed from { ... } 
I tested it on replit also

**Comment by gamer50082** [comment]
It’s because I change to ip (close)

**Comment by TheOnlyWayUp** [comment]
@gamer50082 I'm facing the same issue, could you explain how you fixed it? I'm deploying on replit atm, but if this continues to fail, I'll have to deploy it on my servers.
