### ISSUE TITLE
Node sometimes randomly stops playing music

### ISSUE THREAD

**Issue by Xirado** [lavalink-devs/Lavalink#620]
## Description
Sometimes, when we're playing music, in the middle of a song, Lavalink stops sending Audio to Discord.
The green indicator is gone, but the position still gets updated.
This could happen after an hour of playing music, maybe 2, maybe after 10 minutes.

Moving the bot to another channel and moving it back fixes the issue, so it's probably caused by the WS connection to discord?

## Version info
I'm using Lavalink-Client

Output of `java -version`:
```
java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

There are no logs whatsoever in either Lavalink itself or in the client. The last line is still the play op
```
Version:        d88d1c61aae2d069446ee46f32fa457b9f1a02a8-SNAPSHOT
Build:          1334
Build time:     14.01.2022 20:52:27 UTC
Branch          dev
Commit:         d88d1c6
Commit time:    14.01.2022 20:49:14 UTC
JVM:            13.0.2
Lavaplayer      1.3.97-original
```

**Comment by JellyBrick** [comment]
Have the same problem in `Java 11 / 16 / 17` (Azul OpenJDK)

**Comment by Xirado** [comment]
Another sidenote: From what i can tell, this started happening after we switched to the dev branch of Lavalink, i don't think this happened before (We switched to it when Plugin support got added)

**Comment by freyacodes** [comment]
> the position still gets updated.

Lavalink-Client just assumes the position if it isn't being updated by Lavalink

Is there anything suspicious in the log?

**Comment by Xirado** [comment]
> > the position still gets updated.
> 
> Lavalink-Client just assumes the position if it isn't being updated by Lavalink
> 
> Is there anything suspicious in the log?

Not at all, looks completely normal

**Comment by freyacodes** [comment]
What does `LavalinkPlayer#isPlaying()` return when this happens?

**Comment by Xirado** [comment]
> What does `LavalinkPlayer#isPlaying()` return when this happens?

I haven't checked that. I'll check when it happens again

**Comment by Xirado** [comment]
@freyacodes do you mean `LavalinkPlayer#isConnected` by any chance? There's no `isPlaying` method in `LavalinkPlayer`

**Comment by freyacodes** [comment]
Ah yes, my bad

**Comment by Xirado** [comment]
@freyacodes It actually returns true... Weird

![image](https://user-images.githubusercontent.com/68189302/153495118-0485ae64-dd2e-4d24-b48a-47008222a49c.png)

**Comment by unwell35** [comment]
> @freyacodes It actually returns true... Weird
> 
> ![image](https://user-images.githubusercontent.com/68189302/153495118-0485ae64-dd2e-4d24-b48a-47008222a49c.png)

same problem, the WebSocketClosedEvent fires but LavalinkPlayer#isConnected always returns true

**Comment by freyacodes** [comment]
What values does the closed event contain?

**Comment by unwell35** [comment]
as I remember, the reason is "Abnormal closure" and the error code is 1006.

**Comment by freyacodes** [comment]
I wonder if this could somehow be related to #445 

I believe this is the only change made to voice connection handling

**Comment by topi314** [comment]
there was also https://github.com/freyacodes/Lavalink/pull/577 touching this

**Comment by freyacodes** [comment]
Does Lavalink resume playing if you change the voice region?

**Comment by Xirado** [comment]
Apparently this is a bug with koe. Let me try

**Comment by Xirado** [comment]
> Does Lavalink resume playing if you change the voice region?

Yes it does

**Comment by topi314** [comment]
Koe doesn't support resuming
I'm currently looking into implementing this and will do some tests then


I'll keep you up to date 

https://discord.com/developers/docs/topics/voice-connections#resuming-voice-connection

**Comment by freyacodes** [comment]
> Koe doesn't support resuming

@TopiSenpai not but Lavalink resumes playback if a new voice connection is established

**Comment by topi314** [comment]
It seems like discord kills the connection and expects us to reconnect with the same credentials

We don't seem to get a voice server update for this

**Comment by topi314** [comment]
We would need to resume/connect again here afaik
https://github.com/freyacodes/Lavalink/blob/420dbd0cc36dd1bb5f5274d81b0ad69133ff4e4c/LavalinkServer/src/main/java/lavalink/server/io/SocketContext.kt#L231

**Comment by topi314** [comment]
Maybe it would be better if koe handles that internally once the ws dies aka close code 1006

**Comment by freyacodes** [comment]
This definitely seems like something Koe should deal with

**Comment by topi314** [comment]
👍
As said looking into it :)

**Comment by ShibaInu0413** [comment]
I have also encountered such a problem before. I used pm2 to run before, and then I switched to tmux and added `-Djdk.tls.client.protocols=TLSv1.1, TLSv1.2` to the java runtime, but currently there is no listening Such a problem, I have been testing for 13 hours and I am still testing

**Comment by ShibaInu0413** [comment]
I'm not sure if it's a problem with pm2, or not adding `-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2`, but I don't sound any problem now

**Comment by topi314** [comment]
I run my nodes via the docker image which have this flag and it does not fix the issue that koe simply doesn't reconnect
<https://github.com/freyacodes/Lavalink/blob/a060ab32cba4e7eec8a69cd91d8f80c60bc6eab3/LavalinkServer/docker/Dockerfile#L12>

**Comment by ShibaInu0413** [comment]
I think the problem may be `-Djdk.tls.client.protocols=TLSv1.1, TLSv1.2`, because there is no reason to execute the environment and make the socket close, so maybe add a `-Djdk.tls.client to the README. protocols=TLSv1.1,TLSv1.2`The problem may be solved

**Comment by ShibaInu0413** [comment]
Of course, it is also possible that there is a problem with pm2, because I did not test whether removing `-Djdk.tls.client.protocols=TLSv1.1, TLSv1.2` will cause the same problem, I will test again after a while , or if someone is willing to test it, and share it, I'd appreciate it

**Comment by ShibaInu0413** [comment]
Share my current version, environment, and execution command for reference
system : gcp VM ubuntu 20.04 
Lavalink :
```
Version: 3.4
Build: 1257
Build time: 26.10.2021 14:18:37 UTC
Branch master
Commit: a364833
Commit time: 26.10.2021 14:15:20 UTC
JVM: 13.0.10
Lavaplayer 1.3.96-original
```
run command : `java -Djdk.tls.client.protocols=TLSv1.1,TLSv1.2 -jar Lavalink.jar` in tmux

**Comment by ShibaInu0413** [comment]
I tested it many times later, but the problem doesn't seem to be that simple. Even if I add the java parameter, it will still cause the socket close to appear.

**Comment by topi314** [comment]
this has been fixed in https://github.com/freyacodes/Lavalink/releases/tag/3.5-rc1
