### ISSUE TITLE
Lavalink Docker Imager Error

### ISSUE THREAD

**Issue by AriaFantom** [lavalink-devs/Lavalink#621]
## Description
I am trying to pull docker image

## Version info
**Latest Version from Docker**

## Error
```
Using default tag: latest
Error response from daemon: manifest for fredboat/lavalink:latest not found: manifest unknown: manifest unknown
```

**Comment by topi314** [comment]
https://hub.docker.com/r/fredboat/lavalink/tags

**Comment by freyacodes** [comment]
Please don't use this issue tracker for troubleshooting. We have a Discord channel.

The `latest` tag doesn't exist.
