### ISSUE TITLE
Lavalink preventing me from playing provanity videos like F the police by nwa

### ISSUE THREAD

**Issue by ZeroG-Network** [lavalink-devs/Lavalink#622]
## Description

Discord i asked about where to put this https://github.com/Walkyst/lavaplayer-fork/issues/18 and as discord so slow i am asking in an issue, where do i put the "YoutubeHttpContextFilter" cause my lavalink does not allow me to play profanity videos from youtube. keeps telling me this https://mcpaste.io/16babcaff2cbd441

## Version info
**Client used:** 
A music bot from coding with sudhan https://github.com/SudhanPlayz/Discord-MusicBot
Output of `java -version`:
```
java version "16.0.2" 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

Version:        a060ab32cba4e7eec8a69cd91d8f80c60bc6eab3-SNAPSHOT
Build:          1336
Build time:     24.01.2022 12:04:37 UTC
Branch          master
Commit:         a060ab3
Commit time:    24.01.2022 11:59:16 UTC
JVM:            16.0.2
Lavaplayer      1.3.96-original

**Comment by topi314** [comment]
use dev and see https://github.com/freyacodes/Lavalink/pull/582

**Comment by ZeroG-Network** [comment]
i have the keys, i want to know where and how do i i add it as the info being provided is so limited.

**Comment by ZeroG-Network** [comment]
OK NVM, i found it
Thank you

**Comment by ZeroG-Network** [comment]
OK added it and still does not allow me to play the songs, Yes i did restart the server

**Comment by freyacodes** [comment]
Please use the discord channel if you need help troubleshooting. This is strictly an issue tracker

> Yes i did restart the server

This suggests that you didn't update to the dev branch
