### ISSUE TITLE
Problem playing a radio stream

### ISSUE THREAD

**Issue by chredeur** [lavalink-devs/Lavalink#632]
## Description
When I launch the playback of a radio via a url lavalink starts to play the music but takes a lot of delay on the playback and finally it is disconnected from the radio for having taken too much delay and thus generates an error "Error in playback of http://url:8000/radio.ogg" I would like to know if there is a possibility to make lavalink take the least delay on the playback or then and a maximum delay.

## Version info
Wavelink
Lavalink 3.4

Output of `java -version`:
```
openjdk version "15.0.5" 2021-10-19
OpenJDK Runtime Environment Zulu15.36+13-CA (build 15.0.5+3-MTS)
OpenJDK 64-Bit Server VM Zulu15.36+13-CA (build 15.0.5+3-MTS, mixed mode, sharing)
:/home/container$ java -jar Lavalink.jar --version
Version:        eec629def799086d30e7df25f03c398d64357783-SNAPSHOT
Build:          1342
Build time:     22.02.2022 11:17:22 UTC
Branch          master
Commit:         eec629d
Commit time:    22.02.2022 11:14:41 UTC
JVM:            15.0.5
Lavaplayer      1.3.96-original
```

[error.txt](https://github.com/freyacodes/Lavalink/files/8217575/error.txt)

**Comment by freyacodes** [comment]
The error message `Stream is not positioned at a page header` suggests that it is either not a valid or recognised audio stream

**Comment by chredeur** [comment]
> The error message `Stream is not positioned at a page header` suggests that it is either not a valid or recognised audio stream

Ah well however the link that I provide him and well an audio flow: http://148.251.253.55:8000/phonk.ogg it is just that this error appears at the time when the radio stops the diffusion of the audio flow to lavalink because of its delay

**Comment by chredeur** [comment]
Here are the logs of lavalink with the error just in case
[logs.txt](https://github.com/freyacodes/Lavalink/files/8226275/logs.txt)

**Comment by chredeur** [comment]
Ah and to solve this problem I have only two solutions either add an option to replay the radio or have an option to play the radio without too much delay or not at all
