### ISSUE TITLE
Music start with latency (7seconds before music start)

### ISSUE THREAD

**Issue by WeezDev** [lavalink-devs/Lavalink#642]
## Description

Music start but with latency (7seconds), i host it on linux (debian, ubuntu) vps.
Thank's for help

## Version info
**Client used:** I use the last Releases 

Output of `java -version`:
```
openjdk 13.0.7 2021-04-20
OpenJDK Runtime Environment (build 13.0.7+5-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 13.0.7+5-Ubuntu-0ubuntu120.04, mixed mode)
```

	Version:        3.4
	Build:          1257
	Build time:     26.10.2021 14:18:37 UTC
	Branch          master
	Commit:         a364833
	Commit time:    26.10.2021 14:15:20 UTC
	JVM:            13.0.7
	Lavaplayer      1.3.96-original

**Comment by devoxin** [comment]
What's your network speed and hardware specs? Might be that your server or network is overloaded and struggling to buffer audio.

**Comment by gamer50082** [comment]
can u reply?

**Comment by gamer50082** [comment]
could be just bot having 10% cpu usage and 32mb ram

**Comment by WeezDev** [comment]
Hey, no i find solution the problem is the network of my vps
