### ISSUE TITLE
LowPass filter enabledValue seems strange/suboptimal

### ISSUE THREAD

**Issue by ToxicMushroom** [lavalink-devs/Lavalink#650]
## Description

Currently lowpass docs default AND disable at **20.0**
-> 19.9 and 20.1 still give noticeable low-pass effect so this disable value makes no sense to me

I also noticed that values under **0.5** immediately cut all audio
with **0.5** itself sounding the same as without low-pass so maybe this should be the disable value ?
the docs currently don't have any limits set for low-pass, perhaps setting `0.5` as inclusive minimum would be applicable ?

## Version info
**Client used:** Lavalink.kt

Output of `java -version`: 
for running the bot: `11.0.13`
for ll whatever `fredboat/lavalink:dev` uses i.g

**Comment by devoxin** [comment]
Closing as this should no longer be an issue as of `v3.5-rc2`.
