### ISSUE TITLE
Youtube search is broken

### ISSUE THREAD

**Issue by pauldb09** [lavalink-devs/Lavalink#660]
## Description
Since 6 hours ago the youtube search isn't working ( works for tracks ) and for youtube music

## Version info
**Client used:** Shoukaku 3.0.5

Output of `java -version`:
```
13.0.7
```

Dev branch of lavalink but seems to be happening for everyone

**Comment by Tomato6966** [comment]
Same Problem here

Client: `erela.js` V2.3.3
`java --version`: `openjdk 11 2018-09-25` (v11)

Happened since  ~7 hours ago

Youtube Links work tho

v3.4 Stable Branch 
Happenening on: 10 different ipv4 adddresses
Ubuntu, Debian and Windows
with over 15 different ipv6/64 and ipv6/48 blocks!

**Comment by huotarih** [comment]
Same here, with whatever comes with the redbot audio cog and ubuntu 20 vps. 

openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

Lavalink

Version:        8e1010aa9f473f567e5926a1e25b2917ca9c7ac4-SNAPSHOT
	Build:          1275
	Build time:     13.12.2021 11:31:08 UTC
	Branch          dev
	Commit:         8e1010a
	Commit time:    13.12.2021 11:27:16 UTC
	JVM:            11.0.15
	Lavaplayer      1.3.96-original

**Comment by Quintenvw** [comment]
Same here on 3.4 release. Only affects ytsearch. This happened simultaneously on multiple nodes.

**Comment by karelkryda** [comment]
I opened [issue](https://github.com/Walkyst/lavaplayer-fork/issues/49) in Lavaplayer repo.

As I mentioned, it's possible that YT changed JSON response structure or smth.

**Comment by N1C0exe** [comment]
same here

**Comment by topi314** [comment]
fix is on it's way
https://github.com/Walkyst/lavaplayer-fork/pull/50

there is also a temporary fix jar built by me 
https://cdn.discordapp.com/attachments/418817098278764544/979044972156317746/Lavalink.jar

**Comment by Git-Jaydeep** [comment]
> fix is on it's way [Walkyst/lavaplayer-fork#50](https://github.com/Walkyst/lavaplayer-fork/pull/50)
> 
> there is also a temporary fix jar built by me https://cdn.discordapp.com/attachments/418817098278764544/979044972156317746/Lavalink.jar

I guess there is still an issue, like if I search music It doesn't play it it just queues it 
and if I play from link it also starts playing. Then if I search the same song and skip it plays it !

Is this issue only for me or for everyone?

**Comment by Matts-V** [comment]
same here. Youtube search randomly broke

**Comment by SIGTERM-015** [comment]
Same here, ytsearch broken

**Comment by devoxin** [comment]
@mat321 @NereaCassian Please refer to the comment directly above yours for links to the fix and a new Lavalink jar.

**Comment by Matts-V** [comment]
Yea... Just changed it and it works again, thx!

**Comment by N1C0exe** [comment]
> fix is on it's way [Walkyst/lavaplayer-fork#50](https://github.com/Walkyst/lavaplayer-fork/pull/50)
> 
> there is also a temporary fix jar built by me https://cdn.discordapp.com/attachments/418817098278764544/979044972156317746/Lavalink.jar

the jar file throw error if i use it on a rpi

**Comment by devoxin** [comment]
Lavaplayer does not include ARM natives by default.

**Comment by devoxin** [comment]
Update, I have attempted to build a jar with ARM natives included (https://serux.pro/2277cf-Lavalink.jar). My testing only goes as far as running it on Windows to ensure natives still load fine (which they do), so *should* work with most ARM-based systems.

**Comment by Monix362** [comment]
> fix is on it's way [Walkyst/lavaplayer-fork#50](https://github.com/Walkyst/lavaplayer-fork/pull/50)
> 
> there is also a temporary fix jar built by me https://cdn.discordapp.com/attachments/418817098278764544/979044972156317746/Lavalink.jar

Is this a problem on the side of the library I use to transfer data to the Lavalink?

![Termius_LNNWa6Nnoc](https://user-images.githubusercontent.com/61246713/170527695-24dba683-5a74-46df-8215-1dfb94f3430b.png)

**Comment by topi314** [comment]
Yes it is
You can't send a play without providing which track to play

**Comment by Vretu-Dev** [comment]
> Update, I have attempted to build a jar with ARM natives included (https://serux.pro/2277cf-Lavalink.jar). My testing only goes as far as running it on Windows to ensure natives still load fine (which they do), so _should_ work with most ARM-based systems.

On Linux aarch64 works fine

**Comment by mxscowc1ty** [comment]
> > Update, I have attempted to build a jar with ARM natives included (https://serux.pro/2277cf-Lavalink.jar). My testing only goes as far as running it on Windows to ensure natives still load fine (which they do), so _should_ work with most ARM-based systems.
> 
> On Linux aarch64 works fine

confirm, tysm!

**Comment by N1C0exe** [comment]
> Update, I have attempted to build a jar with ARM natives included (https://serux.pro/2277cf-Lavalink.jar). My testing only goes as far as running it on Windows to ensure natives still load fine (which they do), so _should_ work with most ARM-based systems.

can u send me a jar file that works on ARM ?

**Comment by aikaterna** [comment]
> can u send me a jar file that works on ARM ?

Use the one Devoxin linked above. It works on ARM devices.

**Comment by N1C0exe** [comment]
> > can u send me a jar file that works on ARM ?
> 
> Use the one Devoxin linked above. It works on ARM devices.

yes yes ty

**Comment by aikaterna** [comment]
> Update, I have attempted to build a jar with ARM natives included (https://serux.pro/2277cf-Lavalink.jar). My testing only goes as far as running it on Windows to ensure natives still load fine (which they do), so _should_ work with most ARM-based systems.

This jar has the archived version of lavadsp built for it, which builds a libtimescale.so file for aarch64 with glibc 2.29+ symbols while some OSes using the linux aarch64 designation need a top limit of glibc 2.27 (Ubuntu 18) or glibc 2.28 (Raspbian OS 64 bit), which leads to the issue posted on https://github.com/Cog-Creators/Lavalink-Jars/issues/12 with timescale transforms using this native. If anyone else has this issue, you can use the Lavalink.jar found at https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.4.0_1347 and it has this resolved.

**Comment by devoxin** [comment]
Fix merged into dev branch so I think this is safe to close now.
