### ISSUE TITLE
Lavalink stop sending player event

### ISSUE THREAD

**Issue by flav-code** [lavalink-devs/Lavalink#664]
Librairies: Shoukaku/Discord.js and Shoukaku/Eris
Lavalink build: every
Java version tested: 11 13
Tested on 210k bot, 30k, 8k

The bug happens randomly, several people have this bug and we find neither the source nor how to fix it

Lavalink stop sending player event
we can always send requests like play, stop, skip and lavalink receives them well, but then we receive more data from lavalink, it seems that the ws works only in one direction.
The rest works fine.
There is no error, either on the side of lavalink or the bot.
![image](https://user-images.githubusercontent.com/48295189/172016423-2671abb5-ebf8-4ae8-b2df-73b8f505e57c.png)

**Comment by pauldb09** [comment]
Yeah, i already tested it with java 15 and still same error, having this error on 3 different dedicated servers. 
Hosted on OVH

**Comment by pauldb09** [comment]
@freyacodes Hello! Could you have a check on it please?
