### ISSUE TITLE
How to get Resume key

### ISSUE THREAD

**Issue by appujet** [lavalink-devs/Lavalink#667]
```cmd
{
    "op": "configureResuming",
    "key": "myResumeKey",
    "timeout": 60
}
```

**Comment by topi314** [comment]
Like we said in discord
It can be whatever u want
https://github.com/freyacodes/Lavalink/blob/master/IMPLEMENTATION.md#resuming-lavalink-sessions

**Comment by appujet** [comment]
Oh ok
