### ISSUE TITLE
error when playing any song <v1>

### ISSUE THREAD

**Issue by mason-rogers** [lavalink-devs/Lavalink#68]
Yes I am only using V1 because the d.js client is not updated. But whenever I play ANY song it just errors and does this: https://vic.tion.exposed/uPRdi.png and then emits the end event

**Comment by schnapster** [comment]
You need to use an LL server build from this branch: https://github.com/Frederikam/Lavalink/tree/v1-legacy

**Comment by mason-rogers** [comment]
does the one on the CI server come compiled, I need that one but compiled.

**Comment by freyacodes** [comment]
https://ci.fredboat.com/viewLog.html?buildId=2823&tab=artifacts&buildTypeId=Lavalink_Build&guest=1

**Comment by mason-rogers** [comment]
xx

**Comment by mason-rogers** [comment]
![image](https://user-images.githubusercontent.com/26467584/36062988-8c12bdf6-0e6e-11e8-9ea6-98dd11b423f4.png)

**Comment by mason-rogers** [comment]
nvm it was me being bad i downloaded the wrong jar lololol
