### ISSUE TITLE
Instructions to build from source

### ISSUE THREAD

**Issue by rilysh** [lavalink-devs/Lavalink#684]
According to https://github.com/freyacodes/Lavalink/issues/282#issuecomment-625211233 I tried to build lavalink from source (on Debian), but each-time it failed with an error.
```
Could not open settings generic class cache for settings file '/home/ruzie/Desktop/Lavalink/settings.gradle' (/home/ruzie/.gradle/c
aches/6.5/scripts/4a9t6ok2db86cgcvjf7tylihv/settings6418c6d726070f323dbddda2aadc82ef).
```
Full stack trace: [stacktrace.txt](https://github.com/freyacodes/Lavalink/files/9021363/stacktrace.txt)
I've no experience with java or gradle before, I'm not sure what's wrong there. I used OpenJDK 17.

It will be really good, if you provide how to build from source, and the requirements to build.

**Comment by aikaterna** [comment]
> Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61

Try building with Java 13 or Java 11 instead.

**Comment by rilysh** [comment]
Thanks, I used Java 11, everything goes pretty well. Since it's done, I'm closing this issue.
