### ISSUE TITLE
running lavalink with multiple ports?

### ISSUE THREAD

**Issue by alonemazin** [lavalink-devs/Lavalink#686]
Hey, 
Im trying to run lavalink with multiple ports. But the thing is i don't know exactly how to make that happen I tried to provide array in ``application.yml`` file in `port` field and it didn't work

**Comment by devoxin** [comment]
Lavalink doesn't support this. What's your use-case for listening on multiple ports?

**Comment by freyacodes** [comment]
One way to accomplish similar results would be to run a reverse proxy like nginx or caddy on top of Lavalink. The reverse proxy would forward traffic from one port to Lavalink running on another.

Though such a configuration is outside the scope of this issue tracker
