### ISSUE TITLE
My bot's console sends "Not matches found"

### ISSUE THREAD

**Issue by Cd-corgi** [lavalink-devs/Lavalink#690]
I just updated my lavalink server with the new release and it marks me with "not matches found" every song that i put in my bot to search and play, please. How can i solve this??

**Comment by topi314** [comment]
this happens due to a change in YouTube.
This should be fixed `3.5-rc1` or `dev`

**Comment by topi314** [comment]
duplicate of https://github.com/freyacodes/Lavalink/issues/660
