### ISSUE TITLE
Session is no longer valid (code: 4006)

### ISSUE THREAD

**Issue by seammd124** [lavalink-devs/Lavalink#691]
When my bot is in a voice channel for too long
I am facing this problem
{
  op: 'event',
  reason: 'Session is no longer valid.',
  code: 4006,
  byRemote: true,
  type: 'WebSocketClosedEvent',
  guildId: ''
}

Output of `java -version`: 
```
java version "18" 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
```

Version:        c47990b9493f224773a45ef23244b11e4aeadf7c-SNAPSHOT
Build:          1353
Build time:     10.06.2022 18:37:07 UTC
Branch          dev
Commit:         c47990b
Commit time:    10.06.2022 18:28:37 UTC
JVM:            18
Lavaplayer      1.3.97-original

**Comment by devoxin** [comment]
I wouldn't really say this is an issue within Lavalink, more that your session expired which is normal behaviour. If your library supports it, you can listen for these `WebSocketClosedEvent`s and reopen the connection if you so wish, however as stated this isn't really an issue so I'll go ahead and close this.

If you wish to discuss this further you can join the Discord server linked in the README.
