### ISSUE TITLE
Voice latency?

### ISSUE THREAD

**Issue by Artucuno** [lavalink-devs/Lavalink#737]
## Description
Hey, I was wondering if you could add voice latency to lavalink if it isn't in the library already? Having voice latency would be awesome and would be good for debugging nodes.

Thanks!

## Version info
**Client used:** Lavalink.py

Output of `java -version`:
```
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
```

**Comment by devoxin** [comment]
Added in 39a171c

**Comment by Artucuno** [comment]
How do I build the update? I've never used java before.

**Comment by devoxin** [comment]
Already built, scroll down to 'Artifacts' https://github.com/freyacodes/Lavalink/actions/runs/3021601094
