### ISSUE TITLE
Lavalink not sending sound to voice channel

### ISSUE THREAD

**Issue by vkamsingh** [lavalink-devs/Lavalink#746]
Hello there,
         so i am getting issue in my application playing a track. everything working okay but after sum time track voice didn't reach to voice channel after remove player still issue happening

**Comment by topi314** [comment]
there has been some issues with silence yt tracks which should be resolved in https://github.com/freyacodes/Lavalink/releases/tag/3.6.1

if this issue persists after updating feel free to reopen the issue
