### ISSUE TITLE
YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.

### ISSUE THREAD

**Issue by TheFroster1234** [lavalink-devs/Lavalink#747]
## Description

I was using my client for lavalink as well, until today i got an error like the title. From that error, no one songs wants to play! I want to know how to solve it

## Version info
**Client used:** Poru 

Output of `java -version`:
```
13.0.2
```

![image](https://user-images.githubusercontent.com/93305631/190936618-3cbc8590-e0e2-4bd7-9b8d-932cb8591cbc.png)

**Comment by devoxin** [comment]
That error shouldn't be the reason why no songs play. The snippet of the stack trace you provided doesn't offer any real insight into your issue. Please upload your spring.log file.

**Comment by topi314** [comment]
I'm going to close this as their hasn't been any response. Feel free to reopen it with more info
