### ISSUE TITLE
Playing local audio files

### ISSUE THREAD

**Issue by ShyPianoGuy** [lavalink-devs/Lavalink#76]
how would i go on about playing a local file?

**Comment by freyacodes** [comment]
Never tried this. Presumably, you would have to send the file path as the identifier. Bear in mind that the file is local to the lavalink server receiving the request.

**Comment by ShyPianoGuy** [comment]
oh so something like ?identifier=/path/to/file?

**Comment by MrJacz** [comment]
I'd assume so

**Comment by ShyPianoGuy** [comment]
i tried, got nothing :(

**Comment by freyacodes** [comment]
You need to URL encode the parameter.

`/path/to/file` becomes `%2Fpath%2Fto%2Ffile`

**Comment by devoxin** [comment]
Also don't forget to enable the local audio source manager in `application.yml`

**Comment by ShyPianoGuy** [comment]
still didn't seem to work. My application has local: true and i did the URL encoded way and tried multiple paths and still didn't seem to work

**Comment by Macleykun** [comment]
~~You need to use it like this: `.play file://Music/RickRolledMe.mp3`~~
~~Music would be the folder you added in the same folder where the fredboat.jar file is.~~

~~However there is a little bug. You can't have any spaces in your path or it won't work.~~

I'm so dump. Tottaly unrelated to the issue. Please ignore this.

**Comment by freyacodes** [comment]
The audio file is on the server, right?

**Comment by ShyPianoGuy** [comment]
yes @Frederikam

**Comment by MrJacz** [comment]
So after testing, the file has to be in the same folder as the Lavalink.jar file, the URL to get the track is `http://localhost:2333/loadtracks?identifier=TheFileName.extension`
[![Image](https://jaczaus.me/i/je228ey4bb6c2a0.png)](https://jaczaus.me/i/je228ey4bb6c2a0.png)

**Comment by devoxin** [comment]
I'm not sure the file has to be in the same folder, I've had MP3 tracks in my music folder on Windows (no spaces, though), identifier isn't URL encoded (using lavalink.py V2) and it works

**Comment by devoxin** [comment]
![image](https://user-images.githubusercontent.com/15076404/36636760-e49c157e-19c4-11e8-8c61-d447f4180fa0.png)

**Comment by devoxin** [comment]
Also to clarify, paths containing spaces are also working for me.

**Comment by MrJacz** [comment]
Thats werid, didnt work for me

**Comment by devoxin** [comment]
What lavalink wrapper are you using?

**Comment by MrJacz** [comment]
Discord.js-lavalink (My own) but wrapper doesn't matter, its what you use to resolve the track, lol

**Comment by shikhir-arora** [comment]
Can also confirm it works for me and it doesn't have to be in the Lavalink folder. 

<img width="1593" alt="screen shot 2018-02-24 at 11 14 37 pm" src="https://user-images.githubusercontent.com/8797918/36638080-8db7dc9a-19b8-11e8-8407-c1e746ad851b.png">
<img width="1593" alt="screen shot 2018-02-24 at 11 14 21 pm" src="https://user-images.githubusercontent.com/8797918/36638081-8dc635ba-19b8-11e8-9bef-84ab337a937e.png">

**Comment by freyacodes** [comment]
>Discord.js-lavalink (My own) but wrapper doesn't matter, its what you use to resolve the track, lol

If your wrapper doesn't percent encode the string it should fail. Eg you need `%20` instead of a space.

**Comment by MrJacz** [comment]
@Frederikam The users of my wrapper are to handle resolving of the tracks themselves... it doesnt do anything on the rest side...

**Comment by schnapster** [comment]
To sum up the given answers:
- Make sure local files are enabled in your lavalink server config
- Properly url encode the query parameters when resolving the tracks via `/loadtracks`
- Ensure the audio files are actually present on the machine where lavalink is running

If this does not resolve the issue, please post logs of the server and/or show what happens when you `curl` the `/loadtracks` endpoint.
