### ISSUE TITLE
[Feature Request] Allow Lavalink to read application.yml from another directory

### ISSUE THREAD

**Issue by regunakyle** [lavalink-devs/Lavalink#767]
Hi,

Not sure if this is already possible, but can Lavalink read application.yml from another directory?
For example (Search in this order):
`1. <LavalinkDir>/application.yml`
`2. <LavalinkDir>/conf/application.yml` 
`3. ~/application_lavalink.yml`
`4. Use default profile`

This is to ease docker deployment: Currently I (bind) mount the application.yml file to /opt/Lavalink/application.yml.
I want to mount a docker volume to the container (e.g. lavalink-volume:/opt/Lavalink/conf) and reuse this volume for another container later (so that I can modify it programmatically).
AFAIK docker volume can only be mounted as a directory.

**Comment by freyacodes** [comment]
There are many options. You can even use environment variables https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/html/boot-features-external-config.html 
    
    
     
    
   
     And yes, you can mount single files. 
    
    
     
      
      Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/freyacodes/Lavalink/issues/767","url": "https://github.com/freyacodes/Lavalink/issues/767","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by regunakyle** [comment]
> There are many options. You can even use environment variables https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/html/boot-features-external-config.html And yes, you can mount single files. Message ID: ***@***.***> ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "#767","url": "#767","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

Thank you for your answer!
For future readers, you can do one of the following:
1. Use environment variables, for example:
    - `server.port: 2333` (btw the docker image uses port 8080 for Lavalink by default)
    - `lavalink.server.password: "yourpassword"`
3. Mount your volume (or bind mount) to `/opt/Lavalink/config`, then put your `application.yml` inside
4. Mount the file `application.yml` from your system directly to `/opt/Lavalink/application.yml`
