### ISSUE TITLE
[v2] I/O Exception when processing request due to connection reset

### ISSUE THREAD

**Issue by TheWyn** [lavalink-devs/Lavalink#77]
Babysat till the error occurred, the youtube livestream didn't go down at any point nor did the discord bot, stop command was not issued by any user.  Using Jar build 3005, Pip version 2.0.2.5 and Lavalink.py v2 branch.

Log:
![](https://cdn.discordapp.com/attachments/389824560008265733/415805738116710420/lavalink_log.PNG)

**Comment by freyacodes** [comment]
Connection problems will inevitably happen. You might want to retry on abnormal track ending.

**Comment by TheWyn** [comment]
Looking like jar build 3065 has fixed this.
![](https://cdn.discordapp.com/attachments/169868846759542785/418152359609237524/Capture.PNG)

**Comment by devoxin** [comment]
This should be resolved on Lavaplayer 1.2.54 (Lavalink Build 3066)

**Comment by schnapster** [comment]
This hasn't been reported in a while so I'm going to assume what @Devoxin says is correct.
Please don't hesitate to reopen if this is still an issue on the current builds.
