### ISSUE TITLE
Stucked at "Updating YouTube master token succeeded"

### ISSUE THREAD

**Issue by malthemorsing** [lavalink-devs/Lavalink#772]
## Description
Hi,
Lavalink is stuck on "Updating YouTube master token succeeded". It works perfectly fine without configuring youtube.
spring.log attached. Let me know if you need more information.

Output of `java -version`:
```
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```

Output of 'java -jar Lavalink.jar --version':
```
Version:        3.6.1
Build time:     28.10.2022 09:12:10 UTC
Branch          HEAD
Commit:         ee42ec1
Commit time:    28.10.2022 09:10:11 UTC
JVM:            18.0.2.1
Lavaplayer      1.3.99-original
```
[spring.log](https://github.com/freyacodes/Lavalink/files/9896775/spring.log)

**Comment by freyacodes** [comment]
> Started Launcher in 1.376 seconds (JVM running for 2.804)
> ...
> Lavalink is ready to accept connections.

Looks perfectly fine to me, but you're not connecting to Lavalink. What were you expecting?

**Comment by malthemorsing** [comment]
Well, looks like it was just a case of me not getting enough sleep. My apologies for the confusion and thanks for checking it out! By the way, thank you so much for all your hard work in creating Lavalink, it's really helpful.
