### ISSUE TITLE
resolve Promise

### ISSUE THREAD

**Issue by vanna-code** [lavalink-devs/Lavalink#778]
resolve Promise {
  { playlistInfo: {}, loadType: 'TRACK_LOADED', tracks: [ [Object] ] }
} undefined

how to fix this in discord.js v13

**Comment by devoxin** [comment]
I don't see what the problem is?

**Comment by parasop** [comment]
> resolve Promise { { playlistInfo: {}, loadType: 'TRACK_LOADED', tracks: [ [Object] ] } } undefined
> 
> how to fix this in discord.js v13

use await keywords to resolve Promise

**Comment by vanna-code** [comment]
use await in comands play ?

**Comment by parasop** [comment]
> use await in comands play ?

yes where you search song

**Comment by vanna-code** [comment]
![image](https://user-images.githubusercontent.com/71807955/203306972-ee7b1623-c663-47d4-a0a2-9c562664ed3d.png)

i don't know how to fix this .

**Comment by topi314** [comment]
reach out to your client lib maintainers. This is about lavalink not node.js
