### ISSUE TITLE
[Feature Request] Add whitelisted IP option to the application.yml

### ISSUE THREAD

**Issue by Rajdave69** [lavalink-devs/Lavalink#792]
I'd like to suggest a new option to be added to the application.yml. It's a whitelisted-ips. 
This option allows only the whitelisted IPs declared in the application.yml to authenticate and interact with the Lavalink server.

**Comment by topi314** [comment]
are there any reasons why the password is not sufficient?

**Comment by Rajdave69** [comment]
Well, since there is already a blacklist option it would make sense to include a whitelist option too. It would be useful for a Lavalink server which is supposed to be accessed from only that one IP, or a list of IPs for added security.

**Comment by topi314** [comment]
Where is a blacklist option?

**Comment by Rajdave69** [comment]
https://github.com/freyacodes/Lavalink/blob/master/LavalinkServer/application.yml.example#L28

Here, pretty sure.

**Comment by topi314** [comment]
That is for ipv6 rotation and something completely different

**Comment by Rajdave69** [comment]
Ah nevermind then, but I still think whitelists would be a good idea even on its own

**Comment by topi314** [comment]
You can put a reverse proxy like nginx infront of lavalink to achieve this already
I don't think it's a useful feature
The password already provides enough security
