### ISSUE TITLE
Searching Request takes too long

### ISSUE THREAD

**Issue by ZuherLaith** [lavalink-devs/Lavalink#793]
I'm using Erela.js client and Lavalink self hosted,
The Problem is when the node makeRequest goes to lavalink, it takes so much time to load a youtube URL (from 10 sec to a minute)
but when I retry the process, it happens within 2 seconds (the normal way)
`const MusicTracks = await this.client.erela.search(query, msg.author).catch(e=> {console.log(e);});`
when the request takes too long and an error happens, it leads to this code in erela.js/Manager.js library (on node):
https://sourceb.in/GM9kBcA08m
This started happening too often in the last version of lavalink.

Also, when the search starts, nothing shows up on the lavalink logs, I start to believe its the erela.js client issue

## Version info
Erela.js 2.4.0

Output of `java -version`:
```
Java 13 on Linux Host
```

Version:        3.6.2
Build time:     08.11.2022 09:02:53 UTC
Branch          HEAD
Commit:         4782f1f
Commit time:    08.11.2022 09:01:14 UTC
JVM:            13.0.2
Lavaplayer      1.3.99.1-original

**Comment by parasop** [comment]
erela.js is archived use any other client

**Comment by ZuherLaith** [comment]
would you recommend any client close to erela.js without the need to re-write my entire project?

**Comment by parasop** [comment]
sure you can go with
https://npmjs.com/poru

**Comment by topi314** [comment]
I would recommend you look through the list here yourself and look at potential clients more in-depth https://github.com/freyacodes/Lavalink#client-libraries

Make sure it's actively maintained so you can get support for new lavalink versions quickly

Feel free to reopen this issue if the issue persists after switching, please attach your Lavalink logs then
