### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by sawa-ko** [lavalink-devs/Lavalink#795]
## Description

Currently the only way to configure lavalink is through the application.yml file, something that may not help when it comes to using lavalink in PaaS, since it is usually not possible to modify internal files of the docker image, which lavalink needs to create and/or modify the server configuration.

It would be great if lavalink could be configured with environment variables, so you don't have problems like the one mentioned above and you can use lavalink anywhere without problems.

**Comment by topi314** [comment]
This is already possible
just chain the yml path together like this:

```yml
lavalink:
    server:
        password: "youshallnotpass"    
```
to
`LAVALINK_SERVER_PASSWORD=youshallnotpass`

as for docker images you can just mount your `application.yml` into the container at `/op/Lavalink/application.yml` as described here https://hub.docker.com/r/fredboat/lavalink/

**Comment by sawa-ko** [comment]
@TopiSenpai Where can I see the environment variables available for use?

**Comment by topi314** [comment]
The yml properties map 1:1
So just look into the application.yml

**Comment by sawa-ko** [comment]
Nice, thanks.
