### ISSUE TITLE
Issue with resume option

### ISSUE THREAD

**Issue by flav-code** [lavalink-devs/Lavalink#822]
## Description

I did not activate the resume key and the players are not destroyed directly when the bot disconnects from the node
the players are never even deleted except by sending the request for the destroy 

## Version info
**Client used:** 
lavalink 3.7.3 and Shoukaku #master as Client

**Comment by topi314** [comment]
fixed in https://github.com/freyacodes/Lavalink/releases/tag/3.7.4
