### ISSUE TITLE
lavalink disconnection code 1006

### ISSUE THREAD

**Issue by enekora0** [lavalink-devs/Lavalink#836]
## Description

the lavalink disconnects with 1006 code randomly sometimes working for week sometimes daily disconnects with this reason the lavalink client and the server not in the same vps and its working fine but somethimes dropping connection very offten

## Version info
**Client used:** 
    "lavaclient": "^4.1.1",
Output of `java -version`:
```
openjdk 17.0.6 2023-01-17 LTS
OpenJDK Runtime Environment Zulu17.40+19-CA (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu17.40+19-CA (build 17.0.6+10-LTS, mixed mode, sharing)
```

Version:        3.6.2
Build time:     08.11.2022 09:02:53 UTC
Branch          HEAD
Commit:         4782f1f
Commit time:    08.11.2022 09:01:14 UTC
JVM:            17.0.6
Lavaplayer      1.3.99.1-original

**Comment by ooliver1** [comment]
Please try using 3.7.4 - the latest version.

**Comment by emma-126** [comment]
I'm on version 3.7.5 and am facing the same issue.

**Comment by topi314** [comment]
websocket close code 1006 is emitted by the websocket client if the connection randomly dies
most likely a networking issue
https://www.rfc-editor.org/rfc/rfc6455#section-7.4.1

**Comment by Bloodika** [comment]
As I see it always dies. The things is, I'm using Lavalink for wavelink and before the song ends (like 2 seconds), socket dies.

**Comment by topi314** [comment]
I can't reproduce this issue at all. It might be something up with wavelink idk

**Comment by emma-126** [comment]
You're correct, it's a Wavelink issue that was just patched recently. Thanks for your time.

**Comment by topi314** [comment]
the original issue was opened with lavaclient. I'm gonna close it in a while if we don't get more info

**Comment by topi314** [comment]
I'm gonna close this due to inactivity
if this happens again feel free to reopen
