### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by ukcai696969** [lavalink-devs/Lavalink#855]
## Description
hello im using poru it has embedded fiters and when i enable them i get a error

## Version info
3.6.2

Output of `java -version`:
```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)
```

![image](https://user-images.githubusercontent.com/111254389/225310363-16a6f811-d12e-4635-9d52-8c21ede69865.png)

**Comment by devoxin** [comment]
You're sending `true` for `distortion`. This is not the correct way of configuring the distortion filter. You'll need to query your library maintainer about this as it's not an issue with the Lavalink server.
