### ISSUE TITLE
Oshi dep - rare stats issue on Windows

### ISSUE THREAD

**Issue by aikaterna** [lavalink-devs/Lavalink#858]
## Description
I have a user that is using a 64-bit Windows 10 device to host Lavalink and his bot, and he encountered a stats issue/oshi issue when using a Lavalink.jar with oshi 5.7.4, this can be seen in his log at https://gist.githubusercontent.com/Cog-CreatorsBot/93ac8762eee30fed0b661f4f04fd7a3e/raw/3325e473fc269fae52350bd1d7b940fe6470e076/spring_1.log

```
2022-01-06 18:17:33.597  WARN 4508 --- [pool-2-thread-1] o.util.platform.windows.WmiQueryHandler  : COM exception: Invalid Query: SELECT NAME,PRIORITY,CREATIONDATE,PROCESSID,PARENTPROCESSID,READTRANSFERCOUNT,WRITETRANSFERCOUNT,PRIVATEPAGECOUNT,PAGEFAULTSPERSEC FROM Win32_Process WHERE NOT Name LIKE"%_Total"
```

This issue is reported in https://github.com/oshi/oshi/issues/1710 and resolved with release 5.8.2.

## Version info
**Client used:** Red-Lavalink 0.9.0

Output of `java -version`:

Sorry I don't have the output of `java -version` as this issue was brought up to me in early 2022, was previously reported in https://github.com/freyacodes/Lavalink/pull/601 as I attempted to resolve it. The individual with this reported log was using Java 11.0.13.

**Comment by topi314** [comment]
what was the issue with upgrading to `5.8.2` again?

**Comment by aikaterna** [comment]
The Process object returned that contains the stats was formed differently in that version and the current implementation can't read the stats it provides.

**Comment by aikaterna** [comment]
IIRC this should be the object I'm talking about but it's been a while since I looked at this.
https://github.com/freyacodes/Lavalink/blob/751b565fc8490efc014022a51643a5587092a4f2/LavalinkServer/src/main/java/lavalink/server/io/StatsCollector.kt#L51

**Comment by topi314** [comment]
a fix for this has been release in https://github.com/lavalink-devs/Lavalink/releases/tag/3.7.11
