### ISSUE TITLE
Error here

### ISSUE THREAD

**Issue by MrTabaOfficial** [lavalink-devs/Lavalink#871]
![image](https://user-images.githubusercontent.com/121251795/234722764-464e9bef-8a6b-4021-8670-fd1604965f47.png)
there says that video is not available. link is active :/

**Comment by aikaterna** [comment]
Update your Lavalink.jar, it's out of date. Check out the Releases tab on this repo.

**Comment by Tomato6966** [comment]
It's possible that youtube videos are not able to be played without logging into youtube.

**Comment by MrTabaOfficial** [comment]
> It's possible that youtube videos are not able to be played without logging into YouTube.

it was able to play and now not ?? it was working normally 1 week ago

**Comment by topi314** [comment]
yt constantly does breaking changes
did updating help?

**Comment by MrTabaOfficial** [comment]
> yt constantly does breaking changes did updating help?

Yes It helped Thanks <3

**Comment by melzyy** [comment]
hey, getting the same error rn. should i use the dev build?

EDIT: yeah, that fixed that, fuck youtube i guess

**Comment by topi314** [comment]
dev has no relevant changes compared to the latest release (v3.7.5)
In the future please open a new discussion/issue or join our discord (link in readme)
