### ISSUE TITLE
YouTube 403 not success

### ISSUE THREAD

**Issue by AGuyNamedJens** [lavalink-devs/Lavalink#897]
## Description

Getting 403s on trying to load anything resulting in "playing" and immediately leaving after

## Version info
**Client used:** 
Erela.js since i haven't updated libraries yet, seemed to work fine until i updated lavalink..

Output of `java -version` (it's thrown with the full log):
```
      | 2023-06-27 10:49:53.629 ERROR 861757 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of sJXZ9Dok7u8
0|ll       |
0|ll       | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
0|ll       |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:116) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:361) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager$$Lambda$733/0x00000000448fd748.run(Unknown Source) ~[na:na]
0|ll       |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
0|ll       |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
0|ll       |    at java.base/java.lang.Thread.run(Thread.java:853) ~[na:na]
0|ll       |    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
0|ll       |   lavaplayer.version: 1.4.0-original
0|ll       |   os.arch: amd64
0|ll       |   os.name: Linux
0|ll       |   os.version: 5.4.0-113-generic
0|ll       |   java.vendor: AdoptOpenJDK
0|ll       |   java.version: 16.0.1
0|ll       |   java.runtime.version: 16.0.1+9
0|ll       |   java.vm.version: openj9-0.26.0
0|ll       | Caused by: java.lang.RuntimeException: Not success status code: 4030|ll       |    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:87) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:123) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:105) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:157) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:173) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271) ~[na:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:45) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:78) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:58) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:50) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:104) ~[lavaplayer-1.4.0.jar!/:na]
0|ll       |    ... 5 common frames omitted
0|ll       |
```

**Comment by N1C0exe** [comment]
I suggest u to post this on https://github.com/Walkyst/lavaplayer-fork/issues/108 becouse is a lavaplayer issue . Join the Lavalink Discord server if u want :) there is a thread open about this error

**Comment by AGuyNamedJens** [comment]
> 

I can't join the server because discord is limited to 100 without paying them, and i practically can't leave any either..
And i suppose this means there's no fix yet?

**Comment by topi314** [comment]
see the lavaplayer issue, news will get posted there (there is no fix yet)

**Comment by AGuyNamedJens** [comment]
Alright then, will sub to that thread. Guess youtube has been messing their APIs again as usual in attempts to break down music bots.. lol

**Comment by DJHammers** [comment]
same issue here

**Comment by N1C0exe** [comment]
> same issue here https://github.com/Walkyst/lavaplayer-fork/issues/108

**Comment by vishalcodez** [comment]
Same issue here + destroying all the playing players !! nvm

**Comment by topi314** [comment]
you can give this a try https://github.com/lavalink-devs/Lavalink/tree/patch/yt-player-params

**Comment by xhyrom** [comment]
> you can give this a try https://github.com/lavalink-devs/Lavalink/tree/patch/yt-player-params

I'll try it, thanks!

**Comment by vishalcodez** [comment]
Now working good for you guys ??

**Comment by imanimtiyaz20** [comment]
> Now working good for you guys ??

seems to work pretty fine for me.

**Comment by vishalcodez** [comment]
Can i see your application.yml file ?

**Comment by imanimtiyaz20** [comment]
> Can i see your application.yml file ?

i use the default application.yml file with lavaSrc installed

**Comment by vishalcodez** [comment]
Ohh okay tq

**Comment by topi314** [comment]
this has been fixed in
<https://github.com/lavalink-devs/Lavalink/releases/tag/4.0.0-beta.3>
<https://github.com/lavalink-devs/Lavalink/releases/tag/3.7.8>

**Comment by SylveonDeko** [comment]
still having this issue in 3.7.9

**Comment by SylveonDeko** [comment]
```
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
5|Lavalink  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
5|Lavalink  | 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
5|Lavalink  | 	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
5|Lavalink  |   lavaplayer.version: 1.5.1
5|Lavalink  |   os.arch: amd64
5|Lavalink  |   os.name: Linux
5|Lavalink  |   os.version: 5.15.0-88-generic
5|Lavalink  |   java.vendor: Private Build
5|Lavalink  |   java.version: 18.0.2-ea
5|Lavalink  |   java.runtime.version: 18.0.2-ea+9-Ubuntu-222.04
5|Lavalink  |   java.vm.version: 18.0.2-ea+9-Ubuntu-222.04
5|Lavalink  | Caused by: java.lang.RuntimeException: Not success status code: 403
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271) ~[na:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:59) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:51) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-1.5.1.jar!/:na]
5|Lavalink  | 	... 4 common frames omitted
```

**Comment by N1C0exe** [comment]
> ```
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
> 5|Lavalink  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
> 5|Lavalink  | 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
> 5|Lavalink  | 	Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
> 5|Lavalink  |   lavaplayer.version: 1.5.1
> 5|Lavalink  |   os.arch: amd64
> 5|Lavalink  |   os.name: Linux
> 5|Lavalink  |   os.version: 5.15.0-88-generic
> 5|Lavalink  |   java.vendor: Private Build
> 5|Lavalink  |   java.version: 18.0.2-ea
> 5|Lavalink  |   java.runtime.version: 18.0.2-ea+9-Ubuntu-222.04
> 5|Lavalink  |   java.vm.version: 18.0.2-ea+9-Ubuntu-222.04
> 5|Lavalink  | Caused by: java.lang.RuntimeException: Not success status code: 403
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:271) ~[na:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:74) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:59) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:51) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-1.5.1.jar!/:na]
> 5|Lavalink  | 	... 4 common frames omitted
> ```

yes me too
