### ISSUE TITLE
Region Designation?

### ISSUE THREAD

**Issue by majorcyto** [lavalink-devs/Lavalink#9]
I see in the Eris client example they designated regions. Is it possible to 'assign' a lavalink node to a region? If so what is the config style like for that?

Thanks!

**Comment by freyacodes** [comment]
Not at the moment. This is something I will likely begin working on if I get a significant amount of nodes outside the US

**Comment by majorcyto** [comment]
Sweet, thanks!

**Comment by freyacodes** [comment]
The original lavalink client has moved https://github.com/Fredboat/Lavalink-client
