### ISSUE TITLE
Not emitting TrackEndEvent for a YouTube Livestream

### ISSUE THREAD

**Issue by devoxin** [lavalink-devs/Lavalink#90]
A server I'm in (that serves as a radio server) has 9 bots; all playing different streams, all playing from the same Lavalink server. There's one bot in particular though that drops its stream entirely usually immediately or after a while, but doesn't seem to be receiving any events or emitting any events (log level is set to debug and the client's websocket isn't logging any `Received Event` messages). The link to the stream that's causing issues: https://www.youtube.com/watch?v=ueupsBPNkSc

**Comment by freyacodes** [comment]
The `debug.log` would be useful
