### ISSUE TITLE
YT Playlists

### ISSUE THREAD

**Issue by Tomato6966** [lavalink-devs/Lavalink#909]
Link: https://www.youtube.com/playlist?list=PLMC9KNkIncKtPzgY-5rmhvj7fax8fdxoj

Problem: Playlist has 200 songs, i have 3 yt-playlist-pages but can only fetch 140 tracks
Problem 2: No playlist informatin, except name is provided...

Solution idea for 2:
- You could add it via pluginInfo, at least author, last updated, etc.

**Comment by topi314** [comment]
please follow the issue template, it exists for a reason.
