### ISSUE TITLE
Feature-Request: "Load multiple local tracks"

### ISSUE THREAD

**Issue by Tomato6966** [lavalink-devs/Lavalink#927]
## Description
loadtracks by providing a folder of mp3 files (I wouldn't allow nested requests just for the folder *.mp3|*.mov|*.ogg|etc.etc.

## To Reproduce
-

## Expected behavior
when doing `/loadtracks?identifier=/home/path/to/folder/` it loads all existing possible files which load the tracks
when doing `/loadtracks?identifier=/home/path/to/folder/*.mp3` it only loads files ending with .mp3 (aka glob support)

## Version info
Would suggest to implement this in Lavalink v4

Output of `java -version`:
```
openjdk version "20" 2023-03-21
OpenJDK Runtime Environment (build 20+36-2344)
OpenJDK 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)
```

Lavalink Logs:
```
Version:        4.0.0-beta.2
Build time:     21.07.2023 13:54:04 UTC
Branch          HEAD
Commit:         30bedca
Commit time:    21.07.2023 13:20:01 UTC
JVM:            20
Lavaplayer      1.4.2
```

## Additional context
LoadType: "playlist"
Configuration option for application.yml "localfilespages 5" (like yt pages, 1 page === 100 tracks)

**Comment by topi314** [comment]
This is not a bug but a lavaplayer feature request.

**Comment by freyacodes** [comment]
@topi314 to be fair, there's no button to submit an issue that isn't a bug report

@Tomato6966 This is more appropriate for https://github.com/lavalink-devs/lavaplayer

**Comment by topi314** [comment]
GitHub discussions should be used for such things instead

**Comment by freyacodes** [comment]
Sure, but we don't mention that

**Comment by Tomato6966** [comment]
Yes I also didn't know where to post it, but may i open an "issue / discussion" in lavaplayer repo?

**Comment by topi314** [comment]
There is always the option to open a blank issue

Instead create a discussion in the repo mentioned above & link it here

**Comment by freyacodes** [comment]
> There is always the option to open a blank issue

True. I missed that when I went to check

**Comment by Tomato6966** [comment]
Okay I'll mind that in the future:
<https://github.com/lavalink-devs/lavaplayer/discussions/3>

(BTW if you do `<LINK>` it looks cool like that^^)
