### ISSUE TITLE
Loading search results from SoundCloud failed.

### ISSUE THREAD

**Issue by LucasB25** [lavalink-devs/Lavalink#941]
## To Reproduce
a person simply played music

## Version info
PORU 4.2

Output of `java -version`:
```
17.0.7
```

Lavalink Logs:
```
https://sourceb.in/8Ckn9EL7yR
```
https://sourceb.in/YhoOI1Owr0 version 3.7.8

**Comment by topi314** [comment]
Read timeout
Fix your internet
