### ISSUE TITLE
Dispatch event when paused or resumed

### ISSUE THREAD

**Issue by Fyphen1223** [lavalink-devs/Lavalink#956]
### Change request

Dispatch event when paused or resumed with WS.
Should be with played duration and more.

### Relevance

It will improve quality of Bot.

### Could this be a plugin instead?

No.

### Checklist

- [x] I have checked for duplicate issues
- [X] I have checked for existing plugins

**Comment by freyacodes** [comment]
This is not relevant as it is no longer possible to pause via WS in version 4.x.

Besides, what you have described seems to already have been implemented

https://github.com/lavalink-devs/Lavalink/blob/v3-legacy/LavalinkServer/src/main/java/lavalink/server/io/WebSocketHandler.kt#L122-L126
