### ISSUE TITLE
Java 8 compatibility issues 

### ISSUE THREAD

**Issue by freyacodes** [lavalink-devs/Lavalink#96]
It appears that the jars compiled by Javac 9 on TeamCity have faulty compatibility with Java 8. A solution could be to use a different version of the JDK on TC.

```
java.lang.ClassNotFoundException: com.sedmelluq.discord.lavaplayer.jdaudp.NativeAudioSendFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

Temporary workarounds:
* Upgrading to at least Java 9
* Compiling from source with `./gradlew build`

**Comment by itsfolf** [comment]
Compiling from the source resulted in the same error

**Comment by freyacodes** [comment]
What version did you compile with? Run `java -version`

**Comment by itsfolf** [comment]
Compiled with "1.8.0_144" and ran with "1.8.0_162"

**Comment by freyacodes** [comment]
At this point, I am considering abandoning Java 8 support. How come that you haven't just upgraded to Java 9 or 10?

**Comment by itsfolf** [comment]
It's actually kinda intriguing, I had never seen java 9 or 10 being used in production except for the past two days, I'll do some test just to make sure everything I currently use is compatible and I guess that's the way to go.

EDIT: Just updated to java 10 and that worked.

**Comment by schnapster** [comment]
This should be fixed by this PR: https://github.com/Frederikam/Lavalink/pull/101, which was merged into dev.

**Comment by PassTheMayo** [comment]
@Frederikam If this is fixed, can we close this?

**Comment by freyacodes** [comment]
👌

**Comment by freyacodes** [comment]
I suppose we'll remain on Java 8 source compatibility
