### ISSUE TITLE
Accept raw file from client

### ISSUE THREAD

**Issue by Fyphen1223** [lavalink-devs/Lavalink#960]
### Change request

Making Lavalink to accept requests which contain raw files such as mp3 or mp4. You might think that can be replaced by playing local files, but if I have to do that, I'll run into some problems (I want to play music or audio temporary, not to save file as the local file because it's too tedious if I have to handle all of the requests in the code manually)

### Relevance

Might be useful for some developers like me lol

### Could this be a plugin instead?

I'm not sure how can I manipulate that :(

### Checklist

- [X] I have checked for duplicate issues
- [X] I have checked for existing plugins

**Comment by duncte123** [comment]
I'd just upload the file to a google cloud bucket that is configured to auto-delete the items after like a year and then make the urls publicly accessible so lavalink can play them

**Comment by freyacodes** [comment]
You can most likely use HTTP. If you have a local file, you can expose it through a web server. If you have the file as a Discord attachment, you can simply feed the attachment URL to Lavalink. Uploading files to Lavalink seems outside the scope of Lavalink, and could potentially be implemented as a plugin.
